Repository knative-extensions/eventing-kafka-broker, pull requests merged in 2020-10, with the labels that each got.

#241 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#244 Expose metrics defined by the spec in Prometheus format
  data-plane/core/pom.xml
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/metrics/MetricsOptionsProvider.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/metrics/MetricsOptionsProviderTest.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerRecordOffsetStrategyFactory.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/Main.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactoryTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/UnorderedConsumerTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategyTest.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/Main.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/RequestHandler.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/RequestHandlerTest.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/integration/ReceiverVerticleTest.java
  data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java
Labels: approved, cla: yes, lgtm, size/L

#245 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1/expansion_generated.go
  vendor/knative.dev/eventing/pkg/reconciler/names/names.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/builder.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/configmap.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/configmappropagation.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/containersource.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/customresourcedefinition.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/deployment.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/endpoints.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/eventtype.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/factory.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/listers.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/mock_dynamic_client.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/mock_event_recorder.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/namespace.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/pingsource.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/service.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/sinkbinding.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/unstructured.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/apiserversouce.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/listers.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1beta1/apiserversource.go
  vendor/knative.dev/eventing/pkg/utils/utils.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_tracing_test_helper.go
  vendor/knative.dev/eventing/test/lib/config.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/eventing/test/lib/resources/constants.go
  vendor/knative.dev/pkg/client/injection/apiextensions/client/client.go
  vendor/knative.dev/pkg/client/injection/apiextensions/client/fake/fake.go
  vendor/knative.dev/pkg/metrics/testing/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#246 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/duck/v1/delivery_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/delivery_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/channel/message_receiver.go
  vendor/knative.dev/eventing/pkg/reconciler/sugar/filters.go
  vendor/knative.dev/eventing/pkg/reconciler/sugar/labels.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/factory.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/factory.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1beta1/factory.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_control_plane_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_data_plane_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_tracing_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_header_single_event_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_tracing_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/tracing_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_channel_flow_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_event_transformation_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_redelivery_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_defaulter_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_dls_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_event_tranformation_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/trigger_no_broker_test_helper.go
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#251 Ignore some directories in coverage calculation
  .codecov.yaml
Labels: approved, cla: yes, lgtm, size/XS

#252 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#254 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/reconciler/testing/customresourcedefinition.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/factory.go
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/markdown-link-check-config.rc
  vendor/knative.dev/test-infra/scripts/markdown-lint-config.rc
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#255 [release-0.18] Fix Sink not released (#238)
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#257 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/duck/v1/delivery_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/delivery_types.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_validation.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1beta1/sequence_validation.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#259 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S

#261 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#258 Add Retry Configs to EgressConfig
  control-plane/pkg/contract/contract.pb.go
  data-plane/contract/src/main/java/dev/knative/eventing/kafka/broker/contract/DataPlaneContract.java
  proto/def/contract.proto
Labels: approved, cla: yes, lgtm, size/XL

#263 Add Retry Config to EgressConfig during broker reconciliation
  control-plane/config/500-controller.yaml
  control-plane/pkg/config/env_config.go
  control-plane/pkg/config/env_config_test.go
  control-plane/pkg/core/config/utils.go
  control-plane/pkg/core/config/utils_test.go
  control-plane/pkg/reconciler/broker/broker.go
  control-plane/pkg/reconciler/broker/broker_test.go
  control-plane/pkg/reconciler/testing/factory.go
  control-plane/pkg/reconciler/testing/objects_broker.go
  data-plane/config/template/500-dispatcher.yaml
  go.mod
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#265 Jlink to reduce container image size
  data-plane/docker/Dockerfile
  data-plane/docker/generate_jdk.sh
  test/data-plane/library.sh
Labels: approved, cla: yes, lgtm, size/M

#269 🐛 add delay in liveness for webhook
  control-plane/config/sink/500-webhook.yaml
Labels: approved, cla: yes, lgtm, size/XS

#273 [Automated] Update actions
  .github/workflows/knative-security.yaml
Labels: approved, cla: yes, lgtm, size/XS

#271 [release-0.18] add delay in liveness for webhook (#269)
  control-plane/config/sink/500-webhook.yaml
Labels: approved, cla: yes, lgtm, size/XS

#270 Removed `java.compiler` from used jmods
  data-plane/docker/generate_jdk.sh
Labels: approved, cla: yes, lgtm, size/XS

#275 Fix docker build
  data-plane/docker/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#276 [Automated] Update actions
  .github/workflows/knative-security.yaml
Labels: approved, cla: yes, lgtm, size/XS

#280 Some moved files, some renamed classes
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/file/ResourcesReconcilerAdapter.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/reconciler/ResourcesReconciler.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/wrappers/Egress.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/wrappers/EgressWrapper.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/wrappers/EventMatcher.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/wrappers/Filter.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/wrappers/Resource.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/wrappers/ResourceWrapper.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/file/FileWatcherTest.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/file/ResourcesReconcilerAdapterTest.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/testing/CoreObjects.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/wrappers/EgressWrapperTest.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/wrappers/EventMatcherTest.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/wrappers/ResourceWrapperTest.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerRecordHandler.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerRecordOffsetStrategyFactory.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerVerticleFactory.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/Main.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ResourcesManager.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactory.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/ResourcesManagerTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactoryTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/ConsumerVerticleFactoryMock.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/UnorderedConsumerTest.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/Main.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/RequestHandler.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/RequestHandlerTest.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/integration/ReceiverVerticleTest.java
  data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java
Labels: approved, cla: yes, lgtm, size/L

#268 The Broker retries sending events
  control-plane/pkg/reconciler/broker/broker.go
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/wrappers/Egress.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ResourcesManager.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerRecordSender.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactory.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactoryTest.java
  test/e2e/broker_redelivery_test.go
  test/e2e/broker_trigger_test.go
Labels: approved, cla: yes, lgtm, size/L

#282 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/lib/recordevents/resources.go
  vendor/knative.dev/eventing/test/lib/resources/kube.go
  vendor/knative.dev/eventing/test/lib/sender/resources.go
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/hash/bucketer.go
  vendor/knative.dev/pkg/test/helpers/name.go
  vendor/knative.dev/pkg/webhook/certificates/resources/certs.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#289 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/reconciler/testing/sinkbinding.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/sinkbinding.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1beta1/sinkbinding.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/memstats.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#288 Remove config-logging volume and add server config for the sink
  control-plane/config/500-controller.yaml
  data-plane/config/sink/100-config-kafka-sink-data-plane.yaml
  data-plane/config/sink/template/500-receiver.yaml
Labels: approved, cla: yes, lgtm, size/S

#293 Using the new update-deps script
  go.mod
  go.sum
  hack/k8s-client-go.patch
  hack/update-deps.sh
  vendor/github.com/google/mako/go/quickstore/BUILD
  vendor/github.com/google/mako/internal/go/common/BUILD
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/utilities/BUILD.bazel
  vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/BUILD
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#295 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/container_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/container_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/container_conversion.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_event_tranformation_test_helper.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info_store.go
  vendor/knative.dev/eventing/test/lib/recordevents/observer/observer.go
  vendor/knative.dev/eventing/test/lib/recordevents/observer/reply.go
  vendor/knative.dev/eventing/test/lib/recordevents/recorder_vent/constructor.go
  vendor/knative.dev/eventing/test/lib/recordevents/resources.go
  vendor/knative.dev/eventing/test/test_images/recordevents/main.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#300 update to pkg KubeTest
  go.mod
  go.sum
  test/e2e/broker_trigger_test.go
  test/e2e/conformance/data_plane_conformance_test.go
  test/e2e/kafka_sink_test.go
  test/pkg/kafka/verify_messages_topic.go
  test/pkg/kafka/verify_num_partitions_replication.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_data_plane_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_tracing_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_crd_metadata_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_tracing_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/rbac.go
  vendor/knative.dev/eventing/test/conformance/helpers/tracing/zipkin.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_channel_flow_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_event_transformation_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_defaulter_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/sequence_test_helper.go
  vendor/knative.dev/eventing/test/lib/client.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/eventing/test/lib/logexporter.go
  vendor/knative.dev/eventing/test/lib/operation.go
  vendor/knative.dev/eventing/test/lib/recordevents/observer/observer.go
  vendor/knative.dev/eventing/test/lib/recordevents/observer/reply.go
  vendor/knative.dev/eventing/test/lib/recordevents/resources.go
  vendor/knative.dev/eventing/test/lib/resources/kube.go
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/ingress/ingress.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/test/monitoring/doc.go
  vendor/knative.dev/pkg/test/monitoring/monitoring.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/zipkin/doc.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/pkg/tracing/setup.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#304 Remove Kubernetes dependency
  go.mod
  test/pkg/kafka/verify_num_partitions_replication.go
  third_party/VENDOR-LICENSE/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/LICENSE
  vendor/k8s.io/kubernetes/LICENSE
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/LICENSE
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/doc.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#305 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#302 [master] Upgrade to latest dependencies
  control-plane/pkg/client/injection/reconciler/eventing/v1alpha1/kafkasink/reconciler.go
  go.mod
  go.sum
  vendor/github.com/tsenart/vegeta/v12/LICENSE
  vendor/github.com/tsenart/vegeta/v12/lib/histogram.go
  vendor/knative.dev/eventing/pkg/channel/message_dispatcher.go
  vendor/knative.dev/eventing/pkg/configmap/store.go
  vendor/knative.dev/eventing/pkg/kncloudevents/populate_span_transformer.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/containersource.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/listers.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/containersource.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/listers.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1beta1/containersource.go
  vendor/knative.dev/eventing/pkg/tracing/attributes.go
  vendor/knative.dev/eventing/pkg/tracing/names.go
  vendor/knative.dev/eventing/pkg/tracing/setup.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_tracing_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_tracing_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/tracing/zipkin.go
  vendor/knative.dev/eventing/test/conformance/helpers/tracing_test_helper.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/eventing/test/test_images/utils.go
  vendor/knative.dev/pkg/apis/duck/README.md
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/two_lane_queue.go
  vendor/knative.dev/pkg/hash/doc.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/kmeta/ownerrefable_accessor.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/test/gcs/gcs.go
  vendor/knative.dev/pkg/test/mako/alerter/github/issue.go
  vendor/knative.dev/pkg/test/mako/config/configmap.go
  vendor/knative.dev/pkg/test/mako/sidecar.go
  vendor/knative.dev/pkg/test/monitoring/doc.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/tinterface.go
  vendor/knative.dev/pkg/tracing/opencensus.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/shellcheck-presubmit.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#306 Reduce container images size
  data-plane/config/sink/template/500-receiver.yaml
  data-plane/config/template/500-dispatcher.yaml
  data-plane/config/template/500-receiver.yaml
  data-plane/docker/Dockerfile
  test/data-plane/library.sh
Labels: approved, cla: yes, lgtm, size/M

#284 Use milliseconds for backoff delay in the contract
  control-plane/cmd/kafka-controller/main.go
  control-plane/config/500-controller.yaml
  control-plane/pkg/config/env_config.go
  control-plane/pkg/config/env_config_test.go
  control-plane/pkg/contract/contract.pb.go
  control-plane/pkg/core/config/utils.go
  control-plane/pkg/core/config/utils_test.go
  control-plane/pkg/reconciler/broker/broker.go
  control-plane/pkg/reconciler/broker/broker_test.go
  control-plane/pkg/reconciler/broker/controller.go
  control-plane/pkg/reconciler/broker/controller_test.go
  control-plane/pkg/reconciler/testing/factory.go
  data-plane/contract/src/main/java/dev/knative/eventing/kafka/broker/contract/DataPlaneContract.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactory.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactoryTest.java
  go.mod
  go.sum
  proto/def/contract.proto
  vendor/github.com/rickb777/date/period/arithmetic.go
  vendor/github.com/rickb777/date/period/designator.go
  vendor/github.com/rickb777/date/period/format.go
  vendor/github.com/rickb777/date/period/parse.go
  vendor/github.com/rickb777/date/period/period.go
  vendor/github.com/rickb777/date/period/period64.go
  vendor/github.com/rickb777/plural/go.mod
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#308 Improve error messages in kafka-consumer test image
  test/test_images/kafka-consumer/consumer.go
Labels: approved, cla: yes, lgtm, size/M

#307 Add links and badges to the readme
  README.md
Labels: approved, cla: yes, lgtm, size/M

#311 Added Egress uid and renamed Resource id to uid
  control-plane/pkg/contract/contract.pb.go
  control-plane/pkg/core/config/egress.go
  control-plane/pkg/core/config/egress_test.go
  control-plane/pkg/core/config/resource.go
  control-plane/pkg/core/config/resource_test.go
  control-plane/pkg/log/log_marshaller.go
  control-plane/pkg/reconciler/broker/broker.go
  control-plane/pkg/reconciler/broker/broker_test.go
  control-plane/pkg/reconciler/sink/kafka_sink.go
  control-plane/pkg/reconciler/sink/kafka_sink_test.go
  control-plane/pkg/reconciler/trigger/trigger.go
  control-plane/pkg/reconciler/trigger/trigger_test.go
  data-plane/contract/src/main/java/dev/knative/eventing/kafka/broker/contract/DataPlaneContract.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/wrappers/ResourceWrapper.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/testing/CoreObjects.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/wrappers/ResourceWrapperTest.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/RequestHandlerTest.java
  data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java
  proto/def/contract.proto
Labels: approved, cla: yes, lgtm, size/XL

#314 Update deps + fix
  go.mod
  go.sum
  test/e2e-common.sh
  vendor/knative.dev/eventing/pkg/apis/config/defaults.go
  vendor/knative.dev/eventing/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/subscribable_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_defaults.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/broker_defaults.go
  vendor/knative.dev/eventing/pkg/apis/messaging/register.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/in_memory_channel_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/in_memory_channel_lifecycle.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/trigger/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1beta1/broker/reconciler.go
  vendor/knative.dev/eventing/test/conformance/helpers/tracing/zipkin.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_channel_flow_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_defaulter_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_event_tranformation_test_helper.go
  vendor/knative.dev/eventing/test/lib/client.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info_store.go
  vendor/knative.dev/eventing/test/lib/resources/variables.go
  vendor/knative.dev/eventing/test/lib/typemeta.go
  vendor/knative.dev/eventing/test/performance/infra/receiver/receiver.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#250 Add release notes generator script
  hack/release-notes.sh
Labels: approved, cla: yes, lgtm, size/S

#322 Change logging during e2e tests
  test/pkg/config/100-config-logging.yaml
Labels: approved, cla: yes, lgtm, size/XS

#321 [0.18] Backport fixes found during continuous testing in #249
  data-plane/config/100-config-kafka-broker-data-plane.yaml
  data-plane/config/sink/100-config-kafka-sink-data-plane.yaml
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerRecordHandler.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpSinkResponseHandler.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpSinkResponseHandlerTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/UnorderedConsumerTest.java
  go.sum
  test/pkg/config/100-config-logging.yaml
Labels: approved, cla: yes, lgtm, size/L

#320 Removed test_images
  hack/tools.go
  vendor/knative.dev/eventing/test/test_images/filterevents/main.go
  vendor/knative.dev/eventing/test/test_images/filterevents/pod.yaml
  vendor/knative.dev/eventing/test/test_images/sequencestepper/main.go
  vendor/knative.dev/eventing/test/test_images/sequencestepper/pod.yaml
  vendor/knative.dev/eventing/test/test_images/transformevents/main.go
  vendor/knative.dev/eventing/test/test_images/transformevents/pod.yaml
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#324 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/duck/v1/fuzzer.go
  vendor/knative.dev/eventing/pkg/channel/message_dispatcher.go
  vendor/knative.dev/eventing/pkg/channel/message_receiver.go
  vendor/knative.dev/eventing/pkg/channel/metrics.go
  vendor/knative.dev/eventing/pkg/channel/stats_reporter.go
  vendor/knative.dev/eventing/pkg/kncloudevents/utils.go
  vendor/knative.dev/eventing/test/e2e/helpers/parallel_test_helper.go
  vendor/knative.dev/eventing/test/lib/resources/kube.go
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/config.go
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/flags/e2e_flags.go
  vendor/knative.dev/pkg/test/gcs/gcs.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/mako/config/benchmark.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/tinterface.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#325 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#326 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/lib/duck/resource_checks.go
  vendor/knative.dev/eventing/test/lib/duck/resource_getters.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#329 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#330 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#327 Implement common reconciler in data plane
  data-plane/config/template/500-dispatcher.yaml
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/file/ResourcesReconcilerAdapter.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/reconciler/EgressReconcilerListener.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/reconciler/IngressReconcilerListener.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/reconciler/ResourcesReconciler.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/ResourcesReconcilerImpl.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/utils/CollectionsUtils.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/file/ResourcesReconcilerAdapterTest.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/EgressReconcilerListenerMock.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/IngressReconcilerListenerMock.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/ResourceReconcilerTestRunner.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/ResourcesReconcilerImplTest.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/testing/CoreObjects.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/utils/CollectionsUtilsTest.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerDeployer.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerRecordOffsetStrategyFactory.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerVerticleFactory.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/DispatcherEnv.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/Main.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ResourcesManager.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactory.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerDeployerTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactoryTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/ConsumerVerticleFactoryMock.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/UnorderedConsumerTest.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/Main.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/RequestHandler.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/RequestHandlerTest.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/integration/ReceiverVerticleTest.java
  data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java
Labels: approved, cla: yes, lgtm, size/XXL

#333 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/oauth2/go.mod
  vendor/golang.org/x/oauth2/go.sum
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/google.golang.org/api/internal/creds.go
  vendor/google.golang.org/api/internal/impersonate/impersonate.go
  vendor/google.golang.org/api/internal/service-account.json
  vendor/google.golang.org/api/internal/settings.go
  vendor/google.golang.org/api/option/option.go
  vendor/google.golang.org/api/storage/v1/storage-api.json
  vendor/google.golang.org/api/storage/v1/storage-gen.go
  vendor/google.golang.org/api/transport/grpc/dial.go
  vendor/google.golang.org/api/transport/http/dial.go
  vendor/google.golang.org/api/transport/internal/dca/dca.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/sinkbinding_context.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/sinkbinding_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/sinkbinding_context.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/sinkbinding_types.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_data_plane_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/tracing_test_helper.go
  vendor/knative.dev/eventing/test/lib/k8s_events.go
  vendor/knative.dev/eventing/test/lib/operation.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info_store.go
  vendor/knative.dev/eventing/test/lib/recordevents/recorder_vent/constructor.go
  vendor/knative.dev/eventing/test/lib/recordevents/resources.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XXL

#340 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#341 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/test/lib/recordevents/observer/observer.go
  vendor/knative.dev/eventing/test/lib/recordevents/observer/reply.go
  vendor/knative.dev/pkg/logging/object_encoders.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/webhook/certificates/certificates.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/M

#343 ConsumerVerticleFactory doesn't return future anymore
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerDeployer.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerVerticleFactory.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactory.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerDeployerTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactoryTest.java
Labels: approved, cla: yes, lgtm, size/M

#344 Removed wrappers
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/filter/Filter.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/filter/impl/AttributesFilter.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/wrappers/Egress.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/wrappers/EgressWrapper.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/wrappers/Resource.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/wrappers/ResourceWrapper.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/file/FileWatcherTest.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/filter/impl/AttributesFilterTest.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/testing/CoreObjects.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/wrappers/EgressWrapperTest.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/wrappers/ResourceWrapperTest.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerRecordHandler.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactory.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerDeployerTest.java
Labels: approved, cla: yes, lgtm, size/XXL

#345 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/inmemorychannel.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info.go
  vendor/knative.dev/eventing/test/lib/recordevents/observer/observer.go
  vendor/knative.dev/eventing/test/lib/recordevents/resources.go
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/M

#347 Use the network.GetServiceHostname helper
  control-plane/pkg/reconciler/base/receiver_condition_set.go
  control-plane/pkg/reconciler/testing/objects_broker.go
  control-plane/pkg/reconciler/testing/objects_sink.go
  vendor/knative.dev/eventing/pkg/reconciler/names/mtbroker.go
  vendor/knative.dev/eventing/pkg/reconciler/names/names.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#335 Fix flaky test
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/integration/ReceiverVerticleTest.java
Labels: approved, cla: yes, lgtm, size/XS

#348 [master] Upgrade to latest dependencies
  control-plane/pkg/client/injection/reconciler/eventing/v1alpha1/kafkasink/reconciler.go
  go.mod
  go.sum
  vendor/github.com/cloudevents/sdk-go/v2/binding/transformer/add_metadata.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/transformer/default_metadata.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/transformer/delete_metadata.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/transformer/doc.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/transformer/set_metadata.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/transformer/version.go
  vendor/knative.dev/eventing/pkg/channel/config.go
  vendor/knative.dev/eventing/pkg/channel/history_transformer.go
  vendor/knative.dev/eventing/pkg/channel/message_dispatcher.go
  vendor/knative.dev/eventing/pkg/channel/message_receiver.go
  vendor/knative.dev/eventing/pkg/channel/metrics.go
  vendor/knative.dev/eventing/pkg/channel/references.go
  vendor/knative.dev/eventing/pkg/channel/stats_reporter.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/trigger/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1beta1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/configmap/reader.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_data_plane_helper.go
  vendor/knative.dev/eventing/test/lib/client.go
  vendor/knative.dev/eventing/test/test_images/utils.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#346 Implemented message passing between FileWatcher and Vert.x
  data-plane/core/pom.xml
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/eventbus/ContractMessageCodec.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/eventbus/ContractPublisher.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/file/ResourcesReconcilerAdapter.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/ResourcesReconcilerMessageHandler.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/eventbus/ContractPublisherTest.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/file/ResourcesReconcilerAdapterTest.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/ResourcesReconcilerMessageHandlerTest.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerDeployerVerticle.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/Main.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerDeployerVerticleTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/UnorderedConsumerTest.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/Main.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/ReceiverVerticle.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/RequestMapper.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/ProbeHandlerTest.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/ReceiverVerticleTest.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/RequestMapperTest.java
  data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java
Labels: approved, cla: yes, lgtm, size/XL

#355 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#357 [master] Upgrade to latest dependencies
  control-plane/pkg/contract/contract.pb.go
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/blang/semver/v4/LICENSE
  third_party/VENDOR-LICENSE/gopkg.in/evanphx/json-patch.v4/LICENSE
  vendor/github.com/blang/semver/.travis.yml
  vendor/github.com/blang/semver/README.md
  vendor/github.com/blang/semver/package.json
  vendor/github.com/blang/semver/v4/LICENSE
  vendor/github.com/blang/semver/v4/go.mod
  vendor/github.com/blang/semver/v4/json.go
  vendor/github.com/blang/semver/v4/range.go
  vendor/github.com/blang/semver/v4/semver.go
  vendor/github.com/blang/semver/v4/sort.go
  vendor/github.com/blang/semver/v4/sql.go
  vendor/gopkg.in/evanphx/json-patch.v4/.travis.yml
  vendor/gopkg.in/evanphx/json-patch.v4/LICENSE
  vendor/gopkg.in/evanphx/json-patch.v4/README.md
  vendor/gopkg.in/evanphx/json-patch.v4/errors.go
  vendor/gopkg.in/evanphx/json-patch.v4/merge.go
  vendor/gopkg.in/evanphx/json-patch.v4/patch.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/knative.dev/pkg/apis/duck/patch.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/signals/signal.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XXL

#354 use the new hack repo for scripts
  control-plane/pkg/contract/contract.pb.go
  go.mod
  go.sum
  hack/release.sh
  hack/tools.go
  hack/update-codegen.sh
  hack/update-deps.sh
  hack/verify-codegen.sh
  test/e2e-common.sh
  test/kafka/kafka_setup.sh
  test/presubmit-tests.sh
  vendor/github.com/hashicorp/go-retryablehttp/.travis.yml
  vendor/github.com/hashicorp/go-retryablehttp/client.go
  vendor/github.com/hashicorp/go-retryablehttp/roundtripper.go
  vendor/knative.dev/pkg/test/presubmit-tests.sh
  vendor/knative.dev/test-infra/LICENSE
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/dummy.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/performance-tests.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/knative.dev/test-infra/scripts/release.sh
  vendor/knative.dev/test-infra/scripts/shellcheck-presubmit.sh
  vendor/knative.dev/test-infra/scripts/update-test-infra.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#358 [release-0.18] Upgrade to latest dependencies
  control-plane/pkg/client/injection/reconciler/eventing/v1alpha1/kafkasink/reconciler.go
  control-plane/pkg/contract/contract.pb.go
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#361 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/verify.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/knative.dev/pkg/test/gcs/gcs.go
  vendor/knative.dev/pkg/test/ghutil/client.go
  vendor/knative.dev/pkg/test/mako/config/benchmark.go
  vendor/knative.dev/pkg/test/spoof/error_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/M

#362 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#365 Export data plane tests reports
  data-plane/docker/test/Dockerfile
  test/data-plane/library.sh
Labels: approved, cla: yes, lgtm, size/S

#366 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/reconciler/testing/reactions.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S
