Repository knative-extensions/eventing-kafka-broker, pull requests merged in 2020-07, with the labels that each got.

#20 Add maven wrapper
  DEVELOPMENT.md
  data-plane/.mvn/wrapper/MavenWrapperDownloader.java
  data-plane/.mvn/wrapper/maven-wrapper.jar
  data-plane/.mvn/wrapper/maven-wrapper.properties
  data-plane/docker/Dockerfile
  data-plane/docker/test/Dockerfile
  data-plane/mvnw
  data-plane/mvnw.cmd
  test/data-plane/library.sh
Labels: approved, cla: yes, lgtm, size/XL

#24 Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1beta1/broker/controller.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1beta1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1beta1/trigger/controller.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1beta1/trigger/reconciler.go
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#23 Keep protobuf generated code in repository
  DEVELOPMENT.md
  control-plane/pkg/core/config/triggers.pb.go
  data-plane/.gitignore
  data-plane/generated/src/main/java/dev/knative/eventing/kafka/broker/core/config/BrokersConfig.java
  go.mod
  hack/update-codegen.sh
  hack/verify-codegen.sh
  proto/def/triggers.proto
  proto/hack/generate_proto
  test/data-plane/library.sh
  test/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XXL

#25 Remove hardcoded GOPATH from developer docs.
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#27 Requirements versions in developer guide
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#28 Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/subscription_lifecycle.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#29 Update docs to include installation from scratch
  DEVELOPMENT.md
  test/kafka/kafka_setup.sh
Labels: approved, cla: yes, lgtm, size/M

#35 Use release 2.0.0-milestone1 of cloudevents/sdk-java
  data-plane/pom.xml
Labels: approved, cla: yes, lgtm, size/XS

#36 Use `knative-broker-` as topic prefix
  control-plane/pkg/reconciler/broker/broker.go
  control-plane/pkg/reconciler/broker/broker_test.go
  data-plane/README.md
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/CloudEventRequestToRecordMapper.java
Labels: approved, cla: yes, lgtm, size/S

#37 Receiver responds with 404 when it receives a request to a non-existing Broker.
  control-plane/pkg/core/config/triggers.pb.go
  control-plane/pkg/reconciler/broker/broker.go
  control-plane/pkg/reconciler/broker/broker_test.go
  data-plane/config/template/500-receiver.yaml
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/Broker.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/BrokerWrapper.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/file/FileWatcher.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/file/FileWatcherTest.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/Main.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactoryTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/UnorderedConsumerTest.java
  data-plane/generated/src/main/java/dev/knative/eventing/kafka/broker/core/config/BrokersConfig.java
  data-plane/receiver/pom.xml
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/Env.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/Main.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/RequestHandler.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/EnvTest.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/RequestHandlerTest.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/integration/ReceiverVerticleTest.java
  data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java
  proto/def/triggers.proto
Labels: approved, cla: yes, lgtm, size/XL

#38 Update receiver pods annotation to refresh mounted config map
  control-plane/pkg/reconciler/base/reconciler.go
  control-plane/pkg/reconciler/broker/broker.go
  control-plane/pkg/reconciler/broker/broker_lifecycle.go
  control-plane/pkg/reconciler/broker/broker_test.go
Labels: approved, cla: yes, lgtm, size/L

#40 Create dependabot.yml
  .github/dependabot.yml
Labels: approved, cla: yes, lgtm, size/S

#42 Add Trigger reconciler
  control-plane/cmd/kafka-broker-controller/main.go
  control-plane/pkg/log/logger.go
  control-plane/pkg/reconciler/broker/broker.go
  control-plane/pkg/reconciler/broker/broker_test.go
  control-plane/pkg/reconciler/testing/objects.go
  control-plane/pkg/reconciler/trigger/controller.go
  control-plane/pkg/reconciler/trigger/controller_test.go
  control-plane/pkg/reconciler/trigger/trigger.go
  control-plane/pkg/reconciler/trigger/trigger_lifecycle.go
  control-plane/pkg/reconciler/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#50 Add partition key value as Producer record key
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/cloudevents/PartitionKey.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/cloudevents/PartitionKeyTest.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpSinkResponseHandler.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpSinkResponseHandlerTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/UnorderedConsumerTest.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/CloudEventRequestToRecordMapper.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/integration/ReceiverVerticleTest.java
Labels: approved, cla: yes, lgtm, size/M

#52 Add Trigger finalizer
  control-plane/pkg/reconciler/trigger/trigger.go
  control-plane/pkg/reconciler/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/L

#53 Add JSON Structured Logging to data plane components
  data-plane/config/100-config-logging.yaml
  data-plane/config/template/500-dispatcher.yaml
  data-plane/config/template/500-receiver.yaml
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/ObjectsCreator.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/file/FileWatcher.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/BrokersManager.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerRecordHandler.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/Main.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/UnorderedConsumerRecordOffsetStrategy.java
  data-plane/pom.xml
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/Main.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/RequestHandler.java
Labels: approved, cla: yes, lgtm, size/L

#58 [master] Format markdown
  CONTRIBUTING.md
  DEVELOPMENT.md
  INTERNALS.md
  README.md
  data-plane/README.md
  proto/DEVELOPMENT.md
  test/README.md
Labels: approved, cla: yes, lgtm, size/L

#59 [master] golang format tools
  control-plane/pkg/reconciler/broker/controller.go
  hack/tools.go
Labels: approved, cla: yes, lgtm, size/XS

#60 Export logs from knative-eventing namespace
  go.mod
  go.sum
  test/e2e/conformance/main_test.go
  test/e2e/main_test.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/go.mod
  vendor/contrib.go.opencensus.io/exporter/ocagent/go.sum
  vendor/contrib.go.opencensus.io/exporter/ocagent/ocagent.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/options.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/transform_stats_to_metrics.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/errors.pb.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/errors.proto
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/stream_chunk.pb.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/stream_chunk.proto
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/context.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/errors.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/handler.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshal_httpbodyproto.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshaler.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/mux.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/proto_errors.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/query.go
  vendor/knative.dev/eventing/pkg/apis/eventing/register.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_conversion.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/broker.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_data_plane_helper.go
  vendor/knative.dev/eventing/test/lib/config.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/eventing/test/lib/dropevents/dropeventsfirst/sequence.go
  vendor/knative.dev/eventing/test/lib/logexporter.go
  vendor/knative.dev/eventing/test/lib/sender/resources.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/two_lane_queue.go
  vendor/knative.dev/pkg/hash/bucketer.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#61 Add data plane consumer conformance tests
  control-plane/pkg/reconciler/base/reconciler.go
  control-plane/pkg/reconciler/broker/broker.go
  control-plane/pkg/reconciler/broker/broker_lifecycle.go
  control-plane/pkg/reconciler/broker/broker_test.go
  control-plane/pkg/reconciler/trigger/trigger.go
  control-plane/pkg/reconciler/trigger/trigger_lifecycle.go
  control-plane/pkg/reconciler/trigger/trigger_test.go
  data-plane/config/100-config-kafka-broker-dispatcher.yaml
  data-plane/config/100-config-kafka-broker-receiver.yaml
  data-plane/config/template/500-dispatcher.yaml
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/BrokerWrapper.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/BrokerWrapperTest.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/TriggerWrapperTest.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerRecordHandler.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/Main.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/UnorderedConsumerRecordOffsetStrategy.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerRecordSender.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactory.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/BrokersManagerTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/UnorderedConsumerRecordOffsetStrategyTest.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/CloudEventRequestToRecordMapper.java
  go.mod
  test/e2e-tests.sh
  test/e2e/conformance/data_plane_conformance_test.go
Labels: approved, cla: yes, lgtm, size/XL

#63 Create a new ClusterAdmin at each loop
  control-plane/pkg/reconciler/broker/broker.go
  control-plane/pkg/reconciler/broker/broker_test.go
  control-plane/pkg/reconciler/broker/controller.go
  control-plane/pkg/reconciler/broker/controller_test.go
  control-plane/pkg/reconciler/broker/topic.go
  control-plane/pkg/reconciler/broker/topic_test.go
Labels: approved, cla: yes, lgtm, size/L

#64 Remove data plane config map from artifacts and create it if not found
  control-plane/config/200-controller-cluster-role.yaml
  control-plane/pkg/reconciler/base/reconciler.go
  control-plane/pkg/reconciler/broker/broker.go
  control-plane/pkg/reconciler/broker/broker_test.go
  control-plane/pkg/reconciler/broker/controller.go
  control-plane/pkg/reconciler/testing/factory.go
  control-plane/pkg/reconciler/trigger/trigger.go
  control-plane/pkg/reconciler/trigger/trigger_test.go
  data-plane/config/100-config-brokers-triggers.yaml
Labels: approved, cla: yes, lgtm, size/L

#65 Rename broker repeated field from broker to brokers.
  control-plane/pkg/core/config/triggers.pb.go
  control-plane/pkg/log/log_marshaller.go
  control-plane/pkg/reconciler/broker/broker.go
  control-plane/pkg/reconciler/broker/broker_test.go
  control-plane/pkg/reconciler/trigger/trigger.go
  control-plane/pkg/reconciler/trigger/trigger_test.go
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/ObjectsCreator.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/file/FileWatcherTest.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/testing/utils/CoreObjects.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/UnorderedConsumerTest.java
  data-plane/generated/src/main/java/dev/knative/eventing/kafka/broker/core/config/BrokersConfig.java
  proto/def/triggers.proto
Labels: approved, cla: yes, lgtm, size/L

#66 [master] golang format tools
  control-plane/pkg/reconciler/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/XS

#70 Bind addressable-resolver cluster role to kafka-broker-controller SA
  control-plane/config/201-controller-cluster-role-binding.yaml
Labels: approved, cla: yes, lgtm, size/S
