Repository knative-extensions/eventing-kafka-broker, pull requests merged in 2020-12, with the labels that each got.

#444 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/mako/sidecar.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#445 Use PartitionKeyInterceptor from the sdk
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/cloudevents/PartitionKey.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/cloudevents/PartitionKeyTest.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactory.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpSinkResponseHandler.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactoryTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/UnorderedConsumerTest.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/CloudEventRequestToRecordMapper.java
Labels: approved, cla: yes, lgtm, size/L

#438 Non-blocking data plane components
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerVerticle.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/Main.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactory.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerVerticleTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactoryTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/ConsumerVerticleFactoryMock.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/UnorderedConsumerTest.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/Main.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/ReceiverVerticle.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/ReceiverVerticleTest.java
  data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java
Labels: approved, cla: yes, kind/enhancement, lgtm, size/L

#449 update k8s deps which include leader election fixes
  go.mod
  go.sum
  hack/k8s-client-go.patch
  hack/update-deps.sh
  hack/update-k8s-deps.sh
  third_party/VENDOR-LICENSE/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/.travis.yml
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/endpointslock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go
  vendor/k8s.io/client-go/transport/cache.go
  vendor/modules.txt
Labels: approved, cla: yes, kind/bug, lgtm, size/L

#450 Automatically add area label to PRs
  .github/workflows/OWNERS
  control-plane/OWNERS
  data-plane/OWNERS
  test/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#448 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/knative.dev/pkg/network/handlers/error.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#454 Integrate the gopath hacks
  hack/update-codegen.sh
Labels: approved, cla: yes, lgtm, size/S

#456 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/blendle/zapdriver/LICENSE
  vendor/github.com/blendle/zapdriver/.gitignore
  vendor/github.com/blendle/zapdriver/LICENSE
  vendor/github.com/blendle/zapdriver/README.md
  vendor/github.com/blendle/zapdriver/config.go
  vendor/github.com/blendle/zapdriver/core.go
  vendor/github.com/blendle/zapdriver/encoder.go
  vendor/github.com/blendle/zapdriver/go.mod
  vendor/github.com/blendle/zapdriver/go.sum
  vendor/github.com/blendle/zapdriver/http.go
  vendor/github.com/blendle/zapdriver/label.go
  vendor/github.com/blendle/zapdriver/logger.go
  vendor/github.com/blendle/zapdriver/operation.go
  vendor/github.com/blendle/zapdriver/report.go
  vendor/github.com/blendle/zapdriver/service.go
  vendor/github.com/blendle/zapdriver/source.go
  vendor/github.com/blendle/zapdriver/trace.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#461 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#463 Use DefaultBackoff for resources updated by more controllers
  control-plane/pkg/reconciler/base/reconciler.go
  control-plane/pkg/reconciler/broker/broker.go
  control-plane/pkg/reconciler/sink/kafka_sink.go
  control-plane/pkg/reconciler/trigger/trigger.go
Labels: approved, area/control-plane, cla: yes, lgtm, size/S

#464 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/lib/duck/resource_getters.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#455 Add data plane profiling action
  .github/workflows/knative-profile-data-plane.yaml
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/tracing/TracingSpan.java
  data-plane/pom.xml
  data-plane/profiler/resources/config-kafka-broker-consumer.properties
  data-plane/profiler/resources/config-kafka-broker-httpserver.properties
  data-plane/profiler/resources/config-kafka-broker-producer.properties
  data-plane/profiler/resources/config-kafka-broker-webclient.properties
  data-plane/profiler/resources/config-logging.xml
  data-plane/profiler/resources/config-sacura-warmup.yaml
  data-plane/profiler/resources/config-sacura.yaml
  data-plane/profiler/resources/ingress.json
  data-plane/profiler/run.sh
Labels: approved, area/data-plane, area/test, cla: yes, lgtm, size/L

#467 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/helper.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#469 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, area/test, cla: yes, lgtm, size/S

#470 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#471 Replace HttpTraceContext with W3CTraceContextPropagator
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/tracing/OpenTelemetryTracer.java
Labels: approved, area/data-plane, cla: yes, kind/removal, lgtm, size/XS

#473 Change auto topic create to be false
  test/kafka/kafka-ephemeral-single.yaml
Labels: approved, area/test, cla: yes, lgtm, size/XS

#420 Add Global resync handlers
  control-plane/pkg/reconciler/broker/controller.go
  control-plane/pkg/reconciler/sink/controller.go
  control-plane/pkg/reconciler/trigger/controller.go
  control-plane/pkg/reconciler/trigger/controller_test.go
  test/e2e-tests.sh
  test/e2e/broker_trigger_sink_test.go
  test/e2e/delete_cm_test.go
  test/e2e/kafka_sink_test.go
  test/e2e/main_test.go
  test/pkg/sink/verify.go
Labels: approved, area/control-plane, area/test, cla: yes, kind/bug, lgtm, size/L

#480 Change release labels to kafka.eventing.knative.dev
  control-plane/config/100-config-tracing.yaml
  control-plane/config/100-kafka-broker-configmap.yaml
  control-plane/config/200-controller-cluster-role.yaml
  control-plane/config/200-controller-service-account.yaml
  control-plane/config/201-controller-cluster-role-binding.yaml
  control-plane/config/500-controller.yaml
  control-plane/config/sink/100-kafka-sink.yaml
  control-plane/config/sink/100-webhook-cluster-role.yaml
  control-plane/config/sink/100-webhook-service-account.yaml
  control-plane/config/sink/200-addressable-resolver-cluster-role.yaml
  control-plane/config/sink/200-webhook-cluster-role-binding.yaml
  control-plane/config/sink/400-webhook-defaulting.yaml
  control-plane/config/sink/400-webhook-secret.yaml
  control-plane/config/sink/400-webhook-validation.yaml
  control-plane/config/sink/500-webhook.yaml
  data-plane/config/100-config-kafka-broker-data-plane.yaml
  data-plane/config/100-config-logging.yaml
  data-plane/config/sink/100-config-kafka-sink-data-plane.yaml
  data-plane/config/sink/template/500-receiver.yaml
  data-plane/config/template/500-dispatcher.yaml
  data-plane/config/template/500-receiver.yaml
  hack/label.sh
  test/config/100-config-logging.yaml
  test/config/chaos/chaosduck.yaml
  test/config/cm-watcher.yaml
  test/config/config-br-defaults.yaml
Labels: approved, area/control-plane, area/data-plane, area/test, cla: yes, kind/cleanup, lgtm, size/L

#483 Set anti-affinity for receiver deployment
  data-plane/config/sink/template/500-receiver.yaml
  data-plane/config/template/500-receiver.yaml
Labels: approved, area/data-plane, cla: yes, kind/enhancement, lgtm, size/S

#478 Thread.sleep changed for Awaitility.await #351
  data-plane/THIRD-PARTY.txt
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/file/FileWatcherTest.java
  data-plane/dispatcher/pom.xml
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/UnorderedConsumerTest.java
  data-plane/pom.xml
  data-plane/tests/pom.xml
  data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java
Labels: approved, area/data-plane, cla: yes, lgtm, ok-to-test, size/M

#487 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, area/test, cla: yes, lgtm, size/M

#491 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#492 Avoid logging the entire resource
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerDeployerVerticle.java
Labels: approved, area/data-plane, cla: yes, lgtm, size/S

#494 Fix flaky consumer test
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/UnorderedConsumerTest.java
Labels: approved, area/data-plane, cla: yes, lgtm, size/M

#495 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/tsenart/vegeta/LICENSE
  vendor/github.com/tsenart/vegeta/lib/attack.go
  vendor/github.com/tsenart/vegeta/lib/histogram.go
  vendor/github.com/tsenart/vegeta/lib/metrics.go
  vendor/github.com/tsenart/vegeta/lib/pacer.go
  vendor/github.com/tsenart/vegeta/lib/reporters.go
  vendor/github.com/tsenart/vegeta/lib/results.go
  vendor/github.com/tsenart/vegeta/lib/results_easyjson.go
  vendor/github.com/tsenart/vegeta/lib/target.schema.json
  vendor/github.com/tsenart/vegeta/lib/targets.go
  vendor/github.com/tsenart/vegeta/lib/targets_easyjson.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/channel_template_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/channel.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/inmemorychannel.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_dls_test_helper.go
  vendor/knative.dev/eventing/test/performance/infra/sender/http_load_generator.go
  vendor/knative.dev/pkg/test/mako/config/slack.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#493 Remove replicas from our Deployments
  control-plane/config/500-controller.yaml
  control-plane/config/sink/500-webhook.yaml
  data-plane/config/sink/template/500-receiver.yaml
  data-plane/config/template/500-dispatcher.yaml
  data-plane/config/template/500-receiver.yaml
Labels: approved, area/control-plane, area/data-plane, cla: yes, lgtm, size/XS

#498 Fix imports in release script
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#500 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#505 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/informer/informed_watcher.go
  vendor/knative.dev/pkg/configmap/manual_watcher.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/tracing/setup.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#504 [Automated] Update actions
  .github/workflows/knative-verify.yaml
Labels: approved, area/test, cla: yes, lgtm, size/XS

#507 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/e2e/helpers/channel_single_event_helper.go
  vendor/knative.dev/pkg/tracing/nostackdriver.go
  vendor/knative.dev/pkg/tracing/opencensus.go
  vendor/knative.dev/pkg/tracing/stackdriver.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#512 [data-plane]: Bump opentelemetry-bom in /data-plane
  data-plane/THIRD-PARTY.txt
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/tracing/Tracing.java
  data-plane/pom.xml
Labels: approved, area/data-plane, cla: yes, lgtm, size/M

#511 Skip ConfigMap update when there are no changes
  control-plane/pkg/core/config/egress.go
  control-plane/pkg/core/config/egress_test.go
  control-plane/pkg/core/config/resource.go
  control-plane/pkg/core/config/resource_test.go
  control-plane/pkg/reconciler/broker/broker.go
  control-plane/pkg/reconciler/broker/broker_test.go
  control-plane/pkg/reconciler/sink/kafka_sink.go
  control-plane/pkg/reconciler/sink/kafka_sink_test.go
  control-plane/pkg/reconciler/trigger/trigger.go
  control-plane/pkg/reconciler/trigger/trigger_test.go
Labels: approved, area/control-plane, cla: yes, kind/cleanup, lgtm, size/XL

#514 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, area/test, cla: yes, lgtm, size/XS
