Repository knative-extensions/eventing-kafka-broker, pull requests merged in 2020-11, with the labels that each got.

#370 Test against Kafka 2.6
  test/kafka/kafka-ephemeral-single.yaml
Labels: approved, cla: yes, lgtm, size/XS

#334 Gracefully clean up resources on shutdown
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/file/FileWatcher.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/utils/Shutdown.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/utils/ShutdownTest.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/Main.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/Main.java
Labels: approved, cla: yes, lgtm, size/L

#369 Custom Broker config for sacura job
  test/pkg/config/sacura/101-broker.yaml
Labels: approved, area/test, cla: yes, lgtm, size/S

#375 Change default replication factor
  control-plane/config/100-kafka-broker-configmap.yaml
  test/e2e/broker_trigger_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#378 Fix thread blocked issue
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/ResourcesReconcilerMessageHandler.java
Labels: approved, cla: yes, lgtm, size/XS

#382 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/L

#383 No need for the release-notes script anymore
  hack/release-notes.sh
Labels: approved, cla: yes, lgtm, size/S

#385 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/S

#376 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/performance-tests.sh
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#386 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#387 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/http_client.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#367 Release eventing-kafka.yaml with all components in it
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#392 Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#395 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#390 Create one producer per properties in receiver
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/RequestMapper.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/RequestMapperTest.java
Labels: approved, cla: yes, lgtm, size/L

#399 Remove duplicated workflow
  .github/workflows/knative-test.yaml
Labels: approved, cla: yes, lgtm, size/M

#402 Sync PR template from Eventing
  .github/pull-request-template.md
Labels: approved, cla: yes, lgtm, size/S

#364 Test on KinD
  .github/workflows/kind-e2e.yaml
  .wokeignore
  hack/update-strimzi.sh
  test/e2e-common.sh
  test/e2e-tests.sh
  test/kafka/kafka_setup.sh
  test/kafka/strimzi-cluster-operator.yaml
  test/pkg/kafka/verify_messages_topic.go
  test/pkg/kafka/verify_num_partitions_replication.go
Labels: approved, cla: yes, lgtm, size/XXL

#404 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_redelivery_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_chain_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_defaulter_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_dls_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_event_tranformation_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_single_event_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/parallel_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/sequence_test_helper.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info_matchers.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info_store.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_log.go
  vendor/knative.dev/eventing/test/lib/recordevents/receiver/receiver.go
  vendor/knative.dev/eventing/test/lib/recordevents/receiver/reply.go
  vendor/knative.dev/eventing/test/lib/recordevents/recorder_vent/constructor.go
  vendor/knative.dev/eventing/test/lib/recordevents/recorder_vent/recorder.go
  vendor/knative.dev/eventing/test/lib/recordevents/resources.go
  vendor/knative.dev/eventing/test/lib/recordevents/sender/sender.go
  vendor/knative.dev/eventing/test/lib/sender/resources.go
  vendor/knative.dev/eventing/test/test_images/recordevents/main.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/reconciler/testing/tracker.go
  vendor/knative.dev/pkg/test/logging/.gitattributes
  vendor/knative.dev/pkg/test/logging/doc.go
  vendor/knative.dev/pkg/test/logging/error.go
  vendor/knative.dev/pkg/test/logging/logger.go
  vendor/knative.dev/pkg/test/logging/memory_encoder.go
  vendor/knative.dev/pkg/test/logging/spew_encoder.go
  vendor/knative.dev/pkg/test/logging/sugar.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/logging/zapr.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/tracker/interface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#407 [Automated] Fix misspellings
  test/kafka/strimzi-cluster-operator.yaml
Labels: approved, cla: yes, lgtm, size/XS

#408 Check Sacura Job status in a Go test
  test/e2e-tests.sh
  test/e2e/sacura_test.go
Labels: approved, cla: yes, lgtm, size/L

#409 Retry executing DP builds to avoid conn reset errors
  test/data-plane/library.sh
Labels: approved, cla: yes, lgtm, size/S

#411 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#413 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/network/network.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#414 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/doc.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/register.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/clientset_generated.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta2/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta2/fake/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta2/fake/fake_pingsource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta2/fake/fake_sources_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta2/generated_expansion.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta2/pingsource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta2/sources_client.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/generic.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/sources/interface.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/sources/v1beta2/interface.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/sources/v1beta2/pingsource.go
  vendor/knative.dev/eventing/pkg/client/listers/sources/v1beta2/expansion_generated.go
  vendor/knative.dev/eventing/pkg/client/listers/sources/v1beta2/pingsource.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/listers.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/pingsource.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1beta1/pingsource.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/pkg/hack/update-k8s-deps.sh
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/network.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#415 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#417 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#419 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#418 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#422 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/webhook/env.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#424 Use webhook name from common pkg
  control-plane/cmd/webhook-kafka/main.go
  vendor/knative.dev/eventing/pkg/logconfig/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#425 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#429 Add tests for Configurations.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/utils/Configurations.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/utils/ConfigurationsTest.java
  data-plane/core/src/test/resources/configurations.properties
Labels: approved, cla: yes, lgtm, size/M

#431 [master] Upgrade to latest dependencies
  control-plane/pkg/client/injection/client/client.go
  go.mod
  go.sum
  vendor/knative.dev/pkg/client/injection/apiextensions/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/request.go
  vendor/knative.dev/pkg/test/spoof/response_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#433 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/client/injection/client/client.go
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#434 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_conversion.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#427 Update to sdk-java RC1
  data-plane/THIRD-PARTY.txt
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/filter/impl/AttributesFilter.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/filter/impl/AttributesFilterTest.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpSinkResponseHandler.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/IllegalResponseException.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/UnorderedConsumerTest.java
  data-plane/pom.xml
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/RequestMapperTest.java
  data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java
Labels: approved, cla: yes, lgtm, size/L
