Repository knative-extensions/eventing-kafka-broker, pull requests merged in 2020-09, with the labels that each got.

#137 Port to Vert.x 4 and sdk-java 2.0.0-milestone2
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/EventMatcherTest.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/BrokersManager.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerRecordHandler.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerRecordOffsetStrategyFactory.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerVerticle.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/Main.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/SinkResponseHandler.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerRecordSender.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactory.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpSinkResponseHandler.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/BrokersManagerTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerRecordHandlerTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerVerticleTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactoryTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpSinkResponseHandlerTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/ConsumerVerticleFactoryMock.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/UnorderedConsumerTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategyTest.java
  data-plane/pom.xml
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/CloudEventRequestToRecordMapper.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/HttpVerticle.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/Main.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/integration/ProbeHandlerTest.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/integration/ReceiverVerticleTest.java
  data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java
Labels: approved, cla: yes, lgtm, size/XL

#147 Removed checkstyle and replaced with editorconfig
  data-plane/.editorconfig
  data-plane/README.md
  data-plane/checkstyle/suppression.xml
  data-plane/core/pom.xml
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/BrokerWrapper.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/EventMatcher.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/ObjectsCreator.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/TriggerWrapper.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/file/FileWatcher.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/BrokerWrapperTest.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/EventMatcherTest.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/ObjectsCreatorTest.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/TriggerWrapperTest.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/cloudevents/PartitionKeyTest.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/file/FileWatcherTest.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/testing/utils/CoreObjects.java
  data-plane/dispatcher/pom.xml
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/BrokersManager.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerRecordHandler.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerVerticle.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/Main.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerRecordSender.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactory.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpSinkResponseHandler.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/BrokersManagerTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerRecordHandlerTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerVerticleTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactoryTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpSinkResponseHandlerTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/ConsumerVerticleFactoryMock.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/UnorderedConsumerTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategyTest.java
  data-plane/docker/Dockerfile
  data-plane/generated/pom.xml
  data-plane/pom.xml
  data-plane/receiver/pom.xml
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/CloudEventRequestToRecordMapper.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/Env.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/HttpVerticle.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/Main.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/RequestHandler.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/RequestToRecordMapper.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/SimpleProbeHandlerDecorator.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/EnvTest.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/RequestHandlerTest.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/integration/ProbeHandlerTest.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/integration/ReceiverVerticleTest.java
  data-plane/tests/pom.xml
  data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java
  proto/hack/generate_proto
Labels: approved, cla: yes, lgtm, size/XXL

#149 Get WebClient config from config map
  data-plane/config/100-config-kafka-broker-data-plane.yaml
  data-plane/config/template/500-dispatcher.yaml
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/Configurations.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/Main.java
Labels: approved, cla: yes, lgtm, size/L

#152 [master] Format markdown
  data-plane/README.md
Labels: approved, cla: yes, lgtm, size/M

#151 Configure Vert.x HTTP server through a config map
  data-plane/config/100-config-kafka-broker-data-plane.yaml
  data-plane/config/template/500-dispatcher.yaml
  data-plane/config/template/500-receiver.yaml
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/utils/BaseEnv.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/utils/Configurations.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/Configurations.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/DispatcherEnv.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/Main.java
  data-plane/pom.xml
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/Main.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/ReceiverEnv.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/ReceiverEnvTest.java
Labels: approved, cla: yes, lgtm, size/L

#153 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#155 Disable SELinux when using protobuf compiler
  proto/hack/generate_proto
Labels: approved, cla: yes, lgtm, size/XS

#157 Update Broker and Trigger status when there is a failure
  control-plane/pkg/reconciler/broker/broker.go
  control-plane/pkg/reconciler/trigger/trigger.go
Labels: approved, cla: yes, lgtm, size/XS

#156 Add linting config and fix issues.
  .golangci.yaml
  control-plane/pkg/reconciler/broker/broker_test.go
Labels: approved, cla: yes, lgtm, size/S

#159 Reorganized data-plane poms
  data-plane/contract/pom.xml
  data-plane/contract/src/main/java/dev/knative/eventing/kafka/broker/core/config/BrokersConfig.java
  data-plane/core/pom.xml
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/EventMatcherTest.java
  data-plane/dispatcher/pom.xml
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/ConsumerVerticleFactoryMock.java
  data-plane/docker/Dockerfile
  data-plane/pom.xml
  data-plane/receiver/pom.xml
  data-plane/tests/pom.xml
  hack/verify-codegen.sh
  proto/hack/generate_proto
Labels: approved, cla: yes, lgtm, size/XL

#163 Check if data plane pods are running
  control-plane/pkg/reconciler/base/receiver_condition_set.go
  control-plane/pkg/reconciler/base/reconciler.go
  control-plane/pkg/reconciler/broker/broker.go
  control-plane/pkg/reconciler/broker/broker_test.go
  control-plane/pkg/reconciler/sink/kafka_sink.go
  control-plane/pkg/reconciler/sink/kafka_sink_test.go
  control-plane/pkg/reconciler/testing/objects_broker.go
  control-plane/pkg/reconciler/testing/objects_sink.go
Labels: approved, cla: yes, lgtm, size/L

#165 Enable TestBrokerConsumer
  test/e2e/conformance/data_plane_conformance_test.go
Labels: approved, cla: yes, lgtm, size/L

#166 Add Webhook RBAC configuration
  control-plane/config/sink/100-webhook-cluster-role.yaml
  control-plane/config/sink/100-webhook-service-account.yaml
  control-plane/config/sink/200-webhook-cluster-role-binding.yaml
  control-plane/config/sink/500-webhook.yaml
Labels: approved, cla: yes, lgtm, size/L

#175 Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#176 Allow independent installation of components
  .gitignore
  control-plane/cmd/kafka-controller/main.go
  control-plane/config/200-controller-cluster-role.yaml
  control-plane/config/200-controller-service-account.yaml
  control-plane/config/201-controller-cluster-role-binding.yaml
  control-plane/config/500-controller.yaml
  data-plane/config/100-config-logging.yaml
  data-plane/config/sink/template/500-receiver.yaml
  data-plane/config/template/500-dispatcher.yaml
  data-plane/config/template/500-receiver.yaml
  hack/release.sh
  test/control-plane/library.sh
  test/e2e-common.sh
Labels: approved, cla: yes, lgtm, size/M

#180 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#181 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
Labels: approved, cla: yes, lgtm, size/XS

#178 Add E2E test using Broker, Trigger, and KafkaSink
  go.mod
  test/e2e/broker_trigger_sink_test.go
  test/e2e/kafka_sink_test.go
  test/pkg/addressable/send.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#183 Use WaitForPodRunning instead of WaitForResourceReady
  test/e2e/conformance/data_plane_conformance_test.go
Labels: approved, cla: yes, lgtm, size/M

#177 Add Kafka sink finalizer
  control-plane/pkg/apis/eventing/v1alpha1/kafka_sink_lifecycle.go
  control-plane/pkg/core/config/egress_test.go
  control-plane/pkg/core/config/resource.go
  control-plane/pkg/core/config/resource_test.go
  control-plane/pkg/core/config/utils.go
  control-plane/pkg/core/config/utils_test.go
  control-plane/pkg/reconciler/base/receiver_condition_set.go
  control-plane/pkg/reconciler/base/reconciler.go
  control-plane/pkg/reconciler/broker/broker.go
  control-plane/pkg/reconciler/broker/broker_test.go
  control-plane/pkg/reconciler/kafka/testing/admin_mock.go
  control-plane/pkg/reconciler/kafka/topic.go
  control-plane/pkg/reconciler/kafka/topic_test.go
  control-plane/pkg/reconciler/sink/controller.go
  control-plane/pkg/reconciler/sink/kafka_sink.go
  control-plane/pkg/reconciler/sink/kafka_sink_test.go
  control-plane/pkg/reconciler/testing/objects_sink.go
  control-plane/pkg/reconciler/trigger/trigger.go
  control-plane/pkg/reconciler/trigger/trigger_test.go
  test/pkg/observability/watch_config_map.go
Labels: approved, cla: yes, lgtm, size/XL

#185 Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/conformance/helpers/broker_control_plane_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_data_plane_test_helper.go
  vendor/knative.dev/pkg/test/ingress/ingress.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#191 Project pod name as env var in our deployments
  control-plane/config/500-controller.yaml
  control-plane/config/sink/500-webhook.yaml
Labels: approved, cla: yes, lgtm, size/XS

#187 enable code coverage
  .codecov.yaml
  .github/workflows/knative-go-test.yaml
Labels: approved, cla: yes, lgtm, size/S

#195 Checking if the fancy codecov works with java too
  .codecov.yaml
  .github/workflows/knative-test.yaml
Labels: approved, cla: yes, lgtm, size/S

#196 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#193 Register admission webhooks
  control-plane/cmd/webhook-kafka/main.go
  control-plane/config/sink/400-webhook-defaulting.yaml
  control-plane/config/sink/400-webhook-secret.yaml
  control-plane/config/sink/400-webhook-validation.yaml
  control-plane/pkg/apis/eventing/v1alpha1/kafka_sink_validation.go
  control-plane/pkg/apis/eventing/v1alpha1/kafka_sink_validation_test.go
  test/e2e-common.sh
  test/pkg/testing/run.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1beta1/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/factory.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/generic.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1/expansion_generated.go
  vendor/knative.dev/pkg/client/injection/apiextensions/client/client.go
  vendor/knative.dev/pkg/client/injection/apiextensions/informers/apiextensions/v1/customresourcedefinition/customresourcedefinition.go
  vendor/knative.dev/pkg/client/injection/apiextensions/informers/factory/factory.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/conversion.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/reconciler.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#197 Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#207 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/listers.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#204 Add pierDipi to approvers
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#208 [Release] Pin upstreams for release 0.18
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/webhook/conversion.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#210 Log error on malformed event in response
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpSinkResponseHandler.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/IllegalResponseException.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpSinkResponseHandlerTest.java
Labels: approved, cla: yes, lgtm, size/M

#212 Don't reconcile Triggers we don't own
  control-plane/pkg/reconciler/testing/objects_broker.go
  control-plane/pkg/reconciler/trigger/trigger.go
  control-plane/pkg/reconciler/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/M

#213 Upload Codecov Java report
  .github/workflows/knative-java-test.yaml
Labels: approved, cla: yes, lgtm, size/M

#214 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/duck/v1/fuzzer.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/subscribable_types_conversion.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/subscribable_types_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/container_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/container_validation.go
  vendor/knative.dev/eventing/pkg/tracing/setup.go
  vendor/knative.dev/eventing/test/lib/duck/resource_checks.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#215 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#216 [Automated] Update actions
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/XS

#217 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#221 [Automated] Fix misspellings
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/ObjectsCreator.java
Labels: approved, cla: yes, lgtm, size/XS

#222 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_redelivery_helper.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#225 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#224 [Automated] Update actions
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/M

#220 Enable linters and fix linting errors
  .golangci.yaml
  control-plane/cmd/webhook-kafka/main.go
  control-plane/pkg/apis/eventing/v1alpha1/kafka_sink_validation.go
  control-plane/pkg/apis/eventing/v1alpha1/register.go
  control-plane/pkg/core/config/utils.go
  control-plane/pkg/reconciler/broker/broker.go
  control-plane/pkg/reconciler/kafka/broker_class.go
  control-plane/pkg/reconciler/testing/objects_broker.go
  control-plane/pkg/reconciler/trigger/trigger.go
  test/pkg/testing/run.go
Labels: approved, cla: yes, lgtm, size/M

#226 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#229 Use registry URL to reference container images
  proto/hack/generate_proto
  test/data-plane/library.sh
Labels: approved, cla: yes, lgtm, size/XS

#230 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#235 [release-0.18] Remove strict flag
  test/e2e-common.sh
Labels: approved, cla: yes, lgtm, size/XS

#234 Remove strict flag
  test/e2e-common.sh
Labels: approved, cla: yes, lgtm, size/XS

#232 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#233 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#231 Expose Vertx core metrics in Prometheus format
  DEVELOPMENT.md
  INTERNALS.md
  data-plane/config/sink/template/500-receiver.yaml
  data-plane/config/template/500-dispatcher.yaml
  data-plane/config/template/500-receiver.yaml
  data-plane/core/pom.xml
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/metrics/MetricsOptionsProvider.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/utils/BaseEnv.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/metrics/MetricsOptionsProviderTest.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/utils/BaseEnvTest.java
  data-plane/dispatcher/pom.xml
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/Main.java
  data-plane/pom.xml
  data-plane/receiver/pom.xml
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/Main.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/ReceiverEnvTest.java
Labels: approved, cla: yes, lgtm, size/L

#238 Fix Sink not released
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#239 Use dependencies at HEAD
  control-plane/pkg/client/injection/reconciler/eventing/v1alpha1/kafkasink/controller.go
  control-plane/pkg/client/injection/reconciler/eventing/v1alpha1/kafkasink/reconciler.go
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/duck.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fakeclient.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fakeduck.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fakefactory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fakeinformer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/logging/logkey/constants.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/metrics.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/metrics/workqueue.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/knative.dev/pkg/reconciler/testing/hooks.go
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/knative.dev/pkg/reconciler/testing/util.go
  vendor/knative.dev/pkg/test/logging/spew_encoder.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/knative.dev/pkg/webhook/certificates/certificates.go
  vendor/knative.dev/pkg/webhook/conversion.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L
