Repository knative-extensions/eventing-kafka-broker, pull requests merged in 2020-06, with the labels that each got.

#4 Add test directory to make Prow happy
  test/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/M

#2 Added myself as owner and pierDipi as reviewer
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#3 Add `knative/eventing` issue and PR templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/issue-template.md
  .github/pull-request-template.md
Labels: approved, cla: yes, lgtm, size/M

#1 Add code of conduct
  CODE-OF-CONDUCT.md
Labels: approved, cla: yes, lgtm, size/M

#11 Add documentation: internals, contributing, development
  CONTRIBUTING.md
  DEVELOPMENT.md
  INTERNALS.md
  data-plane/README.md
  test/README.md
Labels: approved, cla: yes, lgtm, size/L

#15 Document protobuf code generation
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/XS

#14 Improve testing pipeline
  data-plane/docker/Dockerfile
  data-plane/docker/dispatcher/Dockerfile
  test/data-plane/library.sh
Labels: approved, cla: yes, lgtm, size/M

#16 updated .gitignore
  .gitignore
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#18 Add data plane integration test
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactory.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactoryTest.java
  data-plane/docker/Dockerfile
  data-plane/pom.xml
  data-plane/tests/pom.xml
  data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java
Labels: approved, cla: yes, lgtm, size/L
