Repository knative-extensions/eventing-kafka-broker, pull requests merged in 2021-06, with the labels that each got.

#949 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#946 Update protobuf
  control-plane/pkg/contract/contract.pb.go
  data-plane/THIRD-PARTY.txt
  data-plane/pom.xml
Labels: approved, area/control-plane, area/data-plane, cla: yes, lgtm, size/XS

#951 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/rekt/resources/trigger/trigger.go
  vendor/knative.dev/eventing/test/rekt/resources/trigger/trigger.yaml
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#950 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, area/test, cla: yes, lgtm, size/XS

#952 Cleanup some of e2e_new test code
  go.mod
  go.sum
  test/e2e_new/broker/broker.go
  test/e2e_new/ordered_test.go
  test/e2e_new/trigger/trigger.go
  test/e2e_new/trigger/trigger.yaml
  test/e2e_new/trigger_finalizer_test.go
  vendor/knative.dev/eventing/test/rekt/resources/addressable/addressable.go
  vendor/knative.dev/eventing/test/rekt/resources/broker/broker.go
  vendor/knative.dev/eventing/test/rekt/resources/broker/broker.yaml
  vendor/knative.dev/eventing/test/rekt/resources/svc/service.go
  vendor/knative.dev/eventing/test/rekt/resources/svc/service.yaml
  vendor/knative.dev/pkg/webhook/certificates/resources/certs.go
  vendor/modules.txt
Labels: approved, area/test, cla: yes, lgtm, size/XL

#953 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#958 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#960 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#954 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/S

#900 Vertx 4.1 & Tracing rework
  data-plane/THIRD-PARTY.txt
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/metrics/Metrics.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/tracing/HeadersPropagatorGetter.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/tracing/HeadersPropagatorSetter.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/tracing/OpenTelemetryTracer.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/tracing/OpenTelemetryVertxTracingFactory.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/tracing/Tracing.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/tracing/TracingConfig.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/tracing/TracingSpan.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/tracing/HeadersPropagatorGetterTest.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/tracing/HeadersPropagatorSetterTest.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/tracing/OpenTelemetryVertxTracingFactoryTest.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/tracing/TracingConfigTest.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/tracing/TracingSpanTest.java
  data-plane/dispatcher/pom.xml
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/Main.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/RecordDispatcher.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerRecordSender.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactory.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpSinkResponseHandler.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/RecordDispatcherTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/AbstractConsumerVerticleTest.java
  data-plane/pom.xml
  data-plane/receiver/pom.xml
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/CloudEventRequestToRecordMapper.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/Main.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/ReceiverTracingVerticleTest.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/ReceiverVerticleTest.java
  data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java
  test/e2e_new/ordered_test.go
  test/e2e_new/tracing_test.go
  test/e2e_new/trigger_finalizer_test.go
Labels: approved, area/data-plane, area/test, cla: yes, lgtm, size/XXL

#964 More comments about how tracing works for the consumer
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/RecordDispatcher.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactory.java
Labels: approved, area/data-plane, cla: yes, lgtm, size/XS

#955 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/evanphx/json-patch/v5/LICENSE
  vendor/github.com/evanphx/json-patch/v5/LICENSE
  vendor/github.com/evanphx/json-patch/v5/errors.go
  vendor/github.com/evanphx/json-patch/v5/go.mod
  vendor/github.com/evanphx/json-patch/v5/go.sum
  vendor/github.com/evanphx/json-patch/v5/merge.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/go.uber.org/zap/.travis.yml
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/CONTRIBUTING.md
  vendor/go.uber.org/zap/FAQ.md
  vendor/go.uber.org/zap/Makefile
  vendor/go.uber.org/zap/README.md
  vendor/go.uber.org/zap/field.go
  vendor/go.uber.org/zap/go.mod
  vendor/go.uber.org/zap/go.sum
  vendor/go.uber.org/zap/http_handler.go
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/sugar.go
  vendor/go.uber.org/zap/zapcore/console_encoder.go
  vendor/go.uber.org/zap/zapcore/error.go
  vendor/go.uber.org/zap/zapcore/field.go
  vendor/go.uber.org/zap/zapcore/write_syncer.go
  vendor/gopkg.in/evanphx/json-patch.v4/.travis.yml
  vendor/gopkg.in/evanphx/json-patch.v4/README.md
  vendor/knative.dev/eventing/test/rekt/resources/broker/broker.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/duck/patch.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/prober.go
  vendor/knative.dev/reconciler-test/pkg/manifest/templates.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#963 Cleanup the `Tracing` class and move setup as instance method of `TracingConfig`
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/tracing/Tracing.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/tracing/TracingConfig.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/tracing/TracingConfigTest.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/tracing/TracingTest.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/Main.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/CloudEventRequestToRecordMapper.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/Main.java
Labels: approved, area/data-plane, cla: yes, lgtm, size/L

#969 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#967 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#968 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-vulnerability.yaml
Labels: approved, area/test, cla: yes, lgtm, size/M

#972 Removed bad log line
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/tracing/TracingConfig.java
Labels: approved, area/data-plane, cla: yes, lgtm, size/XS

#970 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/reconciler/testing/listers.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/scheme/scheme.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/factory.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/listers.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_single_event_helper.go
  vendor/knative.dev/eventing/test/rekt/resources/broker/broker.go
  vendor/knative.dev/eventing/test/rekt/resources/trigger/trigger.go
  vendor/knative.dev/hack/codegen-library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#976 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/lib/client.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/eventing/test/lib/logexporter.go
  vendor/knative.dev/eventing/test/lib/resources/serving.go
  vendor/knative.dev/eventing/test/performance/infra/image_helpers.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#979 Cleanup of the control-plane log package
  control-plane/pkg/contract/log_marshaller.go
  control-plane/pkg/log/log_marshaller.go
  control-plane/pkg/logging/logger.go
  control-plane/pkg/reconciler/base/reconciler.go
  control-plane/pkg/reconciler/broker/broker.go
  control-plane/pkg/reconciler/sink/kafka_sink.go
  control-plane/pkg/reconciler/trigger/trigger.go
Labels: approved, area/control-plane, cla: yes, lgtm, size/L

#980 [main] Format Go code
  control-plane/pkg/reconciler/base/reconciler.go
Labels: approved, area/control-plane, cla: yes, lgtm, size/XS

#982 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#990 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-uuid/.travis.yml
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-uuid/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-uuid/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-uuid/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-uuid/uuid.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/.gitignore
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/2q.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/arc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/doc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#986 Bump JVM version to 16
  .github/workflows/knative-java-test.yaml
  hack/data-plane.sh
Labels: approved, area/test, cla: yes, lgtm, size/XS

#987 Update k8s versions for KinD tests
  .github/workflows/kind-e2e.yaml
Labels: approved, area/test, cla: yes, lgtm, size/S

#992 Fix the path to the contract file
  data-plane/README.md
Labels: approved, area/data-plane, cla: yes, lgtm, size/XS

#993 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#994 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/knative.dev/eventing/pkg/kncloudevents/retries.go
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#997 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/conformance/helpers/channel_status_subscriber_test_helper.go
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#996 Reorganize the shutdown code a bit
  data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java
Labels: approved, area/data-plane, cla: yes, lgtm, size/S

#998 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#1000 Add permission to update namespaces/finalizer to webhook cluster role
  control-plane/config/sink/100-webhook-cluster-role.yaml
Labels: approved, area/control-plane, cla: yes, lgtm, size/XS

#985 Create multiple receiver verticles
  data-plane/profiler/resources/config-sacura-warmup.yaml
  data-plane/profiler/resources/config-sacura.yaml
  data-plane/profiler/run.sh
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/Main.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/ReceiverVerticleFactory.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/ReceiverVerticleFactoryTest.java
Labels: approved, area/data-plane, cla: yes, lgtm, size/L

#1003 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#1005 runAsNonRoot should be good enough
  data-plane/config/broker/template/500-dispatcher.yaml
  data-plane/config/broker/template/500-receiver.yaml
  data-plane/config/sink/template/500-receiver.yaml
Labels: approved, area/data-plane, cla: yes, lgtm, size/XS

#1006 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1008 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/factory.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/subscription.go
  vendor/knative.dev/pkg/test/environment/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1009 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#1015 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#1017 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#1018 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/conformance/helpers/channel_spec_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_status_subscriber_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_status_test_helper.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#911 Add e2e_new to gh actions
  .github/workflows/kind-e2e.yaml
  hack/tools.go
  vendor/knative.dev/eventing/test/test_images/event-library/main.go
  vendor/modules.txt
Labels: approved, area/control-plane, area/data-plane, area/test, cla: yes, lgtm, size/M

#999 Improve data-plane pods annotation update logic
  control-plane/pkg/reconciler/base/reconciler.go
  control-plane/pkg/reconciler/broker/broker.go
  control-plane/pkg/reconciler/broker/broker_test.go
  control-plane/pkg/reconciler/sink/kafka_sink.go
  control-plane/pkg/reconciler/sink/kafka_sink_test.go
Labels: approved, area/control-plane, cla: yes, lgtm, size/L

#1025 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/subscription.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1021 Add single request timeout to the contract
  control-plane/pkg/contract/contract.pb.go
  data-plane/contract/src/main/java/dev/knative/eventing/kafka/broker/contract/DataPlaneContract.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactory.java
  proto/contract.proto
Labels: approved, area/control-plane, area/data-plane, cla: yes, lgtm, size/L

#1024 Replaced ConsumerRecordSender.create with ConsumerRecordSender.noop
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerRecordSender.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactory.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/RecordDispatcherTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/AbstractConsumerVerticleTest.java
Labels: approved, area/data-plane, cla: yes, lgtm, size/M

#1022 Introduced `AsyncCloseable`
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/AsyncCloseable.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/metrics/Metrics.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/metrics/MetricsTest.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerRecordSender.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/RecordDispatcher.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/SinkResponseHandler.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/BaseConsumerVerticle.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerRecordSender.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactory.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpSinkResponseHandler.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerRecordSenderMock.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/RecordDispatcherTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/SinkResponseHandlerMock.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/AbstractConsumerVerticleTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpSinkResponseHandlerTest.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/RequestMapper.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/RequestMapperTest.java
Labels: approved, area/data-plane, cla: yes, lgtm, size/L

#1030 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/duck/v1/delivery_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/delivery_conversion.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/delivery_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/feature/api_validation.go
  vendor/knative.dev/eventing/pkg/apis/feature/features.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/eventing/pkg/apis/feature/store.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/knative.dev/eventing/pkg/kncloudevents/retries.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/recorder_vent/recorder.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1031 Moved receiver Main to a dedicated package
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/utils/BaseEnv.java
  data-plane/receiver/pom.xml
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/Main.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverEnv.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverVerticleFactory.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverEnvTest.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverVerticleFactoryTest.java
Labels: approved, area/data-plane, cla: yes, lgtm, size/M

#1032 Moved dispatcher Main to a dedicated package
  data-plane/dispatcher/pom.xml
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/DispatcherEnv.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/Main.java
Labels: approved, area/data-plane, cla: yes, lgtm, size/S

#1029 Streamline the usage of the ResourcesReconciler
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/reconciler/ResourcesReconciler.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/ResourcesReconcilerBuilder.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/ResourcesReconcilerImpl.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/ResourceReconcilerTestRunner.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/ResourcesReconcilerImplTest.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerDeployerVerticle.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerDeployerVerticleTest.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/ReceiverVerticle.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/RequestMapperTest.java
Labels: approved, area/data-plane, cla: yes, lgtm, size/L

#1035 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/eventshub/prober.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1033 Reorganize CloudEventRequestToRecordMapper
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/RequestMapper.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/RequestToRecordMapper.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/StrictRequestToRecordMapper.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverVerticleFactory.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/ReceiverTracingVerticleTest.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/ReceiverVerticleTest.java
  data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java
Labels: approved, area/data-plane, cla: yes, lgtm, size/L

#1036 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#1034 Glue the new DeliverySpec.Timeout
  control-plane/pkg/core/config/utils.go
  control-plane/pkg/core/config/utils_test.go
  control-plane/pkg/reconciler/trigger/trigger_test.go
Labels: approved, area/control-plane, cla: yes, lgtm, size/M

#1038 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-uuid/.travis.yml
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-uuid/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-uuid/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-uuid/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-uuid/uuid.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/.gitignore
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/2q.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/arc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/doc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
  vendor/knative.dev/eventing/pkg/kncloudevents/retries.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#1039 [main] Update actions
  .github/workflows/knative-go-test.yaml
Labels: approved, area/test, cla: yes, lgtm, size/XS

#1040 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#1042 Fix build on MacOS
  hack/data-plane.sh
Labels: approved, cla: yes, lgtm, size/XS

#1043 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#1028 Split RecordDispatcher in interface and implementation class
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/RecordDispatcher.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/RecordDispatcherImpl.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/RecordDispatcherListener.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/SinkResponseHandler.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/BaseConsumerVerticle.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/OrderedConsumerVerticle.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/OrderedOffsetManager.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/UnorderedConsumerVerticle.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/UnorderedOffsetManager.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactory.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/RecordDispatcherTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/AbstractConsumerVerticleTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/AbstractOffsetManagerTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/OrderedConsumerVerticleTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/OrderedOffsetManagerTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/UnorderedOffsetManagerTest.java
Labels: approved, area/data-plane, cla: yes, lgtm, size/XL

#1016 Enable upstream new conformance tests
  .github/workflows/kind-e2e.yaml
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/RequestMapper.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/RequestMapperTest.java
  hack/tools.go
  test/e2e_new/broker_conformance_test.go
  test/e2e_new/main_test.go
  third_party/eventing-v0.21.4/eventing-core.yaml
  third_party/eventing-v0.21.4/eventing-crds.yaml
  vendor/knative.dev/eventing/test/rekt/features/broker/control_plane.go
  vendor/knative.dev/eventing/test/rekt/features/broker/data_plane.go
  vendor/knative.dev/eventing/test/rekt/features/broker/readyness.go
  vendor/knative.dev/eventing/test/rekt/features/broker/source_to_sink.go
  vendor/knative.dev/eventing/test/rekt/features/broker/topology.go
  vendor/knative.dev/eventing/test/rekt/features/knconf/control_plane.go
  vendor/knative.dev/eventing/test/rekt/features/knconf/data_plane.go
  vendor/knative.dev/eventing/test/rekt/features/knconf/event_patterns.go
  vendor/knative.dev/eventing/test/rekt/resources/eventlibrary/README.md
  vendor/knative.dev/eventing/test/rekt/resources/eventlibrary/eventlibrary.go
  vendor/knative.dev/eventing/test/rekt/resources/eventlibrary/eventlibrary.yaml
  vendor/knative.dev/eventing/test/rekt/resources/flaker/flaker.go
  vendor/knative.dev/eventing/test/rekt/resources/flaker/flaker.yaml
  vendor/knative.dev/eventing/test/test_images/event-flaker/main.go
  vendor/modules.txt
Labels: approved, area/data-plane, area/test, cla: yes, lgtm, size/XXL

#962 Playing with Subscriptions API filters
  data-plane/THIRD-PARTY.txt
  data-plane/core/pom.xml
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/filter/impl/AllFilter.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/filter/impl/AnyFilter.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/filter/impl/BaseStringFilter.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/filter/impl/ExactFilter.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/filter/impl/PrefixFilter.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/filter/impl/SqlFilter.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/filter/impl/SuffixFilter.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/filter/impl/AllFilterTest.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/filter/impl/AnyFilterTest.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/filter/impl/ExactFilterTest.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/filter/impl/PrefixFilterTest.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/filter/impl/SqlFilterTest.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/filter/impl/SuffixFilterTest.java
  data-plane/pom.xml
Labels: approved, area/data-plane, cla: yes, lgtm, size/XL

#1051 Faster tracing headers test
  test/e2e_new/tracing_test.go
Labels: approved, area/test, cla: yes, lgtm, size/XS

#1053 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#1057 Move Filter code to dispatcher
  data-plane/core/pom.xml
  data-plane/dispatcher/pom.xml
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/Filter.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/RecordDispatcherImpl.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactory.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/filter/AllFilter.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/filter/AnyFilter.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/filter/AttributesFilter.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/filter/BaseStringFilter.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/filter/ExactFilter.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/filter/PrefixFilter.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/filter/SqlFilter.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/filter/SuffixFilter.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/RecordDispatcherTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/filter/AllFilterTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/filter/AnyFilterTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/filter/AttributesFilterTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/filter/ExactFilterTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/filter/PrefixFilterTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/filter/SqlFilterTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/filter/SuffixFilterTest.java
Labels: approved, area/data-plane, cla: yes, lgtm, size/M

#1055 Encapsulate runtime hook registration inside Shutdown
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/utils/Shutdown.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/utils/ShutdownTest.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/Main.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/Main.java
Labels: approved, area/data-plane, cla: yes, lgtm, size/L

#1056 Renamed getProperties to readPropertiesSync
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/utils/Configurations.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/utils/ConfigurationsTest.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/Main.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/Main.java
Labels: approved, area/data-plane, cla: yes, lgtm, size/M

#1059 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#1060 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#1058 Better receiver Main code
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/metrics/Metrics.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/Main.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverVerticleFactory.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverVerticleFactoryTest.java
Labels: approved, area/data-plane, cla: yes, lgtm, size/L

#1041 Reorganize RequestMapper and friends
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/IngressProducer.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/IngressRequestHandler.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/ReceiverVerticle.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/IngressProducerReconcilableStore.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticle.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/StrictRequestToRecordMapper.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/handler/IngressRequestHandlerImpl.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/handler/MethodNotAllowedHandler.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/handler/ProbeHandler.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverVerticleFactory.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/IngressProducerReconcilableStoreTest.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticleTest.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticleTracingTest.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/handler/IngressRequestHandlerImplTest.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/handler/MethodNotAllowedHandlerTest.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/handler/PreHandlerTest.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/handler/ProbeHandlerTest.java
  data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java
Labels: approved, area/data-plane, cla: yes, lgtm, size/XXL
