Repository knative-extensions/eventing-kafka-broker, pull requests merged in 2021-05, with the labels that each got.

#856 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/XL

#858 [release-0.22] Backport SASL/PLAIN fixes
  control-plane/pkg/security/config.go
  data-plane/THIRD-PARTY.txt
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/CredentialsValidator.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/KubernetesCredentials.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/security/CredentialsValidatorTest.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/security/KubernetesCredentialsTest.java
Labels: approved, area/control-plane, area/data-plane, cla: yes, kind/bug, lgtm, size/M

#861 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#869 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#862 Now codegen verifies the THIRD-PARTY.txt file
  .github/workflows/build-dependabot-pr.yaml
  .github/workflows/update-dependabot-pr.yaml
  data-plane/THIRD-PARTY.txt
  hack/update-codegen.sh
  hack/verify-codegen.sh
Labels: approved, area/data-plane, area/test, cla: yes, lgtm, size/L

#867 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
Labels: approved, area/test, cla: yes, lgtm, size/S

#875 Fix #870
  control-plane/config/100-config-logging.yaml
  data-plane/config/broker/100-config-logging.yaml
  data-plane/config/sink/100-config-logging.yaml
  hack/control-plane.sh
Labels: approved, area/control-plane, area/data-plane, cla: yes, lgtm, needs-ok-to-test, size/XS

#877 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#876 Dependabot PR workflow fix
  .github/workflows/build-dependabot-pr.yaml
Labels: approved, area/test, cla: yes, lgtm, size/XS

#873 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, area/test, cla: yes, lgtm, size/S

#892 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#894 [main] Update actions
  .github/workflows/knative-go-build.yaml
Labels: approved, area/test, cla: yes, lgtm, size/XS

#899 Fix the Google CLA bot
  .github/workflows/build-dependabot-pr.yaml
  .github/workflows/update-dependabot-pr.yaml
Labels: approved, area/test, cla: yes, lgtm, size/S

#891 [Automated] Update knative/community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#893 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/duck/v1/channelable_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/channel_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_types.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/listers.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_chain_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_dls_test_helper.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#905 Now verify codegen GH action should be happy
  go.sum
Labels: approved, cla: yes, lgtm, size/S

#889 Skip TestTriggerNoFinalizerOnBrokerNotFound test
  control-plane/pkg/reconciler/trigger/controller.go
  test/e2e_new/trigger_finalizer_test.go
Labels: approved, area/control-plane, area/test, cla: yes, lgtm, size/S

#906 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#907 Update deps
  go.mod
  go.sum
  hack/update-codegen.sh
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_types.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_chain_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_dls_test_helper.go
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#908 Update license plugin
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/AuthProvider.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/Credentials.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/CredentialsValidator.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/KafkaClientsAuth.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/KubernetesAuthProvider.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/KubernetesCredentials.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/PlaintextCredentials.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/security/CredentialsValidatorTest.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/security/KafkaClientsAuthTest.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/security/KubernetesAuthProviderTest.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/security/KubernetesCredentialsTest.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/testing/CloudEventSerializerMock.java
  data-plane/pom.xml
  test/e2e_new/trigger_finalizer_test.go
Labels: area/data-plane, area/test, cla: yes, lgtm, size/S

#913 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscribable_channelable_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_validation.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/listers.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/subscription.go
  vendor/knative.dev/eventing/test/lib/resources/eventing.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/destination.go
  vendor/knative.dev/pkg/leaderelection/chaosduck/main.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#912 Add more details in the status about ordered and unordered
  control-plane/pkg/reconciler/trigger/trigger.go
  control-plane/pkg/reconciler/trigger/trigger_lifecycle.go
  control-plane/pkg/reconciler/trigger/trigger_test.go
Labels: approved, area/control-plane, cla: yes, kind/enhancement, lgtm, size/M

#914 Bump third party files
  .github/workflows/kind-e2e.yaml
  third_party/eventing-v0.21.4/eventing-core.yaml
  third_party/eventing-v0.21.4/eventing-crds.yaml
  third_party/eventing-v0.22.1/eventing-core.yaml
  third_party/eventing-v0.22.1/eventing-crds.yaml
  third_party/eventing-v0.23.0/eventing-core.yaml
  third_party/eventing-v0.23.0/eventing-crds.yaml
Labels: approved, area/test, cla: yes, lgtm, size/XXL

#918 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/e2e/helpers/channel_event_tranformation_test_helper.go
  vendor/knative.dev/eventing/test/lib/resources/eventing.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#917 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#886 Bump Go version
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/XS

#835 Bump Strimzi from 0.21 to 0.23.0
  test/kafka/kafka-ephemeral.yaml
  test/kafka/strimzi-cluster-operator.yaml
  test/kafka/user-sasl-scram-512.yaml
  test/kafka/user-tls.yaml
Labels: approved, area/test, cla: yes, lgtm, size/XXL

#749 Refresh development docs and flow
  .github/workflows/kind-e2e.yaml
  .github/workflows/knative-java-test.yaml
  CONTRIBUTING.md
  DEVELOPMENT.md
  data-plane/profiler/README.md
  data-plane/profiler/run.sh
  hack/create-kind-cluster.sh
  hack/generate-proto.sh
  hack/run.sh
  test/README.md
  test/config/sacura/100-broker-config.yaml
  test/config/sacura/101-broker.yaml
  test/e2e-common.sh
  test/e2e-tests.sh
Labels: approved, area/control-plane, area/data-plane, area/test, cla: yes, lgtm, size/XL

#880 [release-0.22] Do not add a finalizer on triggers without a broker
  control-plane/pkg/reconciler/trigger/controller.go
  control-plane/pkg/reconciler/trigger/controller_test.go
Labels: approved, area/control-plane, cla: yes, kind/bug, lgtm, size/XS

#922 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#919 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#923 Remove WITH_KIND
  .github/workflows/kind-e2e.yaml
  hack/data-plane.sh
Labels: approved, area/test, cla: yes, lgtm, size/S

#925 [main] Upgrade to latest dependencies
  control-plane/pkg/client/injection/informers/factory/filtered/fake/fake_filtered_factory.go
  control-plane/pkg/client/injection/informers/factory/filtered/filtered_factory.go
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_factory.go
  vendor/modules.txt
Labels: approved, area/control-plane, cla: yes, lgtm, size/M

#926 Remove CODEOWNERS
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, size/XS

#927 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, area/test, cla: yes, lgtm, size/XS

#930 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#932 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/apis/condition_types.go
  vendor/knative.dev/pkg/apis/deprecated.go
  vendor/knative.dev/pkg/apis/duck/register.go
  vendor/knative.dev/pkg/apis/duck/v1/register.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/register.go
  vendor/knative.dev/pkg/configmap/manual_watcher.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/knative.dev/pkg/system/env.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/test/tinterface.go
  vendor/knative.dev/pkg/tracing/zipkin.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#937 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#934 [release-0.21] Do not add a finalizer on triggers without a broker
  control-plane/pkg/contract/contract.pb.go
  control-plane/pkg/reconciler/trigger/controller.go
  control-plane/pkg/reconciler/trigger/controller_test.go
  go.mod
  go.sum
  hack/control-plane.sh
  hack/data-plane.sh
  test/e2e-common.sh
  vendor/github.com/golang/protobuf/ptypes/empty/empty.pb.go
  vendor/modules.txt
Labels: approved, area/control-plane, area/test, cla: yes, kind/bug, lgtm, size/M

#940 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#945 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, area/test, cla: yes, lgtm, size/S

#943 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/client/injection/apiextensions/client/client.go
  vendor/knative.dev/pkg/client/injection/apiextensions/client/fake/fake.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/addressable/addressable.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/addressable/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1/mutatingwebhookconfiguration/mutatingwebhookconfiguration.go
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1/validatingwebhookconfiguration/validatingwebhookconfiguration.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/configmap/configmap.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/configmap/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/pod/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/pod/pod.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/secret/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/secret/secret.go
  vendor/knative.dev/pkg/client/injection/kube/informers/factory/factory.go
  vendor/knative.dev/pkg/client/injection/kube/informers/factory/fake/fake.go
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/knative.dev/pkg/injection/config.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/logging/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/metrics/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/environment/config.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/tracker/zz_generated.deepcopy.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#948 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/README.md
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#947 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L
