Repository knative-extensions/eventing-kafka-broker, pull requests merged in 2021-02, with the labels that each got.

#580 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_conversion.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#581 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_conversion.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/broker.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1beta1/broker.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#583 Fix link to Kafka download page
  data-plane/profiler/run.sh
Labels: approved, area/data-plane, cla: yes, lgtm, size/XS

#584 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, area/test, cla: yes, lgtm, size/XS

#587 Updated opentelemetry to 0.15
  data-plane/THIRD-PARTY.txt
  data-plane/core/pom.xml
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/eventbus/ContractPublisher.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/tracing/OpenTelemetryTracer.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/tracing/Tracing.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/tracing/TracingSpan.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/utils/Shutdown.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/utils/ShutdownTest.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/Main.java
  data-plane/pom.xml
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/Main.java
Labels: approved, area/data-plane, cla: yes, lgtm, size/L

#593 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#595 Increment contract generation on Broker and KafkaSink finalize
  control-plane/pkg/core/config/utils.go
  control-plane/pkg/core/config/utils_test.go
  control-plane/pkg/reconciler/broker/broker.go
  control-plane/pkg/reconciler/broker/broker_test.go
  control-plane/pkg/reconciler/sink/kafka_sink.go
  control-plane/pkg/reconciler/sink/kafka_sink_test.go
  control-plane/pkg/reconciler/trigger/trigger.go
Labels: approved, area/control-plane, cla: yes, lgtm, size/M

#600 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/broker_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#597 Fix bad offset management
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerRecordHandler.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategy.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/ConsumerVerticleFactoryMock.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/UnorderedConsumerTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/strategy/UnorderedConsumerRecordOffsetStrategyTest.java
Labels: approved, area/data-plane, cla: yes, kind/bug, lgtm, size/L

#568 Data plane reconciler handles failed reconciliation.
  data-plane/core/pom.xml
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/eventbus/ContractPublisher.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/file/FileWatcher.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/ResourcesReconcilerImpl.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/ResourcesReconcilerMessageHandler.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/utils/CollectionsUtils.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/file/FileWatcherTest.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/EgressReconcilerListenerMock.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/IngressReconcilerListenerMock.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/ResourceReconcilerTestRunner.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/ResourcesReconcilerImplTest.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/ResourcesReconcilerMessageHandlerTest.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerDeployerVerticle.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/ReceiverVerticle.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/RequestMapper.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/RequestMapperTest.java
  data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java
  go.sum
Labels: approved, area/data-plane, cla: yes, kind/bug, lgtm, size/XXL

#609 Execute sacura job in parallel
  test/e2e-tests.sh
Labels: approved, area/test, cla: yes, lgtm, size/S

#608 Avoid building receiver twice
  hack/data-plane.sh
Labels: approved, cla: yes, lgtm, size/S

#613 Reduce sleep time in GH actions test setup
  .github/workflows/kind-e2e.yaml
Labels: approved, area/test, cla: yes, lgtm, size/XS

#557 Consume topic from the earliest offset
  control-plane/pkg/reconciler/trigger/trigger.go
  data-plane/config/100-config-kafka-broker-data-plane.yaml
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerVerticle.java
Labels: approved, area/control-plane, area/data-plane, cla: yes, kind/bug, lgtm, size/S

#614 Refactor ConsumerRecordHandler
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerRecordHandler.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerVerticle.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerVerticleFactory.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/Main.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/RecordDispatcher.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/OffsetManager.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/OffsetManagerFactory.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/UnorderedOffsetManager.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactory.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerVerticleTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/RecordDispatcherTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/UnorderedOffsetManagerTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactoryTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/ConsumerVerticleFactoryMock.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/UnorderedConsumerTest.java
  data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java
Labels: approved, area/data-plane, cla: yes, lgtm, size/XL

#623 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, area/test, cla: yes, lgtm, size/XS

#621 [release-0.20] Set auto offset reset to earliest
  data-plane/config/100-config-kafka-broker-data-plane.yaml
Labels: approved, area/data-plane, cla: yes, lgtm, size/XS

#622 [release-0.19] Set auto offset reset to earliest
  data-plane/config/100-config-kafka-broker-data-plane.yaml
Labels: approved, area/data-plane, cla: yes, lgtm, size/XS

#618 Update OWNERS
  OWNERS
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#620 Clean up RecordDispatcher
  data-plane/THIRD-PARTY.txt
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/RecordDispatcher.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/RecordDispatcherTest.java
Labels: approved, area/data-plane, cla: yes, lgtm, size/L

#627 Upgrade dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_types.go
  vendor/knative.dev/eventing/test/conformance/helpers/broker_control_plane_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/README.md
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#624 Install eventing from nightly release
  test/e2e-common.sh
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, area/test, cla: yes, lgtm, size/XXL

#625 Handle ClosedWatchServiceEx and timeouts
  data-plane/config/sink/template/500-receiver.yaml
  data-plane/config/template/500-dispatcher.yaml
  data-plane/config/template/500-receiver.yaml
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/utils/BaseEnv.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/utils/Shutdown.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/utils/BaseEnvTest.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/Main.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/Main.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/ReceiverEnvTest.java
Labels: approved, area/data-plane, cla: yes, lgtm, size/L

#632 I'm not a TOC member
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#638 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/metrics/memstats.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#643 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/metrics/reflector.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#640 OffsetManager Benchmark
  data-plane/THIRD-PARTY.txt
  data-plane/benchmarks/pom.xml
  data-plane/benchmarks/src/main/java/dev/knative/eventing/kafka/broker/benchmarks/UnorderedOffsetManagerBenchmark.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/UnorderedOffsetManager.java
  data-plane/docker/Dockerfile
  data-plane/pom.xml
Labels: approved, area/data-plane, cla: yes, lgtm, size/XL

#649 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/config/ping_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/config/store.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#648 Improved UnorderedOffsetManager
  data-plane/benchmarks/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/UnorderedOffsetManagerBenchmark.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/UnorderedOffsetManager.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/UnorderedOffsetManagerTest.java
Labels: approved, area/data-plane, cla: yes, lgtm, size/L

#651 Make sure we can switch logger whenever we want
  data-plane/THIRD-PARTY.txt
  data-plane/core/pom.xml
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/file/FileWatcher.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/ResourcesReconcilerImpl.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/ResourcesReconcilerMessageHandler.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/KubernetesCredentials.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/tracing/HeadersPropagatorGetter.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/tracing/HeadersPropagatorSetter.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/tracing/OpenTelemetryTracer.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/tracing/Tracing.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/utils/Configurations.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/utils/Logging.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/utils/LoggingTest.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/ConsumerDeployerVerticle.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/Main.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/RecordDispatcher.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/OrderedOffsetManager.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerRecordSender.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpSinkResponseHandler.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/CloudEventRequestToRecordMapper.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/Main.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/RequestMapper.java
Labels: approved, area/data-plane, cla: yes, lgtm, size/L

#642 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: approved, area/test, cla: yes, lgtm, ok-to-test, size/S

#634 Debug sacura job
  go.mod
  go.sum
  vendor/github.com/pierdipi/sacura/cmd/sacura/main.go
  vendor/github.com/pierdipi/sacura/state.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#652 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/config/ping_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/config/store.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_validation.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#658 Adding devguyio to reviewers
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#639 Implemented OrderedConsumerVerticle
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/OrderedAsyncExecutor.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/OrderedAsyncExecutorTest.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/RecordDispatcher.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/OffsetManager.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/BaseConsumerVerticle.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/OrderedConsumerVerticle.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/UnorderedConsumerVerticle.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactory.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/AbstractConsumerVerticleTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/AbstractOffsetManagerTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/OrderedConsumerVerticleTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/OrderedOffsetManagerTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/UnorderedConsumerVerticleTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/UnorderedOffsetManagerTest.java
Labels: approved, area/data-plane, cla: yes, lgtm, size/XXL

#664 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#675 update deps for 0.21
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#673 Add CODEOWNERS file for approvals
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS
