Repository knative-extensions/eventing-kafka-broker, pull requests merged in 2021-10, with the labels that each got.

#1274 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-kafka-latest/channel-crds.yaml
Labels: cla: yes, approved, size/XS, lgtm

#1270 Download zipkin from Github's container registry
  test/config/monitoring.yaml
Labels: cla: yes, approved, size/XS, lgtm, area/test

#1277 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/channel_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_validation.go
  vendor/modules.txt
Labels: cla: yes, approved, size/M, lgtm

#1283 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: cla: yes, approved, lgtm, size/L

#1281 [minor] Use Maven wrapper to run unit tests
  hack/data-plane.sh
Labels: cla: yes, approved, size/XS, lgtm

#1285 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/knative.dev/pkg/webhook/conversion.go
  vendor/modules.txt
Labels: cla: yes, approved, size/M, lgtm

#1287 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: cla: yes, approved, lgtm, size/L

#1286 [Automated] Update eventing-kafka-broker-eventing-kafka nightly
  third_party/eventing-kafka-latest/channel-crds.yaml
Labels: cla: yes, approved, size/XS, lgtm

#1299 Rename condition set for ingress resources and check if `SetAddress` function is set
  control-plane/pkg/reconciler/base/receiver_condition_set.go
  control-plane/pkg/reconciler/broker/broker_test.go
  control-plane/pkg/reconciler/broker/controller.go
  control-plane/pkg/reconciler/channel/controller.go
  control-plane/pkg/reconciler/sink/controller.go
  control-plane/pkg/reconciler/sink/kafka_sink_test.go
  control-plane/pkg/reconciler/trigger/trigger_test.go
Labels: cla: yes, approved, size/M, lgtm, area/control-plane

#1303 Debug Maven stuck
  hack/data-plane.sh
Labels: cla: yes, approved, size/XS, lgtm

#1301 Bump maven version to the latest release
  data-plane/.mvn/wrapper/maven-wrapper.properties
Labels: cla: yes, approved, size/XS, lgtm, area/data-plane

#1310 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: cla: yes, approved, lgtm, size/L

#1317 [Automated] Update eventing-kafka-broker-eventing-kafka nightly
  third_party/eventing-kafka-latest/channel-crds.yaml
  third_party/eventing-kafka-latest/source-crds.yaml
Labels: cla: yes, approved, lgtm, size/L

#1321 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: cla: yes, approved, lgtm, size/S, area/test

#1329 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: cla: yes, approved, lgtm, size/L

#1336 Little rename of func
  control-plane/pkg/reconciler/broker/broker.go
Labels: cla: yes, approved, size/XS, lgtm, area/control-plane

#1346 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: cla: yes, approved, lgtm, size/L

#1355 Prefactoring the structure to be able to mock ClusterAdmin - DeleteTopic func
  control-plane/pkg/reconciler/broker/broker.go
  control-plane/pkg/reconciler/channel/channel.go
  control-plane/pkg/reconciler/kafka/config.go
  control-plane/pkg/reconciler/kafka/topic.go
  control-plane/pkg/reconciler/kafka/topic_test.go
  control-plane/pkg/reconciler/sink/kafka_sink.go
Labels: cla: yes, approved, lgtm, size/L, area/control-plane

#1383 Add security provider for KafkaNetSpec
  control-plane/pkg/reconciler/source/source.go
  control-plane/pkg/security/secrets_provider_net_spec.go
  control-plane/pkg/security/secrets_provider_net_spec_test.go
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/KubernetesAuthProvider.java
Labels: cla: yes, approved, lgtm, size/XL, area/data-plane, area/control-plane

#1385 Add secret tracker for KafkaNetSpec
  control-plane/pkg/reconciler/source/source.go
  control-plane/pkg/security/secrets_tracker.go
  control-plane/pkg/security/secrets_tracker_test.go
Labels: cla: yes, approved, lgtm, size/L, area/control-plane

#1391 [main] Format Go code
  test/e2e_new/broker_not_ready_test.go
Labels: cla: yes, approved, size/XS, lgtm, area/test
