Repository knative-extensions/eventing-kafka-broker, pull requests merged in 2021-08, with the labels that each got.

#1119 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#1121 Resolve response already sent with a chain of handlers
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticle.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/handler/MethodNotAllowedHandler.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/handler/ProbeHandler.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverEnv.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverVerticleFactory.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticleTest.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticleTracingTest.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/handler/MethodNotAllowedHandlerTest.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/handler/ProbeHandlerTest.java
  data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java
Labels: approved, area/data-plane, cla: yes, kind/bug, lgtm, size/L

#1122 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#1126 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/knative.dev/pkg/hack/generate-knative.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#1125 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, area/test, cla: yes, lgtm, size/XS

#1128 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: cla: yes, approved, lgtm, size/L

#1129 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/conformance/helpers/broker_data_plane_test_helper.go
  vendor/modules.txt
Labels: cla: yes, approved, size/M, lgtm

#1130 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: cla: yes, approved, lgtm, size/L

#1133 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: cla: yes, approved, size/XS, lgtm

#1138 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/S

#1135 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: cla: yes, approved, lgtm, size/L

#1144 [main] Upgrade to latest dependencies
  control-plane/pkg/client/injection/client/client.go
  control-plane/pkg/client/injection/informers/eventing/v1alpha1/kafkasink/filtered/kafkasink.go
  control-plane/pkg/client/injection/informers/eventing/v1alpha1/kafkasink/kafkasink.go
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/interfaces.go
  vendor/knative.dev/pkg/client/injection/apiextensions/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/client_expansion.go
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1/mutatingwebhookconfiguration/mutatingwebhookconfiguration.go
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1/validatingwebhookconfiguration/validatingwebhookconfiguration.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/configmap/configmap.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/pod/pod.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/secret/secret.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/injection/clients.go
  vendor/knative.dev/pkg/injection/clients/namespacedkube/informers/core/v1/secret/secret.go
  vendor/knative.dev/pkg/injection/informers.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/network/error_handler.go
  vendor/knative.dev/pkg/network/handlers/error.go
  vendor/knative.dev/pkg/tracing/zipkin.go
  vendor/knative.dev/pkg/tracker/interface.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/XXL, area/control-plane

#1145 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: cla: yes, approved, lgtm, size/L

#1150 Bump to latest eventing, fix Trigger DeadLetterSinkURI
  control-plane/pkg/reconciler/trigger/trigger_lifecycle.go
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/client/injection/client/client.go
  vendor/knative.dev/eventing/pkg/client/injection/informers/eventing/v1/broker/broker.go
  vendor/knative.dev/eventing/pkg/client/injection/informers/eventing/v1/trigger/trigger.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/trigger.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/XXL, area/control-plane

#1153 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, size/XS, lgtm

#1155 [main] Upgrade to latest dependencies
  control-plane/pkg/client/injection/reconciler/eventing/v1alpha1/kafkasink/controller.go
  control-plane/pkg/client/injection/reconciler/eventing/v1alpha1/kafkasink/reconciler.go
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/duck/listable.go
  vendor/knative.dev/eventing/test/lib/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/client_expansion.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/pkg/webhook/certificates/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/knative.dev/reconciler-test/pkg/k8s/steps.go
  vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/L, area/control-plane

#1154 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: cla: yes, approved, lgtm, size/L

#1134 Channel api
  .github/workflows/knative-boilerplate.yaml
  .golangci.yaml
  control-plane/cmd/kafka-controller/main.go
  control-plane/pkg/apis/eventing/v1alpha1/kafka_sink_defaults_test.go
  control-plane/pkg/apis/eventing/v1alpha1/kafka_sink_validation_test.go
  control-plane/pkg/apis/messaging/register.go
  control-plane/pkg/apis/messaging/v1beta1/doc.go
  control-plane/pkg/apis/messaging/v1beta1/kafka_channel_conversion.go
  control-plane/pkg/apis/messaging/v1beta1/kafka_channel_conversion_test.go
  control-plane/pkg/apis/messaging/v1beta1/kafka_channel_defaults.go
  control-plane/pkg/apis/messaging/v1beta1/kafka_channel_defaults_test.go
  control-plane/pkg/apis/messaging/v1beta1/kafka_channel_lifecycle.go
  control-plane/pkg/apis/messaging/v1beta1/kafka_channel_lifecycle_test.go
  control-plane/pkg/apis/messaging/v1beta1/kafka_channel_types.go
  control-plane/pkg/apis/messaging/v1beta1/kafka_channel_types_test.go
  control-plane/pkg/apis/messaging/v1beta1/kafka_channel_validation.go
  control-plane/pkg/apis/messaging/v1beta1/kafka_channel_validation_test.go
  control-plane/pkg/apis/messaging/v1beta1/register.go
  control-plane/pkg/apis/messaging/v1beta1/zz_generated.deepcopy.go
  control-plane/pkg/client/clientset/versioned/clientset.go
  control-plane/pkg/client/clientset/versioned/fake/clientset_generated.go
  control-plane/pkg/client/clientset/versioned/fake/register.go
  control-plane/pkg/client/clientset/versioned/scheme/register.go
  control-plane/pkg/client/clientset/versioned/typed/messaging/v1beta1/doc.go
  control-plane/pkg/client/clientset/versioned/typed/messaging/v1beta1/fake/doc.go
  control-plane/pkg/client/clientset/versioned/typed/messaging/v1beta1/fake/fake_kafkachannel.go
  control-plane/pkg/client/clientset/versioned/typed/messaging/v1beta1/fake/fake_messaging_client.go
  control-plane/pkg/client/clientset/versioned/typed/messaging/v1beta1/generated_expansion.go
  control-plane/pkg/client/clientset/versioned/typed/messaging/v1beta1/kafkachannel.go
  control-plane/pkg/client/clientset/versioned/typed/messaging/v1beta1/messaging_client.go
  control-plane/pkg/client/informers/externalversions/factory.go
  control-plane/pkg/client/informers/externalversions/generic.go
  control-plane/pkg/client/informers/externalversions/messaging/interface.go
  control-plane/pkg/client/informers/externalversions/messaging/v1beta1/interface.go
  control-plane/pkg/client/informers/externalversions/messaging/v1beta1/kafkachannel.go
  control-plane/pkg/client/injection/client/client.go
  control-plane/pkg/client/injection/informers/messaging/v1beta1/kafkachannel/fake/fake.go
  control-plane/pkg/client/injection/informers/messaging/v1beta1/kafkachannel/filtered/fake/fake.go
  control-plane/pkg/client/injection/informers/messaging/v1beta1/kafkachannel/filtered/kafkachannel.go
  control-plane/pkg/client/injection/informers/messaging/v1beta1/kafkachannel/kafkachannel.go
  control-plane/pkg/client/injection/reconciler/messaging/v1beta1/kafkachannel/controller.go
  control-plane/pkg/client/injection/reconciler/messaging/v1beta1/kafkachannel/reconciler.go
  control-plane/pkg/client/injection/reconciler/messaging/v1beta1/kafkachannel/state.go
  control-plane/pkg/client/listers/messaging/v1beta1/expansion_generated.go
  control-plane/pkg/client/listers/messaging/v1beta1/kafkachannel.go
  control-plane/pkg/receiver/path.go
  control-plane/pkg/receiver/path_test.go
  control-plane/pkg/reconciler/kafka/testing/admin_mock.go
  control-plane/pkg/reconciler/kafka/topic_test.go
  hack/tools.go
  hack/update-codegen.sh
  test/e2e_new/resources/kafkasink/kafkasink.go
  test/e2e_new/resources/kafkasink/kafkasink_test.go
Labels: cla: yes, approved, lgtm, size/XXL, area/control-plane, area/test

#1162 Channel lifecycle
  control-plane/pkg/apis/messaging/v1beta1/kafka_channel_lifecycle.go
  control-plane/pkg/apis/messaging/v1beta1/kafka_channel_lifecycle_test.go
Labels: cla: yes, approved, lgtm, size/XL, area/control-plane

#1158 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: cla: yes, approved, lgtm, size/L

#1164 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: cla: yes, approved, lgtm, size/L

#1167 Use `controller.Impl` tracker and cleanups
  control-plane/pkg/core/config/utils_test.go
  control-plane/pkg/reconciler/broker/broker_test.go
  control-plane/pkg/reconciler/broker/controller.go
  control-plane/pkg/reconciler/trigger/controller.go
  control-plane/pkg/reconciler/trigger/trigger_test.go
  test/pkg/observability/watch_config_map.go
Labels: cla: yes, approved, size/M, lgtm, kind/cleanup, area/control-plane, area/test

#1184 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: cla: yes, approved, lgtm, size/L

#1185 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/modules.txt
Labels: cla: yes, approved, size/M, lgtm

#1186 Lets use a generic kafkalogging, rather than broker
  control-plane/pkg/reconciler/broker/broker.go
  control-plane/pkg/reconciler/channel/channel.go
  control-plane/pkg/reconciler/sink/kafka_sink.go
  control-plane/pkg/reconciler/trigger/trigger.go
Labels: cla: yes, approved, lgtm, size/S, area/control-plane

#1187 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: cla: yes, approved, lgtm, size/L

#1188 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_validation.go
  vendor/modules.txt
Labels: cla: yes, approved, size/M, lgtm

#1148 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-style.yaml
Labels: cla: yes, approved, size/XS, lgtm, area/test
