Repository knative-extensions/eventing-kafka-broker, pull requests merged in 2021-11, with the labels that each got.

#1397 Document maturity levels in sandbox
  README.md
Labels: cla: yes, approved, size/XS, lgtm

#1374 Kafka Channel Subscription reconciliation - control plane
  control-plane/pkg/core/config/egress.go
  control-plane/pkg/core/config/egress_test.go
  control-plane/pkg/reconciler/broker/broker.go
  control-plane/pkg/reconciler/channel/channel.go
  control-plane/pkg/reconciler/channel/controller.go
  control-plane/pkg/reconciler/kafka/client.go
  control-plane/pkg/reconciler/sink/kafka_sink.go
  control-plane/pkg/reconciler/source/source.go
  go.mod
  vendor/knative.dev/eventing-kafka/pkg/common/kafka/offset/offsets.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/L, area/control-plane

#1392 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/L

#1398 Let's use NewKafkaClusterAdminClient as the name to avoid confusion
  control-plane/pkg/reconciler/broker/broker.go
  control-plane/pkg/reconciler/broker/broker_test.go
  control-plane/pkg/reconciler/broker/controller.go
  control-plane/pkg/reconciler/channel/channel.go
  control-plane/pkg/reconciler/channel/controller.go
  control-plane/pkg/reconciler/kafka/client.go
  control-plane/pkg/reconciler/kafka/topic_test.go
  control-plane/pkg/reconciler/sink/controller.go
  control-plane/pkg/reconciler/sink/kafka_sink.go
  control-plane/pkg/reconciler/sink/kafka_sink_test.go
  control-plane/pkg/reconciler/source/controller.go
  control-plane/pkg/reconciler/source/source.go
  control-plane/pkg/reconciler/source/source_test.go
Labels: cla: yes, approved, size/M, lgtm, area/control-plane

#1396 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: cla: yes, approved, lgtm, size/L

#1393 Remove egresses copy when comparing resources for change detection
  control-plane/pkg/core/config/resource.go
  control-plane/pkg/core/config/resource_test.go
  control-plane/pkg/reconciler/broker/broker.go
  control-plane/pkg/reconciler/source/source.go
Labels: cla: yes, approved, size/M, lgtm, area/control-plane

#1399 Init offsets when initialOffset is latest in KafkaSource
  control-plane/pkg/reconciler/base/receiver_condition_set.go
  control-plane/pkg/reconciler/kafka/consumer_group.go
  control-plane/pkg/reconciler/kafka/testing/client_mock.go
  control-plane/pkg/reconciler/source/controller.go
  control-plane/pkg/reconciler/source/source.go
  control-plane/pkg/reconciler/source/source_test.go
  control-plane/pkg/reconciler/testing/objects_source.go
Labels: cla: yes, approved, lgtm, size/L, area/control-plane

#1402 Check verticle exception handler presence
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/BaseConsumerVerticle.java
Labels: cla: yes, approved, size/XS, lgtm, area/data-plane

#1403 Enable KafkaSource auth support
  control-plane/pkg/reconciler/source/auth_provider.go
Labels: cla: yes, approved, lgtm, size/S, area/control-plane

#1409 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/S

#1339 Enable KafkaSource controller
  .gitignore
  control-plane/cmd/kafka-controller/main.go
  control-plane/cmd/webhook-kafka/main.go
  control-plane/config/200-controller/200-controller-cluster-role.yaml
  control-plane/config/200-controller/500-controller.yaml
  control-plane/pkg/reconciler/source/controller.go
  data-plane/config/source/100-config-kafka-source-data-plane.yaml
  data-plane/config/source/200-source-data-plane-cluster-role.yaml
  data-plane/config/source/200-source-data-plane-service-account.yaml
  data-plane/config/source/201-source-data-plane-cluster-role-binding.yaml
  data-plane/config/source/template/500-dispatcher.yaml
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/KeyDeserializerTest.java
  hack/data-plane.sh
  test/e2e-common.sh
  test/e2e/kafka_source_test.go
  vendor/knative.dev/eventing-kafka/test/e2e/helpers/channel_subscription_ready_test_helper.go
  vendor/knative.dev/eventing-kafka/test/e2e/helpers/kafka_binding_test_helper.go
  vendor/knative.dev/eventing-kafka/test/e2e/helpers/kafka_helper.go
  vendor/knative.dev/eventing-kafka/test/e2e/helpers/kafka_source.go
  vendor/knative.dev/eventing-kafka/test/e2e/helpers/kafka_source_test_helper.go
  vendor/knative.dev/eventing-kafka/test/lib/creation.go
  vendor/knative.dev/eventing-kafka/test/lib/deletion.go
  vendor/knative.dev/eventing-kafka/test/lib/listers.go
  vendor/knative.dev/eventing-kafka/test/lib/resources/kafka.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/XXL, area/data-plane, area/control-plane, area/test

#1411 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: cla: yes, approved, size/XS, lgtm, area/test

#1415 Add KafkaSource to released YAMLs
  hack/release.sh
Labels: cla: yes, approved, size/XS, lgtm

#1413 Watch contract configmap in channel controller
  control-plane/pkg/reconciler/channel/controller.go
  control-plane/pkg/reconciler/channel/controller_test.go
  vendor/knative.dev/eventing-kafka/pkg/client/injection/informers/messaging/v1beta1/kafkachannel/fake/fake.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/L, area/control-plane

#1419 Better naming and consistency for config.Env and broker.Config
  control-plane/cmd/kafka-controller/main.go
  control-plane/pkg/reconciler/base/receiver_condition_set.go
  control-plane/pkg/reconciler/broker/broker.go
  control-plane/pkg/reconciler/broker/broker_test.go
  control-plane/pkg/reconciler/broker/controller.go
  control-plane/pkg/reconciler/broker/controller_test.go
  control-plane/pkg/reconciler/channel/channel.go
  control-plane/pkg/reconciler/channel/controller.go
  control-plane/pkg/reconciler/sink/controller.go
  control-plane/pkg/reconciler/sink/kafka_sink.go
  control-plane/pkg/reconciler/sink/kafka_sink_test.go
  control-plane/pkg/reconciler/source/source.go
  control-plane/pkg/reconciler/source/source_test.go
  control-plane/pkg/reconciler/testing/factory.go
  control-plane/pkg/reconciler/testing/objects_broker.go
  control-plane/pkg/reconciler/testing/objects_common.go
  control-plane/pkg/reconciler/testing/objects_source.go
  control-plane/pkg/reconciler/trigger/controller.go
  control-plane/pkg/reconciler/trigger/trigger.go
  control-plane/pkg/reconciler/trigger/trigger_test.go
Labels: cla: yes, approved, lgtm, size/XL, area/control-plane, area/test

#1426 [Automated] Update eventing-kafka-broker-eventing-kafka nightly
  third_party/eventing-kafka-latest/channel-crds.yaml
  third_party/eventing-kafka-latest/source-crds.yaml
Labels: cla: yes, approved, size/XS, lgtm

#1427 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: cla: yes, approved, lgtm, size/L

#1432 Separate step for just launching Kafka cluster (Strimzi)
  hack/run.sh
  test/e2e-common.sh
Labels: cla: yes, approved, size/XS, lgtm, area/test

#1434 Separate default envs in testing
  control-plane/pkg/reconciler/broker/broker_test.go
  control-plane/pkg/reconciler/sink/kafka_sink_test.go
  control-plane/pkg/reconciler/source/source_test.go
  control-plane/pkg/reconciler/testing/factory.go
  control-plane/pkg/reconciler/trigger/trigger_test.go
Labels: cla: yes, approved, size/M, lgtm, area/control-plane

#1433 Replace deprecated dry-run usage arg
  test/kafka/kafka_setup.sh
Labels: cla: yes, approved, size/XS, lgtm, area/test

#1436 Reuse testing funcs in reconciler tests
  control-plane/pkg/reconciler/broker/broker_test.go
  control-plane/pkg/reconciler/sink/kafka_sink_test.go
  control-plane/pkg/reconciler/source/source_test.go
  control-plane/pkg/reconciler/testing/objects_broker.go
  control-plane/pkg/reconciler/testing/objects_common.go
  control-plane/pkg/reconciler/testing/objects_sink.go
  control-plane/pkg/reconciler/testing/objects_source.go
  control-plane/pkg/reconciler/trigger/trigger_test.go
Labels: cla: yes, approved, lgtm, size/XL, area/control-plane

#1439 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: cla: yes, approved, lgtm, size/L

#1440 [Automated] Update eventing-kafka-broker-eventing-kafka nightly
  third_party/eventing-kafka-latest/channel-crds.yaml
  third_party/eventing-kafka-latest/source-crds.yaml
Labels: cla: yes, approved, size/XS, lgtm

#1401 Add probes cache
  control-plane/pkg/prober/cache.go
  control-plane/pkg/prober/cache_test.go
Labels: cla: yes, approved, lgtm, size/L, area/control-plane

#1414 Remove unicode control characters in Strimzi operator YAML
  test/kafka/strimzi-cluster-operator.yaml
Labels: cla: yes, approved, size/XS, lgtm, area/test

#1405 Commit offsets at specified intervals
  data-plane/benchmarks/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/UnorderedOffsetManagerBenchmark.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/RecordDispatcherListener.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherImpl.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetManager.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OrderedOffsetManager.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/UnorderedOffsetManager.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleFactoryImpl.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/AbstractOffsetManagerTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetManagerTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OrderedOffsetManagerTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/UnorderedConsumerTest.java
  data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java
Labels: cla: yes, approved, lgtm, size/XL, area/data-plane

#1452 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing-kafka/test/lib/creation.go
  vendor/knative.dev/eventing/test/rekt/features/broker/readyness.go
  vendor/knative.dev/eventing/test/rekt/features/broker/source_to_sink.go
  vendor/knative.dev/eventing/test/rekt/features/trigger/trigger_sink_resolution.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/L

#1447 Initial Kafka channel reconciler tests
  control-plane/pkg/reconciler/broker/broker_test.go
  control-plane/pkg/reconciler/channel/channel.go
  control-plane/pkg/reconciler/channel/channel_test.go
  control-plane/pkg/reconciler/channel/controller.go
  control-plane/pkg/reconciler/sink/kafka_sink_test.go
  control-plane/pkg/reconciler/source/source_test.go
  control-plane/pkg/reconciler/testing/listers.go
  control-plane/pkg/reconciler/testing/objects_channel.go
  control-plane/pkg/reconciler/testing/objects_common.go
  control-plane/pkg/reconciler/trigger/trigger_test.go
Labels: cla: yes, approved, lgtm, size/L, area/control-plane

#1450 [release-0.26] Commit offsets at specified intervals (#1405)
  control-plane/pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
  data-plane/benchmarks/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/UnorderedOffsetManagerBenchmark.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/RecordDispatcherListener.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherImpl.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetManager.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OrderedOffsetManager.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/UnorderedOffsetManager.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleFactoryImpl.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/AbstractOffsetManagerTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetManagerTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OrderedOffsetManagerTest.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/UnorderedConsumerTest.java
  data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java
  test/config/chaos/chaosduck.yaml
  test/e2e-common.sh
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/knative.dev/pkg/hack/generate-knative.sh
Labels: cla: yes, approved, lgtm, size/XL, area/data-plane, area/control-plane, area/test

#1451 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: cla: yes, approved, lgtm, size/S, area/test

#1456 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: cla: yes, approved, lgtm, size/L

#1431 Receiver handles ingress probes
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticle.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/handler/ControlPlaneProbeRequestUtil.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/handler/MethodNotAllowedHandler.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticleTest.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/handler/ProbeRequestUtilTest.java
Labels: cla: yes, approved, lgtm, size/L, area/data-plane

#1461 Adding just the source CRD
  control-plane/config/100-source/100-kafka-source.yaml
  third_party/eventing-kafka-latest/source-crd.yaml
Labels: cla: yes, approved, size/M, lgtm, area/control-plane

#1462 [main] Update actions
  .github/workflows/knative-verify.yaml
Labels: cla: yes, approved, size/XS, lgtm, area/test

#1438 Set KafkaChannel delivery order to ordered by default
  control-plane/pkg/reconciler/channel/channel.go
Labels: cla: yes, approved, size/XS, lgtm, area/control-plane

#1463 Commit offset on consumer close
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/AsyncCloseable.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/RecordDispatcherListener.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherImpl.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/BaseConsumerVerticle.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetManager.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OrderedConsumerVerticle.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/AbstractOffsetManagerTest.java
Labels: cla: yes, approved, size/M, lgtm, area/data-plane, kind/bug

#1470 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/request.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/S

#1469 Add KafkaSource condition for Sink resolved
  control-plane/pkg/reconciler/base/receiver_condition_set.go
  control-plane/pkg/reconciler/source/source.go
  control-plane/pkg/reconciler/source/source_test.go
  control-plane/pkg/reconciler/testing/objects_source.go
Labels: cla: yes, approved, size/M, lgtm, area/control-plane

#1475 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: cla: yes, approved, lgtm, size/L

#1478 [release-0.26] Commit offset on consumer close (#1463)
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/AsyncCloseable.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/RecordDispatcherListener.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherImpl.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/BaseConsumerVerticle.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetManager.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OrderedConsumerVerticle.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/AbstractOffsetManagerTest.java
Labels: cla: yes, approved, size/M, lgtm, area/data-plane

#1464 [Automated] Update eventing-kafka-broker-eventing-kafka nightly
  third_party/eventing-kafka-latest/channel-crds.yaml
  third_party/eventing-kafka-latest/source-crd.yaml
Labels: cla: yes, approved, size/XS, lgtm

#1474 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/eventing/test/lib/duck/resource_getters.go
  vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
  vendor/knative.dev/reconciler-test/pkg/manifest/installer.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/L

#1487 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: cla: yes, approved, lgtm, size/L

#1488 [Automated] Update eventing-kafka-broker-eventing-kafka nightly
  third_party/eventing-kafka-latest/channel-crds.yaml
  third_party/eventing-kafka-latest/source-crd.yaml
Labels: cla: yes, approved, size/XS, lgtm

#1485 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/.gitignore
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/knative.dev/eventing-kafka/pkg/common/client/config.go
  vendor/knative.dev/eventing-kafka/pkg/common/client/yaml.go
  vendor/knative.dev/eventing-kafka/pkg/common/kafka/sarama/sarama.go
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/XXL

#1492 [Automated] Update eventing-kafka-broker-eventing-kafka nightly
  third_party/eventing-kafka-latest/channel-crds.yaml
  third_party/eventing-kafka-latest/source-crd.yaml
Labels: cla: yes, approved, size/XS, lgtm

#1486 Add Broker Delete and Recreated test
  test/e2e_new/broker_test.go
  test/e2e_new/features/broker_deleted_recreated.go
  test/e2e_new/features/featuressteps/broker.go
  third_party/VENDOR-LICENSE/github.com/cloudevents/conformance/pkg/event/LICENSE
  third_party/VENDOR-LICENSE/knative.dev/reconciler-test/LICENSE
Labels: cla: yes, approved, lgtm, size/L, area/test

#1459 NT: We are testing the v1, renaming to proper name
  test/e2e/conformance/data_plane_conformance_test.go
Labels: cla: yes, approved, size/XS, lgtm, area/control-plane, area/test

#1494 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/modules.txt
Labels: cla: yes, approved, size/M, lgtm

#1497 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: cla: yes, approved, lgtm, size/L

#1460 Properly handle events without the `data` field
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherImpl.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/InvalidCloudEventInterceptor.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/KafkaConsumerRecordUtils.java
  data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java
Labels: cla: yes, approved, lgtm, size/L, area/data-plane, kind/bug

#1501 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, size/XS, lgtm

#1502 [release-0.26] Properly handle events without the `data` field (#1460)
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherImpl.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/KafkaConsumerRecordUtils.java
  data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java
Labels: cla: yes, approved, lgtm, size/L, area/data-plane, kind/bug

#1504 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/pkg/test/spoof/error_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: cla: yes, approved, size/M, lgtm

#1496 Using a CONST for the default delivery order of events
  control-plane/pkg/reconciler/channel/channel.go
Labels: cla: yes, approved, size/XS, lgtm, area/control-plane

#1505 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing-kafka/test/e2e/helpers/kafka_helper.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/comment_parser.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/reconciler/filter.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/L

#1507 [Automated] Update eventing-kafka-broker-eventing-kafka nightly
  third_party/eventing-kafka-latest/channel-crds.yaml
  third_party/eventing-kafka-latest/source-crd.yaml
Labels: cla: yes, approved, size/XS, lgtm

#1506 Fix flaky tracing test
  test/e2e_new/tracing_test.go
Labels: cla: yes, approved, size/XS, lgtm, area/test

#1514 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/conformance/helpers/broker_control_plane_test_helper.go
  vendor/modules.txt
Labels: cla: yes, approved, size/M, lgtm

#1523 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  vendor/knative.dev/pkg/kmap/lookup.go
  vendor/knative.dev/pkg/kmap/map.go
  vendor/knative.dev/pkg/kmeta/map.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/L

#1495 Probe resource ingress for readiness
  control-plane/config/200-controller/500-controller.yaml
  control-plane/pkg/config/env_config.go
  control-plane/pkg/prober/async_prober.go
  control-plane/pkg/prober/async_prober_test.go
  control-plane/pkg/prober/cache.go
  control-plane/pkg/prober/prober.go
  control-plane/pkg/prober/prober_test.go
  control-plane/pkg/prober/probertesting/mock_prober.go
  control-plane/pkg/prober/probertesting/mock_prober_test.go
  control-plane/pkg/receiver/address.go
  control-plane/pkg/reconciler/base/receiver_condition_set.go
  control-plane/pkg/reconciler/base/reconciler.go
  control-plane/pkg/reconciler/broker/broker.go
  control-plane/pkg/reconciler/broker/broker_test.go
  control-plane/pkg/reconciler/broker/controller.go
  control-plane/pkg/reconciler/broker/controller_test.go
  control-plane/pkg/reconciler/channel/channel.go
  control-plane/pkg/reconciler/channel/channel_test.go
  control-plane/pkg/reconciler/channel/controller.go
  control-plane/pkg/reconciler/channel/controller_test.go
  control-plane/pkg/reconciler/sink/controller.go
  control-plane/pkg/reconciler/sink/controller_test.go
  control-plane/pkg/reconciler/sink/kafka_sink.go
  control-plane/pkg/reconciler/sink/kafka_sink_test.go
  control-plane/pkg/reconciler/source/source.go
  control-plane/pkg/reconciler/testing/objects_broker.go
  control-plane/pkg/reconciler/testing/objects_common.go
  go.mod
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/XXL, kind/enhancement, area/control-plane

#1529 Add upgrade test script placeholder
  test/e2e-upgrade-tests.sh
Labels: cla: yes, approved, size/XS, lgtm, area/test

#1477 Kafka channel reconciler tests - except auth cases
  control-plane/pkg/reconciler/base/reconciler.go
  control-plane/pkg/reconciler/channel/channel_test.go
  control-plane/pkg/reconciler/testing/objects_broker.go
  control-plane/pkg/reconciler/testing/objects_channel.go
  control-plane/pkg/reconciler/testing/objects_common.go
Labels: cla: yes, approved, lgtm, size/XL, area/control-plane

#1524 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: cla: yes, approved, lgtm, size/L

#1525 [Automated] Update eventing-kafka-broker-eventing-kafka nightly
  third_party/eventing-kafka-latest/channel-crds.yaml
  third_party/eventing-kafka-latest/source-crd.yaml
Labels: cla: yes, approved, size/XS, lgtm

#1536 Using k8s 1.22.2 version
  .github/workflows/kind-e2e.yaml
Labels: cla: yes, approved, size/XS, lgtm, area/test

#1528 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing-kafka/test/e2e/helpers/kafka_helper.go
  vendor/knative.dev/eventing-kafka/test/e2e/helpers/kafka_source_test_helper.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/delivery_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/knative.dev/eventing/pkg/kncloudevents/retries.go
  vendor/knative.dev/eventing/pkg/utils/headers.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_test_helper.go
  vendor/knative.dev/eventing/test/lib/operation.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/metrics/config.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/L

#1538 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: cla: yes, approved, lgtm, size/L

#1539 [Automated] Update eventing-kafka-broker-eventing-kafka nightly
  third_party/eventing-kafka-latest/channel-crds.yaml
  third_party/eventing-kafka-latest/source-crd.yaml
Labels: cla: yes, approved, size/XS, lgtm

#1544 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: cla: yes, approved, lgtm, size/L

#1546 add b3 propagator for tracing
  data-plane/THIRD-PARTY.txt
  data-plane/core/pom.xml
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/tracing/TracingConfig.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/tracing/TracingConfigTest.java
  data-plane/pom.xml
Labels: cla: yes, approved, lgtm, size/L, ok-to-test, area/data-plane

#1549 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: cla: yes, approved, size/XS, lgtm, area/test

#1547 [Automated] Update eventing-kafka-broker-eventing-kafka nightly
  third_party/eventing-kafka-latest/channel-crds.yaml
  third_party/eventing-kafka-latest/source-crd.yaml
Labels: cla: yes, approved, size/XS, lgtm

#1555 Remove broker.spec.config defaulting magic
  control-plane/cmd/kafka-controller/main.go
  control-plane/cmd/webhook-kafka/main.go
  control-plane/config/200-webhook/100-webhook-cluster-role.yaml
  control-plane/pkg/apis/eventing/v1/broker_validation.go
  control-plane/pkg/apis/eventing/v1/broker_validation_test.go
  control-plane/pkg/reconciler/broker/broker.go
  control-plane/pkg/reconciler/broker/broker_test.go
  control-plane/pkg/reconciler/broker/controller.go
  control-plane/pkg/reconciler/broker/controller_test.go
  control-plane/pkg/reconciler/testing/objects_broker.go
Labels: cla: yes, approved, lgtm, size/XL, area/control-plane

#1545 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/modules.txt
Labels: cla: yes, approved, size/M, lgtm
