Repository knative-extensions/eventing-kafka-broker, pull requests merged in 2021-09, with the labels that each got.

#1195 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: cla: yes, approved, lgtm, size/L

#1196 [release-0.25] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/L

#1199 drop scheduled actions these fill up the job queue causing delays
  .github/workflows/kind-e2e.yaml
Labels: cla: yes, approved, size/XS, lgtm, area/test

#1200 Separate security config function
  control-plane/pkg/reconciler/broker/broker.go
  control-plane/pkg/reconciler/sink/kafka_sink.go
  control-plane/pkg/security/config.go
  control-plane/pkg/security/config_test.go
Labels: cla: yes, approved, size/M, lgtm, area/control-plane

#1201 Channel control plane to use secret
  control-plane/pkg/reconciler/broker/broker.go
  control-plane/pkg/reconciler/channel/channel.go
  control-plane/pkg/reconciler/sink/kafka_sink.go
  control-plane/pkg/security/config.go
  control-plane/pkg/security/config_test.go
Labels: cla: yes, approved, size/M, lgtm, area/control-plane

#1206 [release-0.24] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_validation.go
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/L

#1208 Channel reconciler to track configmap and secret
  control-plane/pkg/reconciler/channel/channel.go
  control-plane/pkg/reconciler/channel/controller.go
Labels: cla: yes, approved, lgtm, size/S, area/control-plane

#1203 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-kafka-latest/channel-crds.yaml
Labels: cla: yes, approved, size/XS, lgtm

#1202 Using the xdg-go instead of discontinued xdg
  control-plane/pkg/security/scram.go
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/xdg/scram/LICENSE
  third_party/VENDOR-LICENSE/github.com/xdg/stringprep/LICENSE
  vendor/github.com/xdg/scram/.gitignore
  vendor/github.com/xdg/scram/.travis.yml
  vendor/github.com/xdg/scram/LICENSE
  vendor/github.com/xdg/scram/README.md
  vendor/github.com/xdg/scram/client.go
  vendor/github.com/xdg/scram/client_conv.go
  vendor/github.com/xdg/scram/common.go
  vendor/github.com/xdg/scram/doc.go
  vendor/github.com/xdg/scram/parse.go
  vendor/github.com/xdg/scram/scram.go
  vendor/github.com/xdg/scram/server.go
  vendor/github.com/xdg/scram/server_conv.go
  vendor/github.com/xdg/stringprep/.gitignore
  vendor/github.com/xdg/stringprep/.travis.yml
  vendor/github.com/xdg/stringprep/LICENSE
  vendor/github.com/xdg/stringprep/README.md
  vendor/github.com/xdg/stringprep/bidi.go
  vendor/github.com/xdg/stringprep/doc.go
  vendor/github.com/xdg/stringprep/error.go
  vendor/github.com/xdg/stringprep/map.go
  vendor/github.com/xdg/stringprep/profile.go
  vendor/github.com/xdg/stringprep/saslprep.go
  vendor/github.com/xdg/stringprep/set.go
  vendor/github.com/xdg/stringprep/tables.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/XXL, area/control-plane

#1209 Channel to use spec details for topic creation
  control-plane/pkg/reconciler/channel/channel.go
Labels: cla: yes, approved, lgtm, size/S, area/control-plane

#1210 Handle channel deletion
  control-plane/pkg/reconciler/channel/channel.go
Labels: cla: yes, approved, lgtm, size/L, area/control-plane

#1207 [release-0.23] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_validation.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_spec_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_status_subscriber_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_status_test_helper.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/L

#1191 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/reconciler/leader.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/L

#1212 Use retention from spec for topic creation
  control-plane/pkg/reconciler/channel/channel.go
Labels: cla: yes, approved, lgtm, size/S, area/control-plane

#1214 Make Channel status.address optional
  third_party/eventing-kafka-latest/channel-crds.yaml
Labels: cla: yes, approved, lgtm, size/S, area/control-plane

#1215 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/S

#1218 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-kafka-latest/channel-crds.yaml
Labels: cla: yes, approved, lgtm, size/S

#1217 Improve test coverage for security.config/TestSecret
  control-plane/pkg/reconciler/sink/auth_provider.go
  control-plane/pkg/security/config.go
  control-plane/pkg/security/config_test.go
Labels: cla: yes, approved, size/M, lgtm, area/data-plane, area/control-plane, area/test

#1221 Inline config.Env in channel reconciler
  control-plane/cmd/webhook-kafka/main.go
  control-plane/pkg/reconciler/channel/channel.go
  control-plane/pkg/reconciler/channel/controller.go
Labels: cla: yes, approved, lgtm, size/S, area/control-plane

#1223 Register event listeners in KafkaChannel controller and register custom condition set
  control-plane/pkg/reconciler/channel/controller.go
Labels: cla: yes, approved, lgtm, size/S, area/control-plane

#1222 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-kafka-latest/channel-crds.yaml
Labels: cla: yes, approved, size/XS, lgtm

#1228 [release-0.22] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_conversion.go
  vendor/knative.dev/pkg/webhook/json/decode.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/L

#1219 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing-kafka/pkg/apis/duck/v1alpha1/placement_types.go
  vendor/knative.dev/eventing-kafka/pkg/apis/sources/config/doc.go
  vendor/knative.dev/eventing-kafka/pkg/apis/sources/config/kafka_defaults.go
  vendor/knative.dev/eventing-kafka/pkg/apis/sources/config/store.go
  vendor/knative.dev/eventing-kafka/pkg/apis/sources/v1beta1/kafka_defaults.go
  vendor/knative.dev/eventing-kafka/pkg/apis/sources/v1beta1/kafka_scheduling.go
  vendor/knative.dev/eventing-kafka/pkg/common/constants/constants.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_defaults.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_types.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_validation.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/response_checks.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/XL

#1229 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-kafka-latest/channel-crds.yaml
Labels: cla: yes, approved, size/XS, lgtm

#1231 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/state.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/trigger/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/trigger/state.go
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/L

#1232 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-kafka-latest/channel-crds.yaml
Labels: cla: yes, approved, size/XS, lgtm

#1220 Bump setup-java to v2 in GH action
  .github/workflows/knative-java-test.yaml
Labels: cla: yes, approved, lgtm, size/S, area/test

#1237 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing-kafka/pkg/client/injection/reconciler/messaging/v1beta1/kafkachannel/reconciler.go
  vendor/knative.dev/eventing-kafka/pkg/client/injection/reconciler/messaging/v1beta1/kafkachannel/state.go
  vendor/modules.txt
Labels: cla: yes, approved, size/M, lgtm

#1236 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-kafka-latest/channel-crds.yaml
Labels: cla: yes, approved, size/XS, lgtm

#1242 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, size/XS, lgtm

#1241 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-kafka-latest/channel-crds.yaml
Labels: cla: yes, approved, size/XS, lgtm

#1246 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: cla: yes, approved, lgtm, size/S, area/test

#1245 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/S

#1250 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: cla: yes, approved, size/XS, lgtm, area/test

#1249 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-kafka-latest/channel-crds.yaml
Labels: cla: yes, approved, size/XS, lgtm

#1243 Drop Kubernetes 1.19 and add 1.22
  .github/workflows/kind-e2e.yaml
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-v0.22.1/eventing-core.yaml
  third_party/eventing-v0.22.1/eventing-crds.yaml
  third_party/eventing-v0.23.0/eventing-core.yaml
  third_party/eventing-v0.23.0/eventing-crds.yaml
Labels: cla: yes, approved, lgtm, size/XXL, area/test, kind/removal

#1240 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing-kafka/pkg/apis/kafka/v1alpha1/reset_offset_validation.go
  vendor/knative.dev/eventing-kafka/pkg/apis/messaging/v1beta1/kafka_channel_validation.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/apiserver_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/container_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/sinkbinding_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_validation.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/trigger/reconciler.go
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/L

#1256 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: cla: yes, approved, lgtm, size/S, area/test

#1257 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/L

#1258 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/S

#1261 Workaround Prow CI failures with iptables change
  test/e2e-tests.sh
Labels: cla: yes, approved, size/XS, lgtm, area/test

#1254 Add namespace to referenced addressable before resolving destination
  control-plane/pkg/core/config/utils.go
  control-plane/pkg/reconciler/broker/broker_test.go
  control-plane/pkg/reconciler/testing/objects_broker.go
  control-plane/pkg/reconciler/testing/objects_common.go
Labels: cla: yes, approved, lgtm, size/L, area/control-plane

#1273 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/rbac/100-sa.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/rbac/101-rbac.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/rbac/rbac.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/modules.txt
Labels: cla: yes, approved, size/M, lgtm

#1271 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-kafka-latest/channel-crds.yaml
Labels: cla: yes, approved, size/XS, lgtm
