Repository knative-extensions/eventing-kafka-broker, pull requests merged in 2021-12, with the labels that each got.

#1557 Use Java 17 for GH actions
  .github/workflows/knative-java-test.yaml
Labels: cla: yes, approved, size/XS, lgtm, area/test

#1558 Channel to use new configmap format for bootstrap servers
  control-plane/config/100-channel/100-kafka-channel-configmap.yaml
  control-plane/config/200-controller/500-controller.yaml
  control-plane/pkg/reconciler/channel/channel.go
  control-plane/pkg/reconciler/channel/channel_test.go
  control-plane/pkg/reconciler/kafka/topic.go
  control-plane/pkg/reconciler/testing/objects_channel.go
Labels: cla: yes, approved, lgtm, size/L, area/control-plane

#1559 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: cla: yes, approved, lgtm, size/L

#1556 [Automated] Update eventing-kafka-broker-eventing-kafka nightly
  third_party/eventing-kafka-latest/channel-crds.yaml
  third_party/eventing-kafka-latest/source-crd.yaml
Labels: cla: yes, approved, size/XS, lgtm

#1561 Kafka Ch reconciler tests with auth
  control-plane/pkg/reconciler/channel/channel.go
  control-plane/pkg/reconciler/channel/channel_test.go
  control-plane/pkg/reconciler/channel/testdata/ca.crt
  control-plane/pkg/reconciler/channel/testdata/user.crt
  control-plane/pkg/reconciler/channel/testdata/user.key
Labels: cla: yes, approved, lgtm, size/L, area/control-plane

#1563 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, size/XS, lgtm

#1564 [Automated] Update eventing-kafka-broker-eventing-kafka nightly
  third_party/eventing-kafka-latest/channel-crds.yaml
  third_party/eventing-kafka-latest/source-crd.yaml
Labels: cla: yes, approved, size/XS, lgtm

#1565 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: cla: yes, approved, lgtm, size/L

#1567 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, size/XS, lgtm

#1568 [Automated] Update eventing-kafka-broker-eventing-kafka nightly
  third_party/eventing-kafka-latest/channel-crds.yaml
  third_party/eventing-kafka-latest/source-crd.yaml
Labels: cla: yes, approved, size/XS, lgtm

#1574 Handle non-retryable HTTP status codes as reported in the spec
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSender.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSenderTest.java
Labels: approved, size/M, lgtm, area/data-plane

#1577 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1576 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing-kafka/test/e2e/helpers/kafka_source_test_helper.go
  vendor/knative.dev/eventing/test/rekt/resources/delivery/delivery.go
  vendor/modules.txt
Labels: approved, size/M, lgtm

#1581 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1583 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/XL

#1584 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1578 [Automated] Update eventing-kafka-broker-eventing-kafka nightly
  third_party/eventing-kafka-latest/channel-crds.yaml
  third_party/eventing-kafka-latest/source-crd.yaml
Labels: approved, size/XS, lgtm

#1582 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#1587 [Automated] Update eventing-kafka-broker-eventing-kafka nightly
  third_party/eventing-kafka-latest/channel-crds.yaml
  third_party/eventing-kafka-latest/source-crd.yaml
Labels: approved, size/XS, lgtm

#1591 [main] Use Broker's own configmap for Kafka
  test/pkg/broker/broker.go
  test/pkg/testing/run.go
Labels: approved, size/M, lgtm, area/test

#1594 [release-0.26] Use Broker's own configmap for Kafka
  test/pkg/broker/broker.go
  test/pkg/testing/run.go
  third_party/VENDOR-LICENSE/github.com/nxadm/tail/ratelimiter/Licence
Labels: approved, size/M, lgtm, area/control-plane, area/test

#1569 Trigger Reconciler for ConsumerGroup scaling
  control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_types.go
  control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_validation_test.go
  control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_types.go
  control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/filter_types.go
  control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/zz_generated.deepcopy.go
  control-plane/pkg/reconciler/testing/factory.go
  control-plane/pkg/reconciler/testing/listers.go
  control-plane/pkg/reconciler/testing/objects_common.go
  control-plane/pkg/reconciler/trigger/trigger.go
  control-plane/pkg/reconciler/trigger/trigger_test.go
  control-plane/pkg/reconciler/trigger/v2/controllerv2.go
  control-plane/pkg/reconciler/trigger/v2/controllerv2_test.go
  control-plane/pkg/reconciler/trigger/v2/triggerv2.go
Labels: cla: yes, approved, lgtm, size/L, area/control-plane

#1588 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1589 Fix deleting the Broker ConfigMap prevents the Broker from being finalized
  control-plane/pkg/reconciler/broker/broker.go
  control-plane/pkg/reconciler/broker/broker_test.go
  control-plane/pkg/reconciler/testing/objects_broker.go
  test/e2e_new/broker_test.go
  test/e2e_new/features/broker_deleted_recreated.go
  test/e2e_new/features/featuressteps/broker.go
  test/e2e_new/resources/configmap/copy.go
Labels: approved, lgtm, size/L, area/control-plane, area/test

#1599 [Automated] Update eventing-kafka-broker-eventing-kafka nightly
  third_party/eventing-kafka-latest/channel-crds.yaml
  third_party/eventing-kafka-latest/source-crd.yaml
Labels: approved, size/XS, lgtm

#1603 manual dep updates
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/monitoring/monitoring.go
  vendor/knative.dev/reconciler-test/pkg/environment/interfaces.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/knative.dev/reconciler-test/pkg/milestone/emitter_composite.go
  vendor/knative.dev/reconciler-test/pkg/milestone/emitter_log.go
  vendor/knative.dev/reconciler-test/pkg/milestone/factory.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1607 Align to 1.1... manually, again
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/monitoring/monitoring.go
  vendor/knative.dev/reconciler-test/pkg/environment/interfaces.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/knative.dev/reconciler-test/pkg/milestone/emitter_composite.go
  vendor/knative.dev/reconciler-test/pkg/milestone/emitter_log.go
  vendor/knative.dev/reconciler-test/pkg/milestone/factory.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1613 using sharedmain.MainNamed for all controllers
  control-plane/cmd/kafka-controller/main.go
Labels: approved, size/M, lgtm, area/control-plane

#1615 Add a ConsumerGroup filter function based on owner refs
  control-plane/pkg/reconciler/consumergroup/filter.go
  control-plane/pkg/reconciler/consumergroup/filter_test.go
  control-plane/pkg/reconciler/trigger/v2/controllerv2.go
Labels: approved, lgtm, size/L, area/control-plane

#1616 Add promote filter function to Broker and Trigger reconciler
  control-plane/pkg/reconciler/broker/controller.go
  control-plane/pkg/reconciler/trigger/controller.go
  control-plane/pkg/reconciler/trigger/v2/controllerv2.go
Labels: approved, size/XS, lgtm, area/control-plane

#1625 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#1621 Add promote filter function to Broker and Trigger reconciler (#1616)
  control-plane/pkg/reconciler/broker/controller.go
  control-plane/pkg/reconciler/trigger/controller.go
Labels: approved, size/XS, lgtm, area/control-plane

#1629 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#1640 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, size/XS, lgtm, area/test

#1623 [Automated] Update eventing-kafka-broker-eventing-kafka nightly
  third_party/eventing-kafka-latest/channel-crds.yaml
  third_party/eventing-kafka-latest/source-crd.yaml
Labels: approved, size/XS, lgtm

#1636 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#1637 Add CRD manifests for consumers scheduling and scaling
  control-plane/config/100-kafka-internal/100-consumer.yaml
  control-plane/config/100-kafka-internal/100-consumergroup.yaml
Labels: approved, lgtm, size/L, area/control-plane

#1653 [release-0.26] Add promote filter function to Broker and Trigger reconciler
  control-plane/pkg/reconciler/broker/controller.go
  control-plane/pkg/reconciler/trigger/controller.go
Labels: approved, size/XS, lgtm, area/control-plane
