Repository knative-extensions/eventing-kafka-broker, pull requests merged in 2021-04, with the labels that each got.

#779 Stop testing on k8s version 1.17
  .github/workflows/kind-e2e.yaml
Labels: approved, area/test, cla: yes, lgtm, size/XS

#782 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#783 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#788 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/XL

#789 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#796 Bump fabric8 kube client and junit
  data-plane/THIRD-PARTY.txt
  data-plane/pom.xml
Labels: approved, area/data-plane, cla: yes, lgtm, size/M

#801 [data-plane]: Bump license-maven-plugin in /data-plane
  data-plane/pom.xml
Labels: approved, area/data-plane, cla: yes, lgtm, size/XS

#802 [data-plane]: Bump protobuf.version from 3.15.3 to 3.15.8 in /data-plane
  .github/dependabot.yml
  data-plane/pom.xml
Labels: approved, area/data-plane, cla: yes, lgtm, size/XS

#795 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#800 [data-plane]: Bump vertx.version from 4.0.2 to 4.0.3 in /data-plane
  data-plane/pom.xml
Labels: approved, area/data-plane, cla: yes, lgtm, size/XS

#799 [data-plane]: Bump micrometer-bom from 1.6.4 to 1.6.6 in /data-plane
  data-plane/pom.xml
Labels: approved, area/data-plane, cla: yes, lgtm, size/XS

#804 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/cloudevents/sdk-go/v2/event/event_unmarshal.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v03_reader.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v1.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v1_reader.go
  vendor/github.com/cloudevents/sdk-go/v2/event/extensions.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/prober.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#811 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/trigger.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#810 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#812 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#814 Fix out of bounds in unordered offset manager
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/UnorderedOffsetManager.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/UnorderedOffsetManagerTest.java
Labels: approved, area/data-plane, cla: yes, lgtm, size/S

#819 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#817 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#821 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/trigger/reconciler.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/M

#824 acks=all
  data-plane/config/broker/100-config-kafka-broker-data-plane.yaml
Labels: approved, area/data-plane, cla: yes, lgtm, size/XS

#828 Fix kube auth provider test
  data-plane/THIRD-PARTY.txt
  data-plane/core/pom.xml
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/security/KubernetesAuthProviderTest.java
Labels: approved, area/data-plane, cla: yes, lgtm, size/L

#827 acks=all
  data-plane/config/sink/100-config-kafka-sink-data-plane.yaml
Labels: approved, area/data-plane, cla: yes, lgtm, size/XS

#825 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#822 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/feature/context.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/knative.dev/reconciler-test/pkg/manifest/installer.go
  vendor/knative.dev/reconciler-test/pkg/milestone/emitter.go
  vendor/knative.dev/reconciler-test/pkg/milestone/factory.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#830 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#837 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#836 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#829 Remove java Dockerfile to build
  data-plane/docker/test/Dockerfile
  hack/data-plane.sh
  test/presubmit-tests.sh
Labels: approved, area/data-plane, area/test, cla: yes, lgtm, size/M

#845 Logback test config
  data-plane/core/src/test/resources/logback.xml
  data-plane/dispatcher/src/test/resources/logback.xml
  data-plane/receiver/src/test/resources/logback.xml
  data-plane/tests/src/test/resources/logback.xml
Labels: approved, area/data-plane, cla: yes, lgtm, size/M

#840 Support SASL mechanism PLAIN
  control-plane/pkg/security/config.go
  data-plane/THIRD-PARTY.txt
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/CredentialsValidator.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/security/CredentialsValidatorTest.java
Labels: approved, area/control-plane, area/data-plane, cla: yes, lgtm, size/M

#848 Copy OWNERS_ALIASES from knative/community; fill in OWNERS files
  OWNERS
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/L

#842 [main] Upgrade to latest dependencies
  control-plane/pkg/client/injection/reconciler/eventing/v1alpha1/kafkasink/reconciler.go
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/trigger/reconciler.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/volatile_time.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/knative.dev/reconciler-test/pkg/environment/flags.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/modules.txt
Labels: approved, area/control-plane, cla: yes, lgtm, size/L

#851 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/XL

#847 Removed protobuf dockerfile and moved generate_proto.sh script
  control-plane/pkg/contract/contract.pb.go
  data-plane/contract/src/main/java/dev/knative/eventing/kafka/broker/contract/DataPlaneContract.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactoryTest.java
  hack/generate-proto.sh
  hack/update-codegen.sh
  proto/DEVELOPMENT.md
  proto/contract.proto
  proto/hack/generate_proto
Labels: approved, area/control-plane, area/data-plane, cla: yes, lgtm, size/XL

#855 fix: Allow SASLMechanism to equal "PLAIN"
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/KubernetesCredentials.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/security/KubernetesCredentialsTest.java
Labels: approved, area/data-plane, cla: yes, lgtm, size/S
