Repository knative-extensions/eventing-kafka-broker, pull requests merged in 2021-03, with the labels that each got.

#681 Pin eventing HEAD and upgrade dependencies
  control-plane/pkg/client/injection/reconciler/eventing/v1alpha1/kafkasink/controller.go
  control-plane/pkg/client/injection/reconciler/eventing/v1alpha1/kafkasink/reconciler.go
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/controller.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/trigger/controller.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/trigger/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1beta1/broker/controller.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1beta1/broker/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/metrics_worker.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/reconciler/testing/clock.go
  vendor/knative.dev/pkg/system/clock.go
  vendor/modules.txt
Labels: approved, area/control-plane, cla: yes, lgtm, size/L

#631 Improve SSL support
  control-plane/pkg/security/secret.go
  control-plane/pkg/security/secret_test.go
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/Credentials.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/CredentialsValidator.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/KafkaClientsAuth.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/KubernetesCredentials.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/PlaintextCredentials.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/security/CredentialsValidatorTest.java
Labels: approved, area/control-plane, area/data-plane, cla: yes, lgtm, size/L

#670 Add KafkaSink docs link to the readme
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#676 Add tests to base reconciler
  control-plane/pkg/reconciler/base/reconciler_test.go
Labels: approved, area/control-plane, cla: yes, lgtm, size/L

#677 Add more unit tests for Kafka reconciler package
  control-plane/pkg/reconciler/kafka/admin_test.go
  control-plane/pkg/reconciler/kafka/topic.go
  control-plane/pkg/reconciler/kafka/topic_test.go
Labels: approved, area/control-plane, cla: yes, lgtm, size/M

#669 Move reconcileKind method of Trigger reconciler
  control-plane/pkg/reconciler/trigger/trigger.go
Labels: approved, area/control-plane, cla: yes, kind/cleanup, lgtm, size/L

#690 Fixed codeowners file
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, size/XS

#693 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/informer/informed_watcher.go
  vendor/knative.dev/pkg/configmap/informer/synced_callback.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#633 Add tests for previous versions of Eventing
  .github/workflows/kind-e2e.yaml
  test/e2e-common.sh
  third_party/eventing-v0.18.6/eventing-core.yaml
  third_party/eventing-v0.18.6/eventing-crds.yaml
  third_party/eventing-v0.19.4/eventing-core.yaml
  third_party/eventing-v0.19.4/eventing-crds.yaml
  third_party/eventing-v0.20.1/eventing-core.yaml
  third_party/eventing-v0.20.1/eventing-crds.yaml
Labels: approved, area/test, cla: yes, lgtm, size/XXL

#691 Drop hack and test from CODEOWNERS
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, size/XS

#692 Upgrade sacura to include output improvements
  go.mod
  go.sum
  vendor/github.com/pierdipi/sacura/state.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#694 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#696 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#689 Added delivery guarantee to the egress contract
  control-plane/pkg/contract/contract.pb.go
  data-plane/contract/src/main/java/dev/knative/eventing/kafka/broker/contract/DataPlaneContract.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/DeliveryOrder.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/impl/UnorderedConsumerVerticle.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactory.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/consumer/DeliveryOrderTest.java
  proto/def/contract.proto
Labels: approved, area/control-plane, area/data-plane, cla: yes, lgtm, size/L

#700 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1beta1/expansion_generated.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/channelable_combined_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/channelable_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/doc.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/register.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/resource_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/subscribable_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/subscribable_types_conversion.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/listers.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1beta1/channelable.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1beta1/factory.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1beta1/listers.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_spec_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_status_subscriber_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_status_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_defaulter_test_helper.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#686 Add downloads badge
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#705 Fix profiler test runner
  data-plane/profiler/run.sh
Labels: approved, area/data-plane, cla: yes, lgtm, size/XS

#708 Fix race condition when installing Kafka in CI
  test/kafka/kafka_setup.sh
Labels: approved, area/test, cla: yes, lgtm, size/XS

#704 Add Maven cache in GH Actions
  .github/workflows/knative-java-test.yaml
  .github/workflows/knative-profile-data-plane.yaml
  data-plane/profiler/run.sh
Labels: approved, area/data-plane, area/test, cla: yes, lgtm, size/S

#709 Bump Go version to 1.15
  go.mod
Labels: approved, cla: yes, lgtm, size/XS

#717 [release-0.21] Fix OpenCircuitException: open circuit (#710)
  .github/workflows/knative-java-test.yaml
  .github/workflows/knative-profile-data-plane.yaml
  data-plane/THIRD-PARTY.txt
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/testing/CoreObjects.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactory.java
  test/config/sacura/101-broker.yaml
  test/config/sacura/200-config.yaml
Labels: approved, area/data-plane, area/test, cla: yes, lgtm, size/M

#718 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
Labels: approved, area/test, cla: yes, lgtm, size/XS

#721 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, area/test, cla: yes, lgtm, size/XS

#722 [Automated] Fix misspellings
  .github/workflows/knative-style.yaml
Labels: approved, area/test, cla: yes, lgtm, size/XS

#723 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, area/test, cla: yes, lgtm, size/XS

#724 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/client/injection/client/client.go
  vendor/knative.dev/eventing/pkg/client/injection/client/fake/fake.go
  vendor/knative.dev/eventing/test/rekt/resources/svc/service.go
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/test/README.md
  vendor/knative.dev/pkg/test/mako/sidecar.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/environment/namespace.go
  vendor/knative.dev/reconciler-test/pkg/environment/t.go
  vendor/knative.dev/reconciler-test/pkg/environment/timings.go
  vendor/knative.dev/reconciler-test/pkg/k8s/job.go
  vendor/knative.dev/reconciler-test/pkg/k8s/steps.go
  vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
  vendor/knative.dev/reconciler-test/pkg/manifest/installer.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#727 [Automated] Update actions
  .github/workflows/knative-security.yaml
Labels: approved, area/test, cla: yes, lgtm, size/XS

#728 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/golang.org/x/xerrors/LICENSE
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/errors_go113.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/errors_xerrors.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/github.com/google/gofuzz/.travis.yml
  vendor/github.com/google/gofuzz/CONTRIBUTING.md
  vendor/github.com/google/gofuzz/README.md
  vendor/github.com/google/gofuzz/bytesource/bytesource.go
  vendor/github.com/google/gofuzz/fuzz.go
  vendor/github.com/prometheus/common/model/time.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
  vendor/google.golang.org/grpc/credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go
  vendor/google.golang.org/grpc/encoding/proto/proto.go
  vendor/google.golang.org/grpc/regenerate.sh
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#726 Kind periodic actions every 6 hours
  .github/workflows/kind-e2e.yaml
Labels: approved, area/test, cla: yes, lgtm, size/XS

#735 Strict doesn't exist anymore https://github.com/google/ko/pull/281
  .github/workflows/kind-e2e.yaml
  hack/control-plane.sh
  hack/data-plane.sh
  test/e2e-common.sh
Labels: approved, area/test, cla: yes, lgtm, size/S

#734 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/gopkg.in/yaml.v2/.travis.yml
  vendor/gopkg.in/yaml.v2/apic.go
  vendor/gopkg.in/yaml.v2/go.mod
  vendor/gopkg.in/yaml.v2/yaml.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_types.go
  vendor/knative.dev/eventing/test/rekt/features/broker/control_plane.go
  vendor/knative.dev/eventing/test/rekt/resources/broker/broker.go
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#733 [Automated] Format Go code
  test/e2e_new/broker_test.go
Labels: approved, area/test, cla: yes, lgtm, size/XS

#739 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/rekt/features/broker/ingress.go
  vendor/knative.dev/eventing/test/rekt/features/broker/readyness.go
  vendor/knative.dev/eventing/test/rekt/features/broker/source_to_sink.go
  vendor/knative.dev/eventing/test/rekt/features/defaults.go
  vendor/knative.dev/eventing/test/rekt/resources/broker/broker.go
  vendor/knative.dev/eventing/test/rekt/resources/broker/broker.yaml
  vendor/knative.dev/eventing/test/rekt/resources/trigger/trigger.go
  vendor/knative.dev/reconciler-test/pkg/k8s/job.go
  vendor/knative.dev/reconciler-test/pkg/k8s/steps.go
  vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
  vendor/knative.dev/reconciler-test/pkg/manifest/installer.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#737 Fix data race - failed to send events during tests
  test/pkg/addressable/send.go
Labels: approved, area/test, cla: yes, lgtm, size/M

#738 Update Eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#745 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_defaults.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/subscription_defaults.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/subscription_validation.go
  vendor/knative.dev/eventing/test/rekt/features/broker/control_plane.go
  vendor/knative.dev/eventing/test/rekt/features/broker/data_plane.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#747 Short circuit trigger reconciliation when broker not ready
  control-plane/pkg/reconciler/trigger/trigger.go
  control-plane/pkg/reconciler/trigger/trigger_test.go
Labels: approved, area/control-plane, cla: yes, lgtm, size/M

#701 Implemented delivery order label
  control-plane/pkg/contract/contract.pb.go
  control-plane/pkg/reconciler/trigger/trigger.go
  control-plane/pkg/reconciler/trigger/trigger_test.go
  data-plane/contract/src/main/java/dev/knative/eventing/kafka/broker/contract/DataPlaneContract.java
  go.sum
  hack/tools.go
  proto/def/contract.proto
  test/e2e_new/broker/broker.go
  test/e2e_new/broker/broker.yaml
  test/e2e_new/broker_test.go
  test/e2e_new/ordered_test.go
  test/e2e_new/single_partition_config/install.go
  test/e2e_new/single_partition_config/single_partition_config.yaml
  test/e2e_new/trigger/trigger.go
  test/e2e_new/trigger/trigger.yaml
  test/e2e_new/utils/log_cm.go
  third_party/VENDOR-LICENSE/knative.dev/reconciler-test/pkg/LICENSE
  vendor/knative.dev/eventing/test/rekt/features/broker/control_plane.go
  vendor/knative.dev/eventing/test/rekt/features/broker/data_plane.go
  vendor/knative.dev/eventing/test/rekt/features/broker/ingress.go
  vendor/knative.dev/eventing/test/rekt/features/broker/readyness.go
  vendor/knative.dev/eventing/test/rekt/features/broker/source_to_sink.go
  vendor/knative.dev/eventing/test/rekt/features/knconf/control_plane.go
  vendor/knative.dev/eventing/test/rekt/resources/flaker/flaker.go
  vendor/knative.dev/eventing/test/rekt/resources/flaker/flaker.yaml
  vendor/knative.dev/eventing/test/test_images/event-flaker/main.go
  vendor/modules.txt
Labels: approved, area/control-plane, area/data-plane, area/test, cla: yes, kind/enhancement, lgtm, size/XXL

#752 [Automated] Format Go code
  test/e2e_new/ordered_test.go
Labels: approved, area/test, cla: yes, lgtm, size/XS

#751 Add producer interceptor PartitionKeyExtensionInterceptor
  data-plane/config/broker/100-config-kafka-broker-data-plane.yaml
  data-plane/config/sink/100-config-kafka-sink-data-plane.yaml
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/Main.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/http/HttpConsumerVerticleFactory.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/Main.java
Labels: approved, area/data-plane, cla: yes, kind/bug, lgtm, size/S

#753 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/eventshub/options.go
  vendor/knative.dev/reconciler-test/pkg/test_images/eventshub/dropevents/receiver.go
  vendor/knative.dev/reconciler-test/pkg/test_images/eventshub/event_info.go
  vendor/knative.dev/reconciler-test/pkg/test_images/eventshub/receiver/receiver.go
  vendor/knative.dev/reconciler-test/pkg/test_images/eventshub/sender/sender.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#756 Add another test that checks ordering per keys
  test/e2e_new/multiple_partition_config/install.go
  test/e2e_new/multiple_partition_config/multiple_partition_config.yaml
  test/e2e_new/ordered_test.go
Labels: approved, area/test, cla: yes, lgtm, size/L

#758 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/knative.dev/pkg/tracing/zipkin.go
  vendor/knative.dev/reconciler-test/pkg/environment/execution.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#760 [main] Upgrade to latest dependencies
  control-plane/pkg/contract/contract.pb.go
  go.mod
  go.sum
  vendor/github.com/golang/protobuf/ptypes/empty/empty.pb.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_addressable_resolver_cluster_role_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_channelable_manipulator_cluster_role_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_crd_metadata_test_helper.go
  vendor/knative.dev/eventing/test/conformance/helpers/rbac.go
  vendor/modules.txt
Labels: approved, area/control-plane, cla: yes, lgtm, size/S

#762 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/XL

#767 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/reconciler-test/pkg/test_images/eventshub/event_info.go
  vendor/knative.dev/reconciler-test/pkg/test_images/eventshub/sender/sender.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#766 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, area/test, cla: yes, lgtm, size/XS

#772 [main] Upgrade to latest dependencies
  control-plane/pkg/client/injection/reconciler/eventing/v1alpha1/kafkasink/controller.go
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/controller.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/trigger/controller.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1beta1/broker/controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/reconciler-test/pkg/environment/execution.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/modules.txt
Labels: approved, area/control-plane, cla: yes, lgtm, size/M

#771 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#775 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#776 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L
