Repository knative-extensions/eventing-kafka-broker, pull requests merged in 2021-07, with the labels that each got.

#1069 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/logging/warning_handler.go
  vendor/knative.dev/pkg/ptr/value.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1062 File watcher thread
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/file/FileWatcher.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/file/FileWatcherTest.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/Main.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/UnorderedConsumerTest.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/Main.java
Labels: approved, area/data-plane, cla: yes, lgtm, size/L

#1063 Refactor dispatcher main
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/metrics/Metrics.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleFactoryImpl.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/Main.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/integration/ConsumerVerticleFactoryImplMock.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleFactoryImplTest.java
  data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java
Labels: approved, area/data-plane, cla: yes, lgtm, size/L

#1068 [main] Update actions
  .github/workflows/knative-stale.yaml
Labels: approved, area/test, cla: yes, lgtm, size/XS

#1079 KafkaSink test resource
  test/e2e_new/resources/kafkasink/kafkasink.go
  test/e2e_new/resources/kafkasink/kafkasink.yaml
  test/e2e_new/resources/kafkasink/kafkasink_test.go
Labels: approved, area/test, cla: yes, lgtm, size/L

#1080 [main] Format Go code
  test/e2e_new/resources/kafkasink/kafkasink_test.go
Labels: approved, area/test, cla: yes, lgtm, size/XS

#1081 [main] Update actions
  .github/workflows/knative-go-test.yaml
Labels: approved, area/test, cla: yes, lgtm, size/XS

#1074 Bump vertx and opentel
  data-plane/THIRD-PARTY.txt
  data-plane/pom.xml
Labels: approved, area/data-plane, cla: yes, lgtm, size/M

#1078 Port Broker Delete CM test to e2e_new
  test/e2e-tests.sh
  test/e2e/delete_cm_test.go
  test/e2e_new/broker_delete_config_map_test.go
  test/e2e_new/main_test.go
  test/e2e_new/resources/configmap/delete.go
  test/e2e_new/resources/configmap/log.go
  test/e2e_new/resources/configmap/wait.go
Labels: approved, area/test, cla: yes, lgtm, size/L

#1075 Removed logstash main hack
  data-plane/dispatcher/pom.xml
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/Main.java
  data-plane/receiver/pom.xml
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/Main.java
Labels: approved, area/data-plane, cla: yes, lgtm, size/S

#1082 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#1089 Fix boilerplate date
  control-plane/pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
  control-plane/pkg/client/clientset/versioned/clientset.go
  control-plane/pkg/client/clientset/versioned/doc.go
  control-plane/pkg/client/clientset/versioned/fake/clientset_generated.go
  control-plane/pkg/client/clientset/versioned/fake/doc.go
  control-plane/pkg/client/clientset/versioned/fake/register.go
  control-plane/pkg/client/clientset/versioned/scheme/doc.go
  control-plane/pkg/client/clientset/versioned/scheme/register.go
  control-plane/pkg/client/clientset/versioned/typed/eventing/v1alpha1/doc.go
  control-plane/pkg/client/clientset/versioned/typed/eventing/v1alpha1/eventing_client.go
  control-plane/pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/doc.go
  control-plane/pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/fake_eventing_client.go
  control-plane/pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/fake_kafkasink.go
  control-plane/pkg/client/clientset/versioned/typed/eventing/v1alpha1/generated_expansion.go
  control-plane/pkg/client/clientset/versioned/typed/eventing/v1alpha1/kafkasink.go
  control-plane/pkg/client/informers/externalversions/eventing/interface.go
  control-plane/pkg/client/informers/externalversions/eventing/v1alpha1/interface.go
  control-plane/pkg/client/informers/externalversions/eventing/v1alpha1/kafkasink.go
  control-plane/pkg/client/informers/externalversions/factory.go
  control-plane/pkg/client/informers/externalversions/generic.go
  control-plane/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  control-plane/pkg/client/injection/client/client.go
  control-plane/pkg/client/injection/client/fake/fake.go
  control-plane/pkg/client/injection/informers/eventing/v1alpha1/kafkasink/fake/fake.go
  control-plane/pkg/client/injection/informers/eventing/v1alpha1/kafkasink/filtered/fake/fake.go
  control-plane/pkg/client/injection/informers/eventing/v1alpha1/kafkasink/filtered/kafkasink.go
  control-plane/pkg/client/injection/informers/eventing/v1alpha1/kafkasink/kafkasink.go
  control-plane/pkg/client/injection/informers/factory/factory.go
  control-plane/pkg/client/injection/informers/factory/fake/fake.go
  control-plane/pkg/client/injection/informers/factory/filtered/fake/fake_filtered_factory.go
  control-plane/pkg/client/injection/informers/factory/filtered/filtered_factory.go
  control-plane/pkg/client/injection/reconciler/eventing/v1alpha1/kafkasink/controller.go
  control-plane/pkg/client/injection/reconciler/eventing/v1alpha1/kafkasink/reconciler.go
  control-plane/pkg/client/injection/reconciler/eventing/v1alpha1/kafkasink/state.go
  control-plane/pkg/client/listers/eventing/v1alpha1/expansion_generated.go
  control-plane/pkg/client/listers/eventing/v1alpha1/kafkasink.go
  hack/boilerplate/boilerplate.go.txt
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-uuid/.travis.yml
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-uuid/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-uuid/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-uuid/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-uuid/uuid.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/.gitignore
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/2q.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/arc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/doc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
Labels: approved, area/control-plane, cla: yes, lgtm, size/XXL

#1090 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#1094 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#1093 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#1095 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#1100 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#1097 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#1105 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#1106 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L

#1092 Resolved Trigger deadLetterSink is available in the status
  control-plane/pkg/core/config/utils.go
  control-plane/pkg/core/config/utils_test.go
  control-plane/pkg/reconciler/trigger/trigger.go
  control-plane/pkg/reconciler/trigger/trigger_lifecycle.go
  control-plane/pkg/reconciler/trigger/trigger_test.go
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-uuid/.travis.yml
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-uuid/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-uuid/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-uuid/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-uuid/uuid.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/.gitignore
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/2q.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/arc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/doc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/broker.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/trigger.go
  vendor/knative.dev/pkg/test/spoof/error_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/reconciler-test/cmd/eventshub/main.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/event_info.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/event_log.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/eventshub.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/eventshub_image.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/options.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/prober.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/receiver/receiver.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/modules.txt
Labels: approved, area/control-plane, cla: yes, kind/enhancement, lgtm, size/XXL

#1116 [Automated] Update eventing-kafka-broker nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, cla: yes, lgtm, size/L
