Repository knative-extensions/eventing-kafka-broker, pull requests merged in 2022-12, with the labels that each got.

#2813 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#2801 Add maxDuplicatesPercentage for Broker sacura test
  test/config/sacura/resources/200-config.yaml
Labels: approved, size/XS, lgtm, area/test

#2817 Missing unit tests for namespaced broker
  control-plane/pkg/reconciler/broker/broker_test.go
  control-plane/pkg/reconciler/broker/namespaced_broker_test.go
  control-plane/pkg/reconciler/testing/listers.go
  control-plane/pkg/reconciler/testing/objects_broker.go
  control-plane/pkg/reconciler/testing/objects_common.go
  control-plane/pkg/reconciler/testing/objects_consumergroup.go
  vendor/github.com/manifestival/manifestival/fake/client.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL, area/control-plane

#2816 Handle ConsumerGroup finalization for deleted topics
  control-plane/pkg/kafka/testing/admin_mock.go
  control-plane/pkg/reconciler/consumergroup/consumergroup.go
  control-plane/pkg/reconciler/consumergroup/consumergroup_test.go
  control-plane/pkg/reconciler/testing/errors.go
Labels: approved, lgtm, size/L, area/control-plane

#2795 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing-kafka/pkg/apis/kafka/v1alpha1/reset_offset_types.go
  vendor/knative.dev/eventing-kafka/pkg/apis/sources/config/store.go
  vendor/knative.dev/eventing-kafka/pkg/client/clientset/versioned/fake/register.go
  vendor/knative.dev/eventing-kafka/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/eventing-kafka/pkg/common/client/config.go
  vendor/knative.dev/eventing-kafka/pkg/common/client/kafka_scram_client.go
  vendor/knative.dev/eventing-kafka/pkg/common/client/yaml.go
  vendor/knative.dev/eventing-kafka/pkg/common/config/kafkaconfigmapwatcher.go
  vendor/knative.dev/eventing-kafka/pkg/common/kafka/sarama/sarama.go
  vendor/knative.dev/eventing-kafka/test/e2e/helpers/kafka_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_dls_test_helper.go
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#2824 Fix namespaced broker unit tests
  control-plane/pkg/reconciler/broker/namespaced_broker_test.go
  control-plane/pkg/reconciler/testing/factory.go
  control-plane/pkg/reconciler/testing/objects_common.go
  vendor/github.com/manifestival/manifestival/fake/client.go
  vendor/modules.txt
Labels: approved, lgtm, size/L, area/control-plane

#2825 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing-kafka/pkg/apis/sources/v1beta1/kafka_defaults.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#2827 [Automated] Update eventing-kafka-broker-eventing-kafka nightly
  third_party/eventing-kafka-latest/channel-crds.yaml
  third_party/eventing-kafka-latest/source-crd.yaml
Labels: approved, size/XS, lgtm

#2823 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#2830 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L, ok-to-test

#2831 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/upgrade/prober/configuration.go
  vendor/knative.dev/eventing/test/upgrade/prober/verify.go
  vendor/modules.txt
Labels: approved, size/M, lgtm

#2834 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#2833 WithAnnotation() is deprecated, replacing with 'WithAnnotations'
  test/e2e_new/ordered_test.go
  test/e2e_new/tracing_test.go
Labels: approved, lgtm, size/S, area/test

#2832 Going with latest Jackson version, 2.14.1
  data-plane/THIRD-PARTY.txt
  data-plane/pom.xml
Labels: approved, lgtm, size/S, area/data-plane

#2836 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/rekt/resources/trigger/trigger.go
  vendor/modules.txt
Labels: approved, size/M, lgtm

#2838 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#2840 Bumping to latest Knative Eventing
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/rekt/resources/broker/broker.go
  vendor/knative.dev/eventing/test/rekt/resources/broker/broker.yaml
  vendor/modules.txt
Labels: approved, lgtm, size/S

#2839 [Automated] Update eventing-kafka-broker-eventing-kafka nightly
  third_party/eventing-kafka-latest/channel-crds.yaml
  third_party/eventing-kafka-latest/source-crd.yaml
Labels: approved, size/XS, lgtm

#2842 Bumping to latest knative/eventing
  control-plane/pkg/reconciler/broker/broker.go
  control-plane/pkg/reconciler/testing/objects_broker.go
  go.mod
  go.sum
  test/upgrade/continual/broker.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/test/rekt/features/broker/control_plane.go
  vendor/knative.dev/eventing/test/rekt/features/broker/data_plane.go
  vendor/knative.dev/eventing/test/upgrade/prober/sut/broker.go
  vendor/modules.txt
Labels: approved, size/M, lgtm, area/control-plane, area/test

#2847 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/S, skip-review

#2841 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#2850 [Automated] Update eventing-kafka-broker-eventing-kafka nightly
  third_party/eventing-kafka-latest/channel-crds.yaml
  third_party/eventing-kafka-latest/source-crd.yaml
Labels: approved, size/XS, lgtm

#2848 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_lifecycle.go
  vendor/modules.txt
Labels: approved, size/M, lgtm

#2829 Do not block finalization if secret for external topic is gone
  control-plane/pkg/reconciler/broker/broker.go
  control-plane/pkg/reconciler/broker/broker_test.go
  test/e2e_new/broker_test.go
  test/e2e_new/features/broker_deleted_recreated.go
  test/e2e_new/resources/configmap/broker/broker_config.go
  test/e2e_new/resources/configmap/broker/broker_config.yaml
Labels: approved, lgtm, size/L, area/control-plane, area/test

#2856 Granting permissions to delete consumer groups metadata
  test/kafka/user-sasl-scram-512.yaml
  test/kafka/user-tls.yaml
Labels: approved, lgtm, size/S, area/test

#2858 Manual bump dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/rekt/resources/broker/broker.go
  vendor/knative.dev/eventing/test/rekt/resources/broker/broker.yaml
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/modules.txt
Labels: approved, size/M, lgtm

#2851 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#2854 Templating support in namespaced broker additional resources
  control-plane/pkg/propagator/resource_propagator.go
  control-plane/pkg/propagator/resource_propagator_test.go
  control-plane/pkg/reconciler/broker/namespaced_broker.go
  go.mod
  test/e2e_new/features/featuressteps/broker.go
  test/e2e_new/features/namespaced_broker.go
Labels: approved, lgtm, size/L, area/control-plane, area/test
