Repository knative-extensions/eventing-kafka-broker, pull requests merged in 2023-04, with the labels that each got.

#3029 Remove eventing-kafka-latests Channel & Source CRD from third_party
  third_party/eventing-kafka-latest/channel-crds.yaml
  third_party/eventing-kafka-latest/source-crd.yaml
Labels: approved, lgtm, size/L

#2927 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#3036 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3037 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3032 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#3040 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#3045 Don't override ports for KafkaChannel's service
  control-plane/pkg/reconciler/channel/resources/service.go
  control-plane/pkg/reconciler/testing/objects_channel.go
Labels: approved, lgtm, size/S, area/control-plane

#3044 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#3041 Update deps
  control-plane/pkg/reconciler/consumergroup/controller.go
  go.mod
  go.sum
  hack/tools.go
  test/e2e_new_channel/tracing_test.go
  test/scripts/first-event-delay.sh
  vendor/knative.dev/eventing/cmd/heartbeats/main.go
  vendor/knative.dev/eventing/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/feature/features.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/kncloudevents/retries.go
  vendor/knative.dev/eventing/pkg/scheduler/statefulset/autoscaler.go
  vendor/knative.dev/eventing/pkg/scheduler/statefulset/scheduler.go
  vendor/knative.dev/eventing/test/README.md
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/knative.dev/eventing/test/rekt/features/channel/features.go
  vendor/knative.dev/eventing/test/rekt/resources/containersource/containersource.yaml
  vendor/knative.dev/eventing/test/rekt/resources/svc/service.go
  vendor/knative.dev/eventing/test/test_images/heartbeats/main.go
  vendor/knative.dev/eventing/test/test_images/heartbeats/pod.yaml
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/injection/health_check.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/webhook/env.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/reconciler-test/pkg/resources/job/job.yaml
  vendor/knative.dev/reconciler-test/pkg/resources/secret/secret.yaml
  vendor/knative.dev/reconciler-test/pkg/resources/service/service.yaml
  vendor/modules.txt
Labels: approved, lgtm, size/XL, area/control-plane, area/test

#3034 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-vulnerability.yaml
Labels: approved, size/L, area/test, skip-review

#3049 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/message_receiver.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#3051 Go 1.19 usage
  go.mod
Labels: approved, size/XS, lgtm

#3050 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#3052 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#3054 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S

#3053 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#3059 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3060 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/modules.txt
Labels: approved, lgtm, size/L
