Repository knative-extensions/eventing-kafka-broker, pull requests merged in 2023-12, with the labels that each got.

#3499 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#3496 Updating to latest Quarkus (3.2.9.Final), and aligning vertx it the one used in the BOM
  data-plane/THIRD-PARTY.txt
  data-plane/pom.xml
Labels: approved, size/M, lgtm, area/data-plane

#3484 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/hack/update-codegen.sh
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta3/doc.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta3/eventtype_conversion.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta3/eventtype_defaults.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta3/eventtype_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta3/eventtype_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta3/eventtype_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta3/register.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta3/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/auth/serviceaccount.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/clientset_generated.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta3/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta3/eventing_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta3/eventtype.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta3/fake/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta3/fake/fake_eventing_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta3/fake/fake_eventtype.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta3/generated_expansion.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/eventing/interface.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/eventing/v1beta3/eventtype.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/eventing/v1beta3/interface.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/generic.go
  vendor/knative.dev/eventing/pkg/client/listers/eventing/v1beta3/eventtype.go
  vendor/knative.dev/eventing/pkg/client/listers/eventing/v1beta3/expansion_generated.go
  vendor/knative.dev/eventing/test/rekt/features/broker/topology.go
  vendor/knative.dev/eventing/test/rekt/resources/trigger/trigger.go
  vendor/knative.dev/eventing/test/rekt/resources/trigger/trigger.yaml
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#3497 [release-1.11] Cherry-pick E2E tests for channel: TLS key pair rotation #3406
  control-plane/config/eventing-kafka-broker/100-channel/100-kafka-channel.yaml
  control-plane/pkg/reconciler/channel/channel.go
  control-plane/pkg/reconciler/channel/channel_test.go
  control-plane/pkg/reconciler/channel/controller.go
  control-plane/pkg/reconciler/channel/controller_test.go
  control-plane/pkg/reconciler/channel/resources/service.go
  control-plane/pkg/reconciler/channel/v2/channelv2.go
  control-plane/pkg/reconciler/channel/v2/channelv2_test.go
  control-plane/pkg/reconciler/channel/v2/controllerv2.go
  control-plane/pkg/reconciler/testing/objects_channel.go
  test/e2e_new/channel_eventing_tls_test.go
  test/rekt/features/channel_tls.go
  test/rekt/resources/kafkachannel/kafkachannel.go
Labels: approved, lgtm, size/L, area/control-plane, area/test

#3505 Update dependencies
  go.mod
  go.sum
  test/e2e_new/new_trigger_filters_test.go
  vendor/cloud.google.com/go/compute/internal/version.go
  vendor/cloud.google.com/go/iam/CHANGES.md
  vendor/cloud.google.com/go/internal/.repo-metadata-full.json
  vendor/golang.org/x/crypto/cryptobyte/asn1.go
  vendor/golang.org/x/sys/execabs/execabs.go
  vendor/golang.org/x/sys/execabs/execabs_go118.go
  vendor/golang.org/x/sys/execabs/execabs_go119.go
  vendor/golang.org/x/sys/unix/fcntl.go
  vendor/golang.org/x/sys/unix/ioctl_linux.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_bsd.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_openbsd.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_mips64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_mips64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.s
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/time/rate/rate.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/gopathwalk/walk.go
  vendor/google.golang.org/api/internal/version.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/delivery_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/test/rekt/features/new_trigger_filters/feature.go
  vendor/knative.dev/eventing/test/rekt/features/new_trigger_filters/filters.go
  vendor/knative.dev/eventing/test/rekt/resources/broker/broker.go
  vendor/knative.dev/eventing/test/rekt/resources/broker/broker.yaml
  vendor/knative.dev/eventing/test/rekt/resources/delivery/delivery.go
  vendor/knative.dev/eventing/test/rekt/resources/delivery/delivery.yaml
  vendor/modules.txt
Labels: approved, lgtm, size/XXL, area/test

#3471 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, size/L, skip-review

#3513 Cleanup NewTriggerFilters e2e test
  test/e2e_new/new_trigger_filters_test.go
Labels: approved, size/M, lgtm, area/test

#3512 Rename config-kafka-features feature flags to be consistent with eventing core feature flag names
  control-plane/config/eventing-kafka-broker/200-controller/100-config-kafka-features.yaml
  control-plane/pkg/apis/config/features.go
Labels: approved, size/M, lgtm, ok-to-test, area/control-plane

#3491 Test Keda Kafka Source Scaling
  control-plane/config/eventing-kafka-broker/200-controller/100-config-kafka-autoscaler.yaml
  control-plane/pkg/autoscaler/autoscaler_api.go
  control-plane/pkg/reconciler/testing/objects_consumergroup.go
  test/e2e_new/kafka_source_test.go
  test/rekt/features/kafka_source.go
  test/rekt/features/kafkafeatureflags/kafkafeatureflags.go
Labels: approved, lgtm, size/L, area/control-plane, area/test

#3447 Have link to adopters form in issue/PR templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/issue-template.md
  .github/pull-request-template.md
Labels: approved, lgtm, size/S

#3523 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/api/internal/settings.go
  vendor/google.golang.org/api/internal/version.go
  vendor/google.golang.org/api/option/internaloption/internaloption.go
  vendor/google.golang.org/api/option/option.go
  vendor/google.golang.org/api/storage/v1/storage-api.json
  vendor/google.golang.org/api/storage/v1/storage-gen.go
  vendor/knative.dev/eventing/test/rekt/features/channel/control_plane.go
  vendor/knative.dev/eventing/test/rekt/features/channel/data_plane.go
  vendor/modules.txt
Labels: approved, size/M, lgtm

#3522 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L, skip-review

#3527 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/cmd/heartbeats/main.go
  vendor/knative.dev/eventing/test/rekt/resources/containersource/containersource.go
  vendor/knative.dev/eventing/test/rekt/resources/containersource/containersource.yaml
  vendor/modules.txt
Labels: approved, size/M, lgtm

#3530 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L, skip-review

#3531 Fix KinD setup with valid service account issuer
  hack/create-kind-cluster.sh
Labels: approved, size/XS, lgtm

#3534 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/auth/token_verifier.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#3516 We go all in jdk-21
  data-plane/dispatcher-loom/pom.xml
  data-plane/pom.xml
  data-plane/receiver-loom/pom.xml
  data-plane/tests/pom.xml
Labels: approved, lgtm, size/S, area/data-plane

#3535 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L, skip-review

#3538 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: size/L, skip-review

#3344 Add script to run matched rekt tests
  hack/e2e-matched-test.sh
  hack/run.sh
Labels: approved, lgtm, size/L, area/test

#3543 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/register.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/apiserver_lifecycle.go
  vendor/knative.dev/eventing/pkg/auth/serviceaccount.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/apiserversouce.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/listers.go
  vendor/modules.txt
Labels: approved, size/M, lgtm

#3506 changed '>>' to '>' in order to avoid duplicated k8s resources in yamls
  hack/control-plane.sh
Labels: approved, size/XS, lgtm, ok-to-test

#3553 Add version tag for maven plugin(#3551)
  data-plane/core/pom.xml
  data-plane/dispatcher/pom.xml
  data-plane/pom.xml
  data-plane/receiver/pom.xml
Labels: approved, size/XS, lgtm, ok-to-test, area/data-plane
