Repository knative-extensions/eventing-kafka-broker, pull requests merged in 2023-11, with the labels that each got.

#3445 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#3459 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/cloud.google.com/go/compute/internal/version.go
  vendor/cloud.google.com/go/iam/CHANGES.md
  vendor/cloud.google.com/go/iam/apiv1/iampb/iam_policy.pb.go
  vendor/cloud.google.com/go/iam/apiv1/iampb/options.pb.go
  vendor/cloud.google.com/go/iam/apiv1/iampb/policy.pb.go
  vendor/cloud.google.com/go/storage/CHANGES.md
  vendor/cloud.google.com/go/storage/bucket.go
  vendor/cloud.google.com/go/storage/grpc_client.go
  vendor/cloud.google.com/go/storage/hmac.go
  vendor/cloud.google.com/go/storage/http_client.go
  vendor/cloud.google.com/go/storage/internal/apiv2/doc.go
  vendor/cloud.google.com/go/storage/internal/apiv2/gapic_metadata.json
  vendor/cloud.google.com/go/storage/internal/apiv2/storage_client.go
  vendor/cloud.google.com/go/storage/internal/apiv2/storagepb/storage.pb.go
  vendor/cloud.google.com/go/storage/internal/version.go
  vendor/cloud.google.com/go/storage/invoke.go
  vendor/cloud.google.com/go/storage/reader.go
  vendor/golang.org/x/sync/errgroup/go120.go
  vendor/golang.org/x/sync/errgroup/pre_go120.go
  vendor/google.golang.org/api/internal/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#3458 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#3462 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, size/M, lgtm

#3461 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#3463 Adding test for SSL/NoAuth
  test/e2e_new/broker_sasl_ssl_test.go
  test/rekt/features/broker_auth.go
Labels: approved, lgtm, size/S, area/test

#3465 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/hack/install.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#3371 Refactor secret file paths to use File objects in ReceiverVerticle
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticle.java
Labels: approved, size/M, lgtm, ok-to-test, area/data-plane

#3469 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L

#3407 Add the instruction on how to run single rekt test
  DEVELOPMENT.md
Labels: approved, size/M, lgtm, ok-to-test

#3472 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/flows/v1/parallel_lifecycle.go
  vendor/knative.dev/eventing/pkg/kncloudevents/event_dispatcher.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/parallel.go
  vendor/modules.txt
Labels: approved, size/M, lgtm

#3284 Pass eventtype owner to data plane
  control-plane/pkg/contract/contract.pb.go
  data-plane/contract/src/main/java/dev/knative/eventing/kafka/broker/contract/DataPlaneContract.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/eventtype/EventTypeBuilder.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/ResourcesReconcilerImpl.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/eventtype/EventTypeTest.java
  proto/contract.proto
Labels: approved, lgtm, size/L, area/data-plane, area/control-plane

#3448 Change fabric8io HTTP client from okhttp to the core HTTP client to support IPv6 clusters
  data-plane/THIRD-PARTY.txt
  data-plane/core/pom.xml
  data-plane/pom.xml
Labels: approved, lgtm, size/S, area/data-plane

#3480 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3479 Remove activationLagThreshold to fix 0->1 scaling
  control-plane/pkg/autoscaler/config.go
  control-plane/pkg/autoscaler/keda/keda.go
Labels: approved, lgtm, size/S, area/control-plane

#3473 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/go-jose/go-jose/v3/jwt/builder.go
  vendor/github.com/go-jose/go-jose/v3/jwt/claims.go
  vendor/github.com/go-jose/go-jose/v3/jwt/doc.go
  vendor/github.com/go-jose/go-jose/v3/jwt/errors.go
  vendor/github.com/go-jose/go-jose/v3/jwt/jwt.go
  vendor/github.com/go-jose/go-jose/v3/jwt/validation.go
  vendor/google.golang.org/api/internal/version.go
  vendor/knative.dev/eventing/hack/e2e-debug.sh
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/container_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/sinkbinding_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/auth/token_provider.go
  vendor/knative.dev/eventing/pkg/auth/utils.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/containersource.go
  vendor/knative.dev/eventing/test/rekt/features/channel/features.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/event/services.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/event/types.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/sender/services.go
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/reconciler-test/pkg/environment/flags.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/state/timings.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#3490 clean up: making argument final
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleBuilder.java
Labels: approved, size/XS, lgtm, area/data-plane

#3492 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3485 Update dependencies
  control-plane/pkg/apis/messaging/v1beta1/kafka_channel_validation.go
  go.mod
  go.sum
  test/e2e_new_channel/kafka_channel_upstream_test.go
  test/e2e_new_channel/tracing_test.go
  test/rekt/features/kafkachannel/util.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/subscribable_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/register.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/in_memory_channel_validation.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/broker.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_spec_test_helper.go
  vendor/knative.dev/eventing/test/lib/resources/eventing.go
  vendor/knative.dev/eventing/test/rekt/features/broker/feature.go
  vendor/knative.dev/eventing/test/rekt/features/channel/control_plane.go
  vendor/knative.dev/eventing/test/rekt/features/channel/features.go
  vendor/knative.dev/eventing/test/rekt/features/channel/topology.go
  vendor/knative.dev/eventing/test/rekt/resources/subscription/subscription.go
  vendor/knative.dev/eventing/test/rekt/resources/subscription/subscription.yaml
  vendor/modules.txt
Labels: approved, lgtm, size/L, area/control-plane, area/test
