Repository knative-extensions/eventing-kafka-broker, pull requests merged in 2024-12, with the labels that each got.

#4138 Use and test KafkaSource v1 API
  control-plane/pkg/apis/internalskafkaeventing/v1alpha1/consumer_defaults.go
  control-plane/pkg/apis/internalskafkaeventing/v1alpha1/consumer_defaults_test.go
  control-plane/pkg/apis/internalskafkaeventing/v1alpha1/consumer_group_defaults_test.go
  control-plane/pkg/apis/internalskafkaeventing/v1alpha1/consumer_group_validation_test.go
  control-plane/pkg/apis/internalskafkaeventing/v1alpha1/consumer_types.go
  control-plane/pkg/apis/internalskafkaeventing/v1alpha1/consumer_validation.go
  control-plane/pkg/apis/internalskafkaeventing/v1alpha1/zz_generated.deepcopy.go
  control-plane/pkg/apis/sources/v1beta1/kafka_types.go
  control-plane/pkg/autoscaler/keda/keda.go
  control-plane/pkg/reconciler/base/receiver_condition_set.go
  control-plane/pkg/reconciler/broker/namespaced_broker_test.go
  control-plane/pkg/reconciler/channel/channel.go
  control-plane/pkg/reconciler/channel/channel_test.go
  control-plane/pkg/reconciler/consumer/consumer.go
  control-plane/pkg/reconciler/consumer/consumer_test.go
  control-plane/pkg/reconciler/consumergroup/consumergroup.go
  control-plane/pkg/reconciler/consumergroup/consumergroup_test.go
  control-plane/pkg/reconciler/consumergroup/controller_test.go
  control-plane/pkg/reconciler/source/controller.go
  control-plane/pkg/reconciler/source/controller_test.go
  control-plane/pkg/reconciler/source/source.go
  control-plane/pkg/reconciler/source/source_test.go
  control-plane/pkg/reconciler/testing/listers.go
  control-plane/pkg/reconciler/testing/objects_common.go
  control-plane/pkg/reconciler/testing/objects_consumer.go
  control-plane/pkg/reconciler/testing/objects_source.go
  control-plane/pkg/reconciler/trigger/namespaced_trigger_test.go
  control-plane/pkg/reconciler/trigger/trigger.go
  control-plane/pkg/reconciler/trigger/trigger_test.go
  control-plane/pkg/reconciler/trigger/v2/triggerv2.go
  control-plane/pkg/reconciler/trigger/v2/triggerv2_test.go
  control-plane/pkg/security/secrets_provider_net_spec.go
  control-plane/pkg/security/secrets_provider_net_spec_test.go
  control-plane/pkg/security/secrets_tracker.go
  control-plane/pkg/security/secrets_tracker_test.go
  test/config/sacura-sink-source/resources/100-source.yaml
  test/e2e/sacura_test.go
  test/e2e_source/helpers/kafka_source.go
  test/lib/creation.go
  test/lib/resources/kafkabinding.go
  test/lib/resources/kafkasource.go
  test/rekt/features/kafka_source.go
  test/rekt/features/keda_scaling.go
  test/rekt/resources/kafkasource/kafkasource.go
  test/upgrade/continual/sink_source.go
  test/upgrade/continual/types.go
Labels: approved, lgtm, size/L, area/control-plane, area/test

#4181 Complete Consumer verticle stop promise only after closing dependencies
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/ConsumerVerticle.java
Labels: approved, lgtm, size/S, area/data-plane

#4185 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: size/L, skip-review

#4186 Bump golang.org/x/crypto from 0.28.0 to 0.31.0
  go.mod
  go.sum
  vendor/golang.org/x/sys/unix/ioctl_linux.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/unix/ztypes_zos_s390x.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/term/README.md
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#4191 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: size/L, skip-review

#4194 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#4192 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: size/L, skip-review
