Repository knative-extensions/eventing-kafka-broker, pull requests merged in 2024-06, with the labels that each got.

#3916 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, size/L, skip-review

#3920 Skip flaky TestBrokerNotReadyAfterBeingReady test for namespaced Broker
  test/e2e_new/broker_not_ready_test.go
Labels: approved, size/XS, lgtm, area/test

#3912 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/cloud.google.com/go/auth/CHANGES.md
  vendor/cloud.google.com/go/auth/auth.go
  vendor/cloud.google.com/go/auth/credentials/compute.go
  vendor/cloud.google.com/go/auth/httptransport/httptransport.go
  vendor/cloud.google.com/go/auth/internal/transport/cba.go
  vendor/cloud.google.com/go/internal/.repo-metadata-full.json
  vendor/google.golang.org/api/internal/version.go
  vendor/google.golang.org/api/storage/v1/storage-api.json
  vendor/google.golang.org/api/storage/v1/storage-gen.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/annotations.pb.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/client.pb.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/field_behavior.pb.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/field_info.pb.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/http.pb.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/resource.pb.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/routing.pb.go
  vendor/google.golang.org/genproto/googleapis/api/httpbody/httpbody.pb.go
  vendor/google.golang.org/genproto/googleapis/api/launch_stage.pb.go
  vendor/knative.dev/eventing/hack/e2e-debug.sh
  vendor/knative.dev/eventing/hack/update-codegen.sh
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/eventtype_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sinks/constants.go
  vendor/knative.dev/eventing/pkg/apis/sinks/register.go
  vendor/knative.dev/eventing/pkg/apis/sinks/v1alpha1/doc.go
  vendor/knative.dev/eventing/pkg/apis/sinks/v1alpha1/job_sink_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sinks/v1alpha1/job_sink_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sinks/v1alpha1/job_sink_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sinks/v1alpha1/job_sink_types.go
  vendor/knative.dev/eventing/pkg/apis/sinks/v1alpha1/job_sink_validation.go
  vendor/knative.dev/eventing/pkg/apis/sinks/v1alpha1/register.go
  vendor/knative.dev/eventing/pkg/apis/sinks/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/auth/audience.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/clientset_generated.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sinks/v1alpha1/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sinks/v1alpha1/fake/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sinks/v1alpha1/fake/fake_jobsink.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sinks/v1alpha1/fake/fake_sinks_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sinks/v1alpha1/generated_expansion.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sinks/v1alpha1/jobsink.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sinks/v1alpha1/sinks_client.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/factory.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/generic.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/sinks/interface.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/sinks/v1alpha1/interface.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/sinks/v1alpha1/jobsink.go
  vendor/knative.dev/eventing/pkg/client/listers/sinks/v1alpha1/expansion_generated.go
  vendor/knative.dev/eventing/pkg/client/listers/sinks/v1alpha1/jobsink.go
  vendor/knative.dev/eventing/pkg/eventingtls/eventingtls.go
  vendor/knative.dev/eventing/pkg/kncloudevents/event_dispatcher.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/forwarder/forwarder.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/options.go
  vendor/knative.dev/reconciler-test/pkg/k8s/steps.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#3900 Bump to latest Kafka clients 3.7
  data-plane/THIRD-PARTY.txt
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherImpl.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/NullCloudEventInterceptor.java
  data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetManagerTest.java
  data-plane/pom.xml
  data-plane/tests/pom.xml
Labels: approved, size/M, lgtm, area/data-plane

#3927 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3919 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, size/XL, skip-review

#3928 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/cloud.google.com/go/auth/CHANGES.md
  vendor/cloud.google.com/go/auth/credentials/filetypes.go
  vendor/cloud.google.com/go/auth/grpctransport/grpctransport.go
  vendor/cloud.google.com/go/auth/httptransport/httptransport.go
  vendor/cloud.google.com/go/auth/internal/transport/cert/workload_cert.go
  vendor/golang.org/x/mod/module/module.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/timer.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/writesched_priority.go
  vendor/golang.org/x/net/proxy/per_host.go
  vendor/golang.org/x/oauth2/google/google.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/security_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/google.golang.org/api/internal/version.go
  vendor/google.golang.org/genproto/googleapis/type/date/date.pb.go
  vendor/google.golang.org/genproto/googleapis/type/expr/expr.pb.go
  vendor/knative.dev/eventing/pkg/apis/sinks/register.go
  vendor/knative.dev/eventing/pkg/apis/sinks/v1alpha1/job_sink_validation.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#3930 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/hack/generate-yamls.sh
  vendor/knative.dev/eventing/hack/update-codegen.sh
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/doc.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/eventpolicy_conversion.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/eventpolicy_defaults.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/eventpolicy_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/eventpolicy_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/eventpolicy_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/register.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/feature/features.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/clientset_generated.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1alpha1/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1alpha1/eventing_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1alpha1/eventpolicy.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/fake_eventing_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/fake_eventpolicy.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1alpha1/generated_expansion.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/eventing/interface.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/eventing/v1alpha1/eventpolicy.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/eventing/v1alpha1/interface.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/generic.go
  vendor/knative.dev/eventing/pkg/client/listers/eventing/v1alpha1/eventpolicy.go
  vendor/knative.dev/eventing/pkg/client/listers/eventing/v1alpha1/expansion_generated.go
  vendor/knative.dev/eventing/pkg/kncloudevents/event_dispatcher.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#3932 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/duck/v1/eventpoliciesstatus_type.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/parallel_types.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_types.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/in_memory_channel_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, size/M, lgtm

#3933 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/eventpolicy_validation.go
  vendor/knative.dev/eventing/pkg/apis/feature/store.go
  vendor/knative.dev/eventing/pkg/auth/event_policy.go
  vendor/knative.dev/eventing/pkg/kncloudevents/event_dispatcher.go
  vendor/knative.dev/pkg/apis/duck/v1/auth_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/authstatus/authstatus.go
  vendor/knative.dev/pkg/resolver/authenticatable_resolver.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#3941 fix: only add authentication ref to scaled objects when there is an actual value to reference
  control-plane/pkg/autoscaler/keda/keda.go
Labels: approved, size/XS, lgtm, area/control-plane

#3944 test: verify that scaledobjects have no authenticationref when it is empty
  test/e2e_new/kafka_source_test.go
  test/rekt/features/keda_scaling.go
Labels: approved, size/M, lgtm, area/test

#3950 fix: go version in go mod is correct now
  go.mod
Labels: approved, size/XS, lgtm

#3951 Move to using namespaced listers for eventtypes in data plane
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/eventtype/EventTypeCreatorImpl.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/eventtype/EventTypeListerFactory.java
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/eventtype/EventTypeCreatorImplTest.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/Main.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverVerticleFactory.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverVerticleFactoryTest.java
Labels: approved, size/M, lgtm, area/data-plane

#3957 LoomKafkaConsumer::close let closing task finish before interrupting
  data-plane/dispatcher-loom/src/main/java/dev/knative/eventing/kafka/broker/dispatcherloom/LoomKafkaConsumer.java
Labels: approved, lgtm, size/S, area/data-plane

#3954 Revert "fix: go version in go mod is correct now"
  go.mod
Labels: approved, size/XS, lgtm

#3940 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: size/L, skip-review
