Repository knative-extensions/eventing-kafka-broker, pull requests merged in 2024-07, with the labels that each got.

#3958 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/eventpolicy_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/feature/features.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_lifecycle.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/eventpolicy.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/sequence.go
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L

#3960 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L, skip-review

#3965 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#3972 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: size/L, skip-review

#3885 Remove unused vertx-kafka-client from dependencies
  data-plane/THIRD-PARTY.txt
  data-plane/core/pom.xml
Labels: approved, size/XS, lgtm, area/data-plane

#3976 feat: added UpdateScale method to KafkaSource client
  control-plane/pkg/apis/sources/v1beta1/kafka_types.go
  control-plane/pkg/client/clientset/versioned/typed/sources/v1beta1/fake/fake_kafkasource.go
  control-plane/pkg/client/clientset/versioned/typed/sources/v1beta1/kafkasource.go
Labels: approved, lgtm, size/S, area/control-plane

#3984 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta3/eventtype_lifecycle.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/eventtype.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/listers.go
  vendor/modules.txt
Labels: approved, size/M, lgtm

#3982 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L, skip-review

#3980 feat: added delivery format to the contract
  control-plane/pkg/contract/contract.pb.go
  data-plane/contract/src/main/java/dev/knative/eventing/kafka/broker/contract/DataPlaneContract.java
  proto/contract.proto
Labels: approved, lgtm, size/L, area/data-plane, area/control-plane

#3985 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L, skip-review

#3986 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/eventtype_conversion.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/parallel_lifecycle.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/eventpolicy.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/parallel.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#3988 Bump to Strimzi 0.42.0 operator and Kafka operand to 3.7.1
  test/kafka/kafka-ephemeral.yaml
  test/kafka/strimzi-cluster-operator.yaml
Labels: approved, lgtm, size/XXL, area/test

#3963 feat: removed new trigger filters feature flag
  control-plane/pkg/reconciler/consumer/consumer.go
  control-plane/pkg/reconciler/trigger/trigger.go
  control-plane/pkg/reconciler/trigger/trigger_test.go
  test/experimental/features_config/features.yaml
Labels: approved, lgtm, size/S, area/control-plane, area/test

#3993 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/feature/features.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#3996 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/eventpolicy_validation.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#3989 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L, skip-review

#3997 Remove JBoss logging from dependencies
  data-plane/THIRD-PARTY.txt
  data-plane/core/pom.xml
Labels: approved, lgtm, size/S, area/data-plane

#3998 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, size/L, skip-review

#3938 fix: kafka controller does not panic on invalid kafka client config
  control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_validation.go
  control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_validation_test.go
  control-plane/pkg/reconciler/consumergroup/consumergroup.go
Labels: approved, lgtm, size/S, area/control-plane

#4001 fix: virtual secrets created from netspec have name and namespace
  control-plane/pkg/security/secrets_provider_net_spec.go
  control-plane/pkg/security/secrets_provider_net_spec_test.go
Labels: approved, size/M, lgtm, area/control-plane

#4005 fix: do not double increment clientpool wg
  control-plane/pkg/kafka/clientpool/clientpool.go
  control-plane/pkg/kafka/clientpool/clientpool_test.go
  control-plane/pkg/kafka/clientpool/clusteradmin.go
  control-plane/pkg/kafka/testing/admin_mock.go
  control-plane/pkg/kafka/testing/client_mock.go
Labels: approved, size/M, lgtm, area/control-plane

#4020 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#4016 fix: correct clusterrole permissions for post install job
  control-plane/config/post-install/200-controller-cluster-role.yaml
Labels: approved, size/XS, lgtm, area/control-plane
