Repository knative-extensions/eventing-kafka-broker, pull requests merged in 2024-11, with the labels that each got.

#4155 Allow kafka-controller to list JobSinks
  control-plane/config/eventing-kafka-broker/200-controller/200-controller-cluster-role.yaml
Labels: approved, lgtm, size/S, area/control-plane

#4124 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, size/XXL, skip-review

#4156 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#4159 Thread safe improvements on OIDCDiscoveryConfigListener
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/auth/OIDCDiscoveryConfigListener.java
Labels: approved, size/M, lgtm, area/data-plane

#4163 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: size/L, skip-review

#4176 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review
