Repository knative-extensions/eventing-kafka-broker, pull requests merged in 2024-03, with the labels that each got.

#3727 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3725 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/experimental/features/eventtype_autocreate/features.go
  vendor/knative.dev/eventing/test/rekt/resources/eventtype/eventtype.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/forwarder/forwarder.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#3717 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/eventing-tls-networking.yaml
Labels: approved, lgtm, size/L, skip-review

#3728 TokenVerifier: execute blocking calls in parallel
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/oidc/TokenVerifierImpl.java
Labels: approved, size/M, lgtm, ok-to-test, area/data-plane, area/control-plane

#3732 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/knative.dev/eventing/test/e2e-conformance-tests.sh
  vendor/knative.dev/eventing/test/e2e-rekt-tests.sh
  vendor/knative.dev/eventing/test/e2e-tests.sh
  vendor/knative.dev/eventing/test/e2e-upgrade-tests.sh
  vendor/knative.dev/eventing/test/rekt/features/channel/data_plane.go
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L

#3739 Bump CloudEvents GO-SDK to 2.15.2
  go.mod
  go.sum
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#3738 Use error log level when contract parsing fails
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/eventbus/ContractPublisher.java
Labels: approved, size/XS, lgtm, area/data-plane

#3733 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/cloud.google.com/go/compute/internal/version.go
  vendor/cloud.google.com/go/storage/CHANGES.md
  vendor/cloud.google.com/go/storage/client.go
  vendor/cloud.google.com/go/storage/grpc_client.go
  vendor/cloud.google.com/go/storage/http_client.go
  vendor/cloud.google.com/go/storage/internal/apiv2/storagepb/storage.pb.go
  vendor/cloud.google.com/go/storage/internal/version.go
  vendor/cloud.google.com/go/storage/writer.go
  vendor/github.com/prometheus/client_model/go/metrics.pb.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/github.com/prometheus/common/expfmt/openmetrics_create.go
  vendor/github.com/prometheus/common/model/labelset.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#3747 Bump just go-jose to latest
  go.mod
  go.sum
  vendor/github.com/go-jose/go-jose/v3/BUG-BOUNTY.md
  vendor/github.com/go-jose/go-jose/v3/CHANGELOG.md
  vendor/github.com/go-jose/go-jose/v3/README.md
  vendor/github.com/go-jose/go-jose/v3/SECURITY.md
  vendor/github.com/go-jose/go-jose/v3/asymmetric.go
  vendor/github.com/go-jose/go-jose/v3/crypter.go
  vendor/github.com/go-jose/go-jose/v3/doc.go
  vendor/github.com/go-jose/go-jose/v3/encoding.go
  vendor/github.com/go-jose/go-jose/v3/json/decode.go
  vendor/github.com/go-jose/go-jose/v3/json/encode.go
  vendor/github.com/go-jose/go-jose/v3/json/stream.go
  vendor/github.com/go-jose/go-jose/v3/jwe.go
  vendor/github.com/go-jose/go-jose/v3/jwk.go
  vendor/github.com/go-jose/go-jose/v3/jws.go
  vendor/github.com/go-jose/go-jose/v3/jwt/claims.go
  vendor/github.com/go-jose/go-jose/v3/jwt/doc.go
  vendor/github.com/go-jose/go-jose/v3/opaque.go
  vendor/github.com/go-jose/go-jose/v3/shared.go
  vendor/github.com/go-jose/go-jose/v3/signing.go
  vendor/github.com/go-jose/go-jose/v3/symmetric.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#3748 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/eventing-tls-networking.yaml
Labels: approved, size/L, skip-review

#3735 Replace bash script log collector with a more resilient go based log collector
  test/e2e_new/main_test.go
  test/pkg/logging/logging.go
Labels: approved, lgtm, size/L, area/test

#3754 Unpin CE Kafka protocol version from older version
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S

#3756 Add timestamp to filename for logs
  test/pkg/logging/logging.go
Labels: approved, size/XS, lgtm, area/test

#3557 Migrate to use Loom modules by default
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/tracing/kafka/ProducerTracer.java
  data-plane/dispatcher-loom/src/main/java/dev/knative/eventing/kafka/broker/dispatcherloom/LoomKafkaConsumer.java
  data-plane/receiver-loom/src/main/java/dev/knative/eventing/kafka/broker/receiverloom/LoomKafkaProducer.java
  data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticleTracingTest.java
  hack/data-plane.sh
Labels: approved, lgtm, size/L, area/data-plane

#3758 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/hack/run.sh
  vendor/knative.dev/hack/infra-library.sh
  vendor/modules.txt
Labels: approved, size/M, lgtm

#3757 Update to K8s 1.28 in create-kind-cluster.sh
  hack/create-kind-cluster.sh
Labels: approved, size/XS, lgtm

#3760 [release-1.13] Unpin CE Kafka protocol version from older version
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S

#3766 [e2e test] for broker topic and trigger consumer id templates being used
  test/e2e_new/broker_sasl_ssl_test.go
  test/kafka/kafka_setup.sh
  test/kafka/user-sasl-scram-512-restricted.yaml
  test/pkg/run.go
  test/rekt/features/broker_auth.go
  test/rekt/resources/kafkaauthsecret/kafkaauthsecret.go
Labels: approved, size/M, lgtm, area/test

#3761 Cancel receiver pod start on invalid OIDC config only if authentication.oidc is enabled
  control-plane/pkg/reconciler/broker/namespaced_broker.go
  control-plane/pkg/reconciler/broker/namespaced_broker_test.go
  data-plane/config/broker/500-receiver.yaml
  data-plane/config/channel/500-receiver.yaml
  data-plane/config/sink/500-receiver.yaml
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/features/FeaturesConfig.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/oidc/TokenVerifierImpl.java
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/utils/BaseEnv.java
  data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/Main.java
Labels: approved, lgtm, size/L, area/data-plane, area/control-plane

#3759 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3771 Add unit test for FeaturesConfig class
  data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/features/FeaturesConfigTest.java
Labels: approved, size/M, lgtm, area/data-plane

#3755 used new logging package in all e2e test main functions
  test/e2e/main_test.go
  test/e2e_channel/main_test.go
  test/e2e_new_channel/main_test.go
  test/e2e_sink/main_test.go
  test/e2e_source/main_test.go
Labels: approved, lgtm, size/L, ok-to-test, area/test

#3768 Bump strimzi 0.40.0 kafka 3.7.0
  test/kafka/kafka-ephemeral.yaml
  test/kafka/strimzi-cluster-operator.yaml
Labels: approved, lgtm, size/XXL, area/test

#3779 fix: triggers use correct consumer group id generated from template
  control-plane/pkg/reconciler/trigger/controller.go
  control-plane/pkg/reconciler/trigger/controller_test.go
  control-plane/pkg/reconciler/trigger/namespaced_controller.go
  control-plane/pkg/reconciler/trigger/namespaced_controller_test.go
  control-plane/pkg/reconciler/trigger/namespaced_trigger.go
  control-plane/pkg/reconciler/trigger/namespaced_trigger_test.go
  test/e2e_new/broker_sasl_ssl_test.go
  test/rekt/features/broker_auth.go
  test/rekt/resources/configmap/configkafkafeatures/configKafkaFeatures.go
Labels: approved, lgtm, size/L, area/control-plane, area/test

#3777 adding s390x and ppc64le platform for loom based builds
  data-plane/dispatcher-loom/pom.xml
  data-plane/receiver-loom/pom.xml
Labels: approved, lgtm, size/S, area/data-plane

#3782 cleanup: consumergroup template test does not modify configmap now
  test/config-kafka-features/new-cg-id.yaml
  test/config-kafka-features/restore-cg-id.yaml
  test/reconciler-tests.sh
  test/rekt/features/broker_auth.go
  test/rekt/resources/configmap/configkafkafeatures/configKafkaFeatures.go
Labels: approved, lgtm, size/L, area/test

#3788 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#3789 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3790 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3793 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#3787 Add cluster admin proxy
  control-plane/pkg/kafka/clientpool/client_test.go
  control-plane/pkg/kafka/clientpool/clientpool.go
  control-plane/pkg/kafka/clientpool/clusteradmin.go
  control-plane/pkg/kafka/clientpool/clusteradmin_test.go
  control-plane/pkg/kafka/testing/admin_mock.go
  control-plane/pkg/kafka/testing/client_mock.go
Labels: approved, lgtm, size/XL, area/control-plane

#3783 added sacura tests to keda test job
  test/keda-reconciler-tests.sh
Labels: approved, size/XS, lgtm, ok-to-test, area/test
