Repository knative-extensions/eventing-kafka-broker, pull requests merged in 2025-08, with the labels that each got.

#4452 treat offsets skipped due to kafka transactions as comitted
  data-plane/config/source/100-config-kafka-source-data-plane.yaml
  data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/metrics/Metrics.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherImpl.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/CloudEventOverridesMutator.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetSkippingCloudEvent.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OrderedConsumerVerticle.java
  data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/UnorderedConsumerVerticle.java
  test/e2e_source/helpers/kafka_helper.go
  test/e2e_source/helpers/kafka_source.go
  test/pkg/kafka/verify_committed_offset.go
  test/test_images/committed-offset/admin.go
Labels: approved, lgtm, size/L, area/data-plane, area/test

#4467 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/client_golang/prometheus/internal/difflib.go
  vendor/github.com/prometheus/client_golang/prometheus/metric.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_darwin.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_mem_nocgo_darwin.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_procfsenabled.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/vec.go
  vendor/github.com/prometheus/client_golang/prometheus/wrap.go
  vendor/github.com/spf13/pflag/README.md
  vendor/github.com/spf13/pflag/bool_func.go
  vendor/github.com/spf13/pflag/count.go
  vendor/github.com/spf13/pflag/errors.go
  vendor/github.com/spf13/pflag/flag.go
  vendor/github.com/spf13/pflag/func.go
  vendor/github.com/spf13/pflag/golangflag.go
  vendor/github.com/spf13/pflag/ipnet_slice.go
  vendor/github.com/spf13/pflag/text.go
  vendor/github.com/spf13/pflag/time.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/golist_overlay.go
  vendor/golang.org/x/tools/internal/modindex/lookup.go
  vendor/golang.org/x/tools/internal/packagesinternal/packages.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#4483 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, size/L, skip-review

#4491 [release-1.19] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/observability/metrics/prometheus_enabled.go
  vendor/modules.txt
Labels: size/S, skip-review

#4487 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L, skip-review

#4499 fix typo in LoomConsumerFactoryTest class name
  data-plane/dispatcher-loom/src/test/java/dev/knative/eventing/kafka/broker/dispatcherloom/LoomConsumerFactoryTest.java
Labels: approved, size/XS, lgtm, ok-to-test, area/data-plane
