Repository knative-extensions/eventing-kafka-broker, pull requests merged in 2025-09, with the labels that each got.

#4512 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/XL, skip-review

#4530 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/listers.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/pod.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/statefulset.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/trigger.go
  vendor/modules.txt
Labels: approved, lgtm, size/L, skip-review

#4541 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/channel/event_receiver.go
  vendor/knative.dev/eventing/pkg/channel/references.go
  vendor/knative.dev/eventing/test/conformance/helpers/channel_tracing_test_helper.go
  vendor/modules.txt
Labels: approved, size/L, skip-review

#4544 Add volume template to kafka-*-dispatcher statefulsets for contract-resources volume
  data-plane/config/broker/500-dispatcher.yaml
  data-plane/config/channel/500-dispatcher.yaml
  data-plane/config/source/500-dispatcher.yaml
Labels: approved, size/XS, lgtm, area/data-plane

#4536 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: size/L, skip-review
