Repository knative-extensions/eventing-kafka-broker, pull requests merged in 2025-03, with the labels that each got.

#4290 Run `./hack/update-codegen.sh` on dependabot PRs
  .github/workflows/update-dependabot-pr.yaml
Labels: approved, size/M, lgtm, area/test

#4286 Fix golangci exclude config
  .golangci.yaml
Labels: approved, size/XS, lgtm

#4291 Bump github.com/go-jose/go-jose/v3 from 3.0.3 to 3.0.4
  go.mod
  go.sum
  vendor/github.com/go-jose/go-jose/v3/jwe.go
  vendor/github.com/go-jose/go-jose/v3/jws.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#4281 Allow configuring dispatchers min replicas
  control-plane/config/eventing-kafka-broker/200-controller/500-controller.yaml
  control-plane/pkg/reconciler/consumergroup/controller.go
  control-plane/pkg/reconciler/consumergroup/controller_test.go
Labels: approved, lgtm, size/S, area/control-plane

#4305 Update profiling gh action
  .github/workflows/knative-profile-data-plane.yaml
  data-plane/profiler/run.sh
Labels: approved, lgtm, size/S, area/data-plane, area/test

#4301 Bump to Quarkus 3.20 and friends
  data-plane/THIRD-PARTY.txt
  data-plane/pom.xml
Labels: approved, size/M, lgtm, area/data-plane

#4312 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
