Repository knative-extensions/eventing-kafka-broker, pull requests merged in 2025-06, with the labels that each got.

#4399 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/grpc/internal/resolver/delegatingresolver/delegatingresolver.go
  vendor/google.golang.org/grpc/version.go
  vendor/knative.dev/eventing/pkg/eventingtls/eventingtlstesting/eventingtlstesting.go
  vendor/knative.dev/eventing/pkg/kncloudevents/event_receiver.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#4403 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L, skip-review

#4414 Revert "Allow kafka-controller to list JobSinks (#4155)"
  control-plane/config/eventing-kafka-broker/200-controller/200-controller-cluster-role.yaml
Labels: approved, lgtm, size/S, area/control-plane

#4427 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/go.yaml.in/yaml/v2/.travis.yml
  vendor/go.yaml.in/yaml/v2/LICENSE
  vendor/go.yaml.in/yaml/v2/LICENSE.libyaml
  vendor/go.yaml.in/yaml/v2/NOTICE
  vendor/go.yaml.in/yaml/v2/README.md
  vendor/go.yaml.in/yaml/v2/apic.go
  vendor/go.yaml.in/yaml/v2/decode.go
  vendor/go.yaml.in/yaml/v2/emitterc.go
  vendor/go.yaml.in/yaml/v2/encode.go
  vendor/go.yaml.in/yaml/v2/parserc.go
  vendor/go.yaml.in/yaml/v2/readerc.go
  vendor/go.yaml.in/yaml/v2/resolve.go
  vendor/go.yaml.in/yaml/v2/scannerc.go
  vendor/go.yaml.in/yaml/v2/sorter.go
  vendor/go.yaml.in/yaml/v2/writerc.go
  vendor/go.yaml.in/yaml/v2/yaml.go
  vendor/go.yaml.in/yaml/v2/yamlh.go
  vendor/go.yaml.in/yaml/v2/yamlprivateh.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/integration_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/test/rekt/features/new_trigger_filters/feature.go
  vendor/modules.txt
  vendor/sigs.k8s.io/yaml/.travis.yml
  vendor/sigs.k8s.io/yaml/goyaml.v2/README.md
  vendor/sigs.k8s.io/yaml/goyaml.v2/yaml_aliases.go
  vendor/sigs.k8s.io/yaml/yaml.go
  vendor/sigs.k8s.io/yaml/yaml_go110.go
Labels: approved, lgtm, size/XL

#4428 [Automated] Update eventing-kafka-broker-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
Labels: approved, lgtm, size/L, skip-review
